/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, August 22, 2018 at 12:28:31 AM Central European Summer Time
* Operating System: Version 11.3.1 (Build 15E302)
* Image Source: /System/Library/PrivateFrameworks/ToneKit.framework/ToneKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ToneKit/ToneKit-Structs.h>
#import <UIKit/UIView.h>

@protocol TKVibrationRecorderStyleProvider;
@class UIView, NSLayoutConstraint, TKVibrationRecorderProgressDotImageView, NSMutableArray;

@interface TKVibrationRecorderProgressView : UIView {

	double _maximumTimeInterval;
	double _currentVibrationComponentDidBeginTimeInterval;
	double _previousPauseDidBeginTimeInterval;
	id<TKVibrationRecorderStyleProvider> _styleProvider;
	UIView* _progressView;
	NSLayoutConstraint* _progressViewWidthConstraint;
	TKVibrationRecorderProgressDotImageView* _dotForCurrentVibrationComponent;
	NSLayoutConstraint* _dotForCurrentVibrationComponentLeftConstraint;
	NSLayoutConstraint* _dotForCurrentVibrationComponentRightConstraint;
	NSMutableArray* _dots;
	int _roundedCornersCompensationDelayMode;
	double _currentTimeInterval;

}

@property (assign,nonatomic) double currentTimeInterval;                           //@synthesize currentTimeInterval=_currentTimeInterval - In the implementation block
@property (assign,nonatomic) int roundedCornersCompensationDelayMode;              //@synthesize roundedCornersCompensationDelayMode=_roundedCornersCompensationDelayMode - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)didMoveToWindow;
-(CGSize)intrinsicContentSize;
-(void)didMoveToSuperview;
-(id)accessibilityLabel;
-(CGRect)accessibilityFrame;
-(id)accessibilityValue;
-(BOOL)isAccessibilityElement;
-(id)initWithMaximumTimeInterval:(double)arg1 styleProvider:(id)arg2 ;
-(void)clearAllVibrationComponents;
-(void)setRoundedCornersCompensationDelayMode:(int)arg1 ;
-(void)setCurrentTimeInterval:(double)arg1 ;
-(void)vibrationComponentDidEnd;
-(void)vibrationComponentDidStart;
-(double)_cappedValueForTimeInterval:(double)arg1 ;
-(int)roundedCornersCompensationDelayMode;
-(UIOffset)_dotInsets;
-(CGSize)_dotSize;
-(CGRect)_frameForDotAtTimeInterval:(double)arg1 duration:(double)arg2 ;
-(void)_updateHorizontalConstraintsOfDotForCurrentVibrationComponent:(id)arg1 withFrame:(CGRect)arg2 ;
-(id)_resizableDotImage;
-(void)_updateProgressViewBackgroundColor;
-(double)currentTimeInterval;
@end

