swift_version: 4.1.2
sdk: iphoneos
author: Jesper Flodin
github_url: https://github.com/Jesperflodin1/ToneManager
module: ToneManager
module_version: 0.5
copyright: '© 2018 Jesper Flodin under [open source license](https://github.com/jesperflodin1/ToneManager/LICENSE'
root_url: https://jesperflodin1.github.io/ToneManager/
min_acl: private
