//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary;

@interface _LgControllerStandin : NSObject
{
    NSDictionary *_properties;
}

@property(readonly, retain) NSDictionary *properties; // @synthesize properties=_properties;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;

@end

