//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ABAudioUnitSource, ABPort, DBLocalEndpoint;

@interface ABAudioUnitSourceReservationRequest : NSObject
{
    double _creationTime;
    ABPort *_port;
    double _sampleRate;
    CDUnknownBlockType _completion;
    ABAudioUnitSource *_source;
    id _owner;
    DBLocalEndpoint *_endpoint;
}

@property(readonly, nonatomic) DBLocalEndpoint *endpoint; // @synthesize endpoint=_endpoint;
@property(readonly, nonatomic) id owner; // @synthesize owner=_owner;
@property(retain, nonatomic) ABAudioUnitSource *source; // @synthesize source=_source;
@property(readonly, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(readonly, nonatomic) double sampleRate; // @synthesize sampleRate=_sampleRate;
@property(readonly, nonatomic) ABPort *port; // @synthesize port=_port;
- (void).cxx_destruct;
- (id)description;
- (void)resetCreationDate;
@property(readonly, nonatomic) double reservationAgeInSeconds;
- (id)initWithPort:(id)arg1 sampleRate:(double)arg2 source:(id)arg3 endpoint:(id)arg4 owner:(id)arg5 completion:(CDUnknownBlockType)arg6;

@end

