//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ABFloatConverter, NSDate, NSMutableArray, NSString;

@interface ABAudioMute : NSObject
{
    _Bool _shouldBeMuted;
    NSMutableArray *_muteCompletionCallbacks;
    NSMutableArray *_unmuteCompletionCallbacks;
    _Bool _mutingInProgress;
    _Bool _unmutingInProgress;
    NSDate *_unmuteDate;
    NSDate *_muteDate;
    struct {
        double rampPosition;
        double isOnRamp;
        double fadeDuration;
    } _fadeInfo;
    _Bool _isSilent;
    struct AudioBufferList *_floatBuffer;
    NSString *_name;
    ABFloatConverter *_floatConverter;
    struct AudioStreamBasicDescription _audioFormat;
}

@property(retain, nonatomic) ABFloatConverter *floatConverter; // @synthesize floatConverter=_floatConverter;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) struct AudioStreamBasicDescription audioFormat; // @synthesize audioFormat=_audioFormat;
- (void).cxx_destruct;
- (void)completeUnmuting:(id)arg1;
- (void)checkIfSourceIsUnmuted;
- (void)unmuteWithCompletion:(CDUnknownBlockType)arg1;
- (void)completeMuting:(id)arg1;
- (void)checkIfSourceIsMuted;
- (void)muteWithCompletion:(CDUnknownBlockType)arg1;
@property(nonatomic) double fadeDuration;
@property(readonly, nonatomic) _Bool isSilent;
@property(nonatomic) _Bool shouldBeMuted;
- (id)description;
- (void)dealloc;
- (id)initWithInitialMute:(_Bool)arg1 audioFormat:(struct AudioStreamBasicDescription)arg2 fadeDuration:(double)arg3 name:(id)arg4;

@end

