//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSProxy.h>

@class UIImage;

@interface ABPeerResourceImageProxy : NSProxy
{
    unsigned int _resourceID;
    UIImage *_image;
}

+ (id)resourceImageProxyWithImage:(id)arg1 resourceID:(unsigned int)arg2;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (unsigned long long)hash;
- (id)initWithImage:(id)arg1 resourceID:(unsigned int)arg2;

@end

