//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ABPeer, NSSet;

@interface ABRegistry : NSObject
{
    NSSet *_peers;
    ABPeer *_selfPeer;
}

@property(retain, nonatomic) ABPeer *selfPeer; // @synthesize selfPeer=_selfPeer;
@property(retain, nonatomic) NSSet *peers; // @synthesize peers=_peers;
- (void).cxx_destruct;
- (id)peerHavingSameLaunchURLLikePeer:(id)arg1;
- (id)peerHavingSamePortsLikePeer:(id)arg1;
- (id)audiobusPeer;
- (id)updateOrCreatePeerFromPeerProperties:(id)arg1;
- (_Bool)peerAlreadyExists:(id)arg1;
- (id)peerWithName:(id)arg1 uniqueID:(id)arg2;
- (id)peerWithUniqueNumericID:(unsigned int)arg1;
- (void)removePeer:(id)arg1;
- (void)addPeer:(id)arg1;
- (id)initWithSelfPeer:(id)arg1;

@end

