//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class UIColor;

@interface CALayer (MACALayer_Extensions)
@property(nonatomic) UIColor *cbBackgroundColor;
@property(nonatomic) UIColor *cbShadowColor;
@property(nonatomic) UIColor *cbBorderColor;
@end

