//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CMMotionManager, CbVelocityAnalysisContext, CbVelocityAnalyzer;

@protocol CbAccelerometerManagerProtocol <NSObject>
+ (id)sharedManager;
@property(retain, nonatomic) CMMotionManager *motionManager;
- (double)pullVelocity;
- (double)currentAccelerationForAnalyzer:(CbVelocityAnalyzer *)arg1;
- (void)finishedAnalyzingWithAnalyzer:(CbVelocityAnalyzer *)arg1;
- (CbVelocityAnalyzer *)analyzerWithContext:(CbVelocityAnalysisContext *)arg1;
- (CbVelocityAnalyzer *)analyzer;
- (void)enableAccelerometerUpdatesGlobally;
- (void)disableAccelerometerUpdatesGlobally;

@optional
@property(nonatomic) double currentMaxAccel;
@property(nonatomic) double currentMinAccel;
@property(nonatomic) unsigned long long touchesCount;
- (void)endLog;
@end

