//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "APDCoachingTipManagerDelegate-Protocol.h"
#import "CBCentralManagerDelegate-Protocol.h"
#import "CbAppControllerDelegate-Protocol.h"
#import "CbApplicationDelegateProtocol-Protocol.h"
#import "MAInAppPurchaseDelegateProtocol-Protocol.h"
#import "MAUIExclusiveButtonDelegate-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"

@class CBCentralManager, CbAppController, CbMainContainerViewController, EcTimer, NSDate, NSString, NSURL, Reachability, UIResponder, UIView, UIWindow;
@protocol CbProgressIndicatorDelegate;

@interface CbAppDelegate : NSObject <UIApplicationDelegate, MAUIExclusiveButtonDelegate, MAInAppPurchaseDelegateProtocol, CbAppControllerDelegate, CBCentralManagerDelegate, CbApplicationDelegateProtocol, APDCoachingTipManagerDelegate>
{
    NSDate *m_batteryTestStartTime;
    EcTimer *m_heartbeatTimer;
    float m_batteryStartingLevel;
    long long m_batteryStartingState;
    CbMainContainerViewController *_mainViewController;
    UIResponder *_lockObject;
    struct __CFFileDescriptor *_kqRefFileTransfer;
    struct __CFFileDescriptor *_kqRefSharedDocuments;
    CbAppController *_appController;
    CBCentralManager *_bluetoothManager;
    long long _bluetoothState;
    NSURL *_airDropImportURL;
    int _virtualMidiDestinationUUID;
    _Bool _waitingForPendingOpenURLCallAtLaunch;
    UIWindow *_window;
    id <CbProgressIndicatorDelegate> _progressIndicatorDelegate;
    Reachability *_helpHostReachablity;
    NSURL *_pendingOpenInPlaceURL;
    CDUnknownBlockType _backgroundSessionCompletionHandler;
}

+ (id)sharedApplicationDelegate;
@property(copy) CDUnknownBlockType backgroundSessionCompletionHandler; // @synthesize backgroundSessionCompletionHandler=_backgroundSessionCompletionHandler;
@property(nonatomic) _Bool waitingForPendingOpenURLCallAtLaunch; // @synthesize waitingForPendingOpenURLCallAtLaunch=_waitingForPendingOpenURLCallAtLaunch;
@property(retain, nonatomic) NSURL *pendingOpenInPlaceURL; // @synthesize pendingOpenInPlaceURL=_pendingOpenInPlaceURL;
@property(readonly, nonatomic) long long bluetoothState; // @synthesize bluetoothState=_bluetoothState;
@property(readonly, nonatomic) Reachability *helpHostReachablity; // @synthesize helpHostReachablity=_helpHostReachablity;
@property(nonatomic) id <CbProgressIndicatorDelegate> progressIndicatorDelegate; // @synthesize progressIndicatorDelegate=_progressIndicatorDelegate;
@property(readonly, nonatomic) CbMainContainerViewController *mainViewController; // @synthesize mainViewController=_mainViewController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)appControllerDidUnregisterGlobalHandlers:(id)arg1;
- (void)appControllerDidRegisterGlobalHandlers:(id)arg1 isAppLaunch:(_Bool)arg2;
- (void)_stopSharedDocumentsChangeNotifier;
- (void)_startSharedDocumentsChangeNotifier;
- (void)_kqueueFired:(struct __CFFileDescriptor *)arg1;
- (_Bool)shouldShowExternalBluetoothRow;
- (void)centralManagerDidUpdateState:(id)arg1;
- (void)unlockForControl:(id)arg1;
- (_Bool)lockForControl:(id)arg1;
- (void)coachingTipManager:(id)arg1 coachingTipViewTapped:(id)arg2 APDID:(id)arg3;
- (_Bool)showGlobalHelp;
- (_Bool)showGlobalHelpPageWithAPDID:(id)arg1 showCoachingTipsAfterClosing:(_Bool)arg2;
- (_Bool)showHelpPageWithAPDID:(id)arg1 inViewController:(id)arg2 showCoachingTipsAfterClosing:(_Bool)arg3;
- (id)mobileGuideController;
- (void)showHelpError;
- (void)initializeMobileGuideFramework;
- (void)waitForMobileGuide;
- (void)purchaseActionDidFinishWithState:(long long)arg1 forProducts:(id)arg2 error:(id)arg3;
- (void)setBackgroundAudioForAudioBusOrInterappAudioEnabled:(_Bool)arg1 userPrefEnabled:(_Bool)arg2 useHighLatency:(_Bool)arg3 curDocument:(id)arg4;
- (void)setOutputOnlySessionEnabled:(_Bool)arg1;
- (void)dealloc;
- (void)application:(id)arg1 handleEventsForBackgroundURLSession:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)_collectQuickActionWithType:(id)arg1 userInfo:(id)arg2 doActionNow:(_Bool)arg3;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)appControllerApplicationWillResignActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)appControllerApplicationDidBecomeActive:(id)arg1 wasSuspended:(_Bool)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)appControllerApplicationWillTerminate:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)appControllerApplicationWillBeSuspended:(id)arg1;
- (void)appControllerDidStartApplication:(id)arg1;
- (id)appControllerAppName:(id)arg1;
- (_Bool)appControllerIsAnySongUIOpen:(id)arg1;
- (void)startMainViewController;
- (void)loadMainViewController;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_applicationDidSuspendedEventsOnly:(id)arg1;
- (void)_osMemoryStatusChanged:(id)arg1;
- (void)_maContentScanUpdated:(id)arg1;
- (void)_delayedSongImport;
- (void)importAirDropFromURL:(id)arg1 finishedHandler:(CDUnknownBlockType)arg2;
- (void)_checkForUpgrade;
- (void)_updateFactoryDefaultsPref;
- (void)_updateFactoryContentPrefs;
- (void)_initApplication;
- (void)_startBatteryLogging;
- (void)_batteryHeartbeat:(id)arg1;
@property(readonly, nonatomic) CbAppController *appController;
@property(readonly, nonatomic) UIView *mainView;
- (void)installGlobalProgressIndicatorService;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

