//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSKeyboardViewController.h"

#import "CbAUInstParameterDelegate-Protocol.h"

@class DfPlugIn, NSString;

@interface CbAUInstKeyboardViewController : MSKeyboardViewController <CbAUInstParameterDelegate>
{
    DfPlugIn *_currentPlugin;
    _Bool _ignoreValueChanges;
}

+ (_Bool)needsFullSizeFrameOnWidePadForTrack:(id)arg1;
- (void).cxx_destruct;
- (id)visibleHelpIndices;
- (id)allHelpIndices;
- (void)navBarZoomButtonPressed;
- (_Bool)navBarShouldShowZoomButton;
- (void)externalFullScreenModeWillCloseAnimated:(_Bool)arg1 targetViewSize:(struct CGSize)arg2;
- (void)externalFullScreenModeWillOpenAnimated:(_Bool)arg1 targetViewSize:(struct CGSize)arg2;
- (void)externalFullScreenModeDidCloseAnimated:(_Bool)arg1;
- (void)externalFullScreenModeDidOpenAnimated:(_Bool)arg1;
- (struct CGRect)externalFullScreenModeViewOriginalFrameInSuperview;
- (id)externalFullScreenModeSuperview;
- (id)externalFullScreenModeView;
- (void)changeToNextOrPreviousCST:(_Bool)arg1;
- (id)cstBrowserPassThroughViews;
- (_Bool)cstBrowserShouldCloseOnCSTSelection;
- (_Bool)cstBrowserGetsPresentedFromInstrumentBrowser;
- (void)cstBrowserSheetDidCloseForCSTBrowser:(id)arg1;
- (void)cstBrowserSheetWillCloseForCSTBrowser:(id)arg1;
- (void)cstBrowserDidHideNameEditorKeyboard:(id)arg1;
- (void)cstBrowserWillShowNameEditorKeyboard:(id)arg1;
- (_Bool)currentActiveCSTHasBassAmpTypeSelectedForCSTBrowser:(id)arg1;
- (void)cstBrowser:(id)arg1 currentActiveCSTWasRenamedToPath:(id)arg2;
- (void)cstBrowser:(id)arg1 saveCurrentActiveCSTToPath:(id)arg2;
- (id)currentActiveCSTSubCategoryForCSTBrowser:(id)arg1;
- (_Bool)currentActiveCSTIsDirtyForCSTBrowser:(id)arg1;
- (id)currentActiveCSTPathForCstBrowser:(id)arg1 isRecentsCategoryCST:(_Bool *)arg2;
- (void)cstBrowser:(id)arg1 selectedCSTAtPath:(id)arg2 isRecentsCategoryCST:(_Bool)arg3;
- (_Bool)useDefaultCSTBrowser;
- (void)plugInSettingChangedHandler:(id)arg1;
- (void)parameterDidChangeHandler:(id)arg1;
- (void)_handleAudioUnitDidLoadNotification:(id)arg1;
- (id)plugInParameterInfoArrayWithMaxNumber:(long long)arg1;
- (id)plugInValueInfoDictForParameter:(long long)arg1;
- (void)setValue:(long long)arg1 forParameter:(long long)arg2;
- (void)parameterChangeDidFinish:(long long)arg1;
- (void)parameterWillChange:(long long)arg1;
- (_Bool)supportsCSTButtonOnPhone;
- (void)controllerWillClose;
- (void)songWillClose;
- (void)openCstBrowserAction:(id)arg1;
- (_Bool)supportsParamEditMode;
- (void)viewDidLoad;
- (Class)keyboardImplClass;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

