//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "MAVeValueClient-Protocol.h"

@class MAVeUILabelView, MAVeUISeparatorGridView, NSMutableDictionary, NSObject, NSString;
@protocol CbAUInstParameterDelegate;

@interface CbAUInstParameterPageViewController : UIViewController <MAVeValueClient>
{
    NSObject<CbAUInstParameterDelegate> *_auPluginDelegate;
    unsigned long long _numParameterViews;
    unsigned long long _numRows;
    unsigned long long _numCols;
    NSMutableDictionary *_parameterViews;
    MAVeUISeparatorGridView *_gridView;
    MAVeUILabelView *_noParametersLabel;
}

@property(retain, nonatomic) MAVeUILabelView *noParametersLabel; // @synthesize noParametersLabel=_noParametersLabel;
@property(retain, nonatomic) MAVeUISeparatorGridView *gridView; // @synthesize gridView=_gridView;
@property(retain, nonatomic) NSMutableDictionary *parameterViews; // @synthesize parameterViews=_parameterViews;
@property(nonatomic) unsigned long long numCols; // @synthesize numCols=_numCols;
@property(nonatomic) unsigned long long numRows; // @synthesize numRows=_numRows;
@property(nonatomic) unsigned long long numParameterViews; // @synthesize numParameterViews=_numParameterViews;
@property(nonatomic) NSObject<CbAUInstParameterDelegate> *auPluginDelegate; // @synthesize auPluginDelegate=_auPluginDelegate;
- (void).cxx_destruct;
- (long long)styleForParameterType:(id)arg1;
- (void)connectParameterID:(id)arg1 withViewAdapter:(id)arg2 andValueID:(id)arg3;
- (id)attributedStringFromString:(id)arg1 withUnitString:(id)arg2;
- (id)viewsForParameterID:(long long)arg1;
- (_Bool)containsParameterID:(long long)arg1;
- (_Bool)isFull;
- (_Bool)isEmpty;
- (void)valueFinishedChange:(id)arg1;
- (void)valueDidChange:(id)arg1;
- (void)valueWillChange:(id)arg1;
- (void)updateParameter:(long long)arg1 withValueDict:(id)arg2;
- (void)setViewFrame:(struct CGRect)arg1;
- (void)addParameter:(id)arg1;
- (void)setupWithNumRows:(unsigned long long)arg1 numCols:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

