//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class DfTrack, NSArray, NSString, UINavigationController;

@interface CbAuthoringPlugInListController : UITableViewController <UITableViewDelegate, UITableViewDataSource>
{
    DfTrack *_track;
    unsigned long long _slot;
    _Bool _isMidiPlugIn;
    NSArray *_pluginList;
    UINavigationController *_navigationController;
}

- (void).cxx_destruct;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)initWith:(id)arg1 andTrack:(id)arg2 slot:(unsigned long long)arg3 isMidiPlugin:(_Bool)arg4 presentedByNavigationController:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

