//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CALayer, UIImage;

@interface CbAudioRecorderSelectionWheel : UIView
{
    CALayer *_wheelContainerLayer;
    CALayer *_selectionWheelLayer;
    CALayer *_selectionMaskLayer;
    CALayer *_selectionLightLayer;
    _Bool _shouldAnimate;
    _Bool _selectionHidden;
    UIImage *_wheelBackgroundImage;
    UIImage *_selectionMask;
    UIImage *_selectionLightBorderMask;
}

+ (Class)layerClass;
@property(nonatomic) _Bool selectionHidden; // @synthesize selectionHidden=_selectionHidden;
@property(retain, nonatomic) UIImage *selectionLightBorderMask; // @synthesize selectionLightBorderMask=_selectionLightBorderMask;
@property(retain, nonatomic) UIImage *selectionMask; // @synthesize selectionMask=_selectionMask;
@property(retain, nonatomic) UIImage *wheelBackgroundImage; // @synthesize wheelBackgroundImage=_wheelBackgroundImage;
- (void).cxx_destruct;
- (void)displayLayer:(id)arg1;
- (double)wheelAngleInRad;
- (void)setWheelAngleInRad:(double)arg1;
- (void)setWheelAnleInRad:(double)arg1 withduration:(double)arg2 startVelocity:(double)arg3 damping:(double)arg4 completion:(CDUnknownBlockType)arg5;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

