//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPinchGestureRecognizer.h>

@interface CbAXSyntheticPinchGestureRecognizer : UIPinchGestureRecognizer
{
    unsigned long long _timesProcessed;
    unsigned long long _maxTimesShouldProcess;
    _Bool _zoomingIn;
    CDUnknownBlockType _completionBlock;
    id _host;
}

@property(nonatomic) id host; // @synthesize host=_host;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
- (void).cxx_destruct;
- (void)synthesizePinch;
- (struct CGPoint)locationOfTouch:(unsigned long long)arg1 inView:(id)arg2;
- (unsigned long long)numberOfTouches;
- (long long)state;
- (void)dealloc;
- (id)initWithTarget:(id)arg1 host:(id)arg2 forZoomingIn:(_Bool)arg3 withCompletionBlock:(CDUnknownBlockType)arg4;

@end

