//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableSet, UIButton, UIImageView;

@interface CbComperTouchZone : UIView
{
    UIImageView *_touchZoneImageView;
    UIButton *_topStrumTrigger;
    long long _displayMode;
    UIButton *_bottomStrumTrigger;
    _Bool _isMuteZone;
    NSMutableSet *_currentTouches;
    unsigned long long _altCount;
    _Bool _isPlaying;
    _Bool _isSelected;
    _Bool _isEmpty;
}

@property(nonatomic) _Bool isEmpty; // @synthesize isEmpty=_isEmpty;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(nonatomic) _Bool isPlaying; // @synthesize isPlaying=_isPlaying;
@property long long displayMode; // @synthesize displayMode=_displayMode;
@property(readonly) unsigned long long altCount; // @synthesize altCount=_altCount;
@property _Bool isMuteZone; // @synthesize isMuteZone=_isMuteZone;
@property(readonly) UIButton *bottomStrumTrigger; // @synthesize bottomStrumTrigger=_bottomStrumTrigger;
@property(readonly) UIButton *topStrumTrigger; // @synthesize topStrumTrigger=_topStrumTrigger;
@property(readonly) UIImageView *touchZoneImageView; // @synthesize touchZoneImageView=_touchZoneImageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (unsigned long long)touchesCount;
- (_Bool)removeTouchFromCurrentTouches:(id)arg1;
- (void)addTouchToCurrentTouches:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;

@end

