//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CbStringImageCreator, NSMutableArray, NSString;
@protocol CbErhuStringsViewDelegate;

@interface CbErhuStringsView : UIView
{
    NSMutableArray *_stringViews;
    id <CbErhuStringsViewDelegate> _delegate;
    NSString *_stringSetFamily;
    CbStringImageCreator *_stringImageCreator;
}

@property(retain, nonatomic) CbStringImageCreator *stringImageCreator; // @synthesize stringImageCreator=_stringImageCreator;
@property(readonly, nonatomic) NSString *stringSetFamily; // @synthesize stringSetFamily=_stringSetFamily;
@property(nonatomic) __weak id <CbErhuStringsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateAssets;
- (void)updateFretPosition:(double)arg1 forString:(unsigned long long)arg2;
- (void)updateAmplitude:(double)arg1 forString:(unsigned long long)arg2;
- (void)layoutSubviews;
- (void)setStringSetFamily:(id)arg1;
- (id)init;

@end

