//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class CbTunerView, DfTrack, EcTimer, NSDictionary;

@interface CbExternalGuitarTunerViewController : UIViewController
{
    DfTrack *_tunerTrack;
    CbTunerView *_tunerView;
    EcTimer *_updateTimer;
    NSDictionary *_assets;
}

+ (id)viewControllerWithTrack:(id)arg1 andFrame:(struct CGRect)arg2;
+ (_Bool)isAnyGuitarTunerActive;
@property(retain, nonatomic) NSDictionary *assets; // @synthesize assets=_assets;
@property(retain, nonatomic) EcTimer *updateTimer; // @synthesize updateTimer=_updateTimer;
@property(retain, nonatomic) CbTunerView *tunerView; // @synthesize tunerView=_tunerView;
@property(nonatomic) __weak DfTrack *tunerTrack; // @synthesize tunerTrack=_tunerTrack;
- (void).cxx_destruct;
- (void)audioDriverChangedHandler:(id)arg1;
- (void)stopTuner;
- (void)startTunerForTrack:(id)arg1;
- (void)onUpdateTimer:(id)arg1;
- (id)initWithTrack:(id)arg1 andFrame:(struct CGRect)arg2;
- (void)dealloc;
- (id)createViewWithFrame:(struct CGRect)arg1;
- (void)controllerWillClose;

@end

