//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CbLocalPublishers.h"

#import "CbCheckSongOpenAlertDelegate-Protocol.h"

@class NSString, UIViewController;

@interface CbExportFor3rdParties : CbLocalPublishers <CbCheckSongOpenAlertDelegate>
{
    UIViewController *_dummyViewController;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)songExportDidCancel:(id)arg1;
- (void)songExportDidFail:(id)arg1 error:(id)arg2;
- (void)songExportDidFinish:(id)arg1;
- (void)checkSongOpenAlertDidFinishWithButtonIndex:(long long)arg1 alertInfo:(id)arg2 alertTag:(long long)arg3;
- (void)cleanUpControllers;
- (void)showWithExportDialogController:(id)arg1;
- (void)show;
- (void)startPublish;
- (id)progressString;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

