//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "MAUICleanable-Protocol.h"

@class CALayer, CbDrummerInstrumentIconAnimationOpenGL, NSString, UIImage, UITextView;

@interface CbFlipImageView : UIView <MAUICleanable>
{
    CALayer *_imageLayer;
    CALayer *_inAppGlyphLayer;
    UIImage *_image;
    UITextView *_descriptionTextView;
    id _target;
    SEL _action;
    CbDrummerInstrumentIconAnimationOpenGL *_drummerAnimation;
    _Bool _inAppPurchaseMode;
    _Bool _isAnimatable;
    NSString *_assetName;
}

@property(nonatomic) _Bool isAnimatable; // @synthesize isAnimatable=_isAnimatable;
@property(nonatomic) _Bool inAppPurchaseMode; // @synthesize inAppPurchaseMode=_inAppPurchaseMode;
@property(retain, nonatomic) NSString *assetName; // @synthesize assetName=_assetName;
- (void).cxx_destruct;
- (id)_viewToAnimateIn;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)stopAnimating;
- (void)startAnimating;
@property(readonly, nonatomic) _Bool isAnimating;
@property(retain, nonatomic) UIImage *image;
- (void)setScaleFactor:(double)arg1;
- (void)setAlpha:(double)arg1;
- (void)setDescriptionText:(id)arg1;
- (void)setTarget:(id)arg1 action:(SEL)arg2;
- (void)cleanup;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

