//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CbGenInstSlider, MAUIInfoOverlayViewController, MAUISlider, NSNumberFormatter, NSString, UILabel;

@interface CbGenInstSliderControl : UIView
{
    struct CGRect sliderOriginFrame;
    UIView *sliderAnimationContainer;
    UIView *sliderOutline;
    UIView *sliderTickMarks;
    UIView *sliderValueIndication;
    _Bool _animateSlider;
    _Bool _selected;
    _Bool _enabled;
    _Bool _close;
    _Bool _showSliderValueIndication;
    _Bool _enableInfoOverlay;
    UILabel *_label;
    NSNumberFormatter *_infoOverlayFormatter;
    CbGenInstSlider *_slider;
    MAUIInfoOverlayViewController *_infoOverlayController;
    struct CGSize _sliderThumbSize;
}

@property(retain, nonatomic) MAUIInfoOverlayViewController *infoOverlayController; // @synthesize infoOverlayController=_infoOverlayController;
@property(retain, nonatomic) CbGenInstSlider *slider; // @synthesize slider=_slider;
@property(retain, nonatomic) NSNumberFormatter *infoOverlayFormatter; // @synthesize infoOverlayFormatter=_infoOverlayFormatter;
@property(nonatomic) _Bool enableInfoOverlay; // @synthesize enableInfoOverlay=_enableInfoOverlay;
@property(nonatomic) _Bool showSliderValueIndication; // @synthesize showSliderValueIndication=_showSliderValueIndication;
@property(nonatomic) _Bool close; // @synthesize close=_close;
@property(nonatomic) struct CGSize sliderThumbSize; // @synthesize sliderThumbSize=_sliderThumbSize;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (void)updateColors;
- (void)updateFrames;
- (id)sliderColor;
- (void)layoutSliderValueIndication;
- (void)layoutTickMarks;
- (void)layoutTickMarksTrack;
- (void)layoutOutline;
- (void)layoutSlider;
- (void)layoutSliderAnimationContainer;
- (void)layoutComponents;
- (long long)outlineInset;
@property(nonatomic) long long numberOfTickMarks;
@property(nonatomic) _Bool animateSlider;
@property(nonatomic) float sliderValueMin;
@property(nonatomic) float sliderValueMax;
@property(nonatomic) float sliderValue;
@property(nonatomic) NSString *labelText;
@property(readonly, nonatomic) MAUISlider *valueSlider;
- (void)setFrame:(struct CGRect)arg1;
- (void)updateInfoOverlay;
- (void)endInfoOverlay;
- (void)startInfoOverlay;
- (void)closeInfoOverlayImmediatelyAndRelease;
- (void)closeSliderAnimated;
- (void)openSliderAnimated;
- (void)sliderTouchUp:(id)arg1;
- (void)valueChanged:(id)arg1;
- (void)sliderTouchDown:(id)arg1;
- (void)updateSliderComponentFrames;
- (void)createSliderComponents;
- (void)dealloc;
- (void)awakeFromNib;

@end

