//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class CbHelpOverlayMainViewController, NSMutableArray;

@interface CbHelpOverlayPageViewController : UIViewController
{
    CbHelpOverlayMainViewController *_mainHelpController;
    NSMutableArray *_userInteractionControls;
}

@property(readonly, nonatomic) CbHelpOverlayMainViewController *mainHelpController; // @synthesize mainHelpController=_mainHelpController;
- (void).cxx_destruct;
- (void)setViewVisible:(_Bool)arg1 withTag:(long long)arg2 animate:(_Bool)arg3;
- (id)viewWithTag:(long long)arg1;
- (void)setAssetSet:(id)arg1;
- (void)viewDidLoad;
- (id)_convertLabelTextToAttributedString:(id)arg1;
- (void)moveUserInteractionControlsToView:(id)arg1;
- (void)moveUserInteractionControlsBackToHelpPage;
- (void)dealloc;
- (void)viewDidUnload;
- (void)cleanUp;
- (void)removeUserinteractionControls;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 mainHelpController:(id)arg3;

@end

