//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSMutableDictionary, NSString, UITableView;
@protocol CbImportControllerDelegate;

@interface CbImportDialogController : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *_tableView;
    id <CbImportControllerDelegate> _songBrowser;
    NSMutableDictionary *_thumbs;
    _Bool _deleting;
    NSArray *_sharedSongFileInfos;
}

+ (id)readSharedDirectory;
@property(nonatomic) id <CbImportControllerDelegate> songBrowser; // @synthesize songBrowser=_songBrowser;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)significantTimeChange:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 editActionsForRowAtIndexPath:(id)arg2;
- (id)thumbForSongInfo:(id)arg1;
- (void)closeAction:(id)arg1;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillAppear:(_Bool)arg1;
- (void)_appDidBecomeActive:(id)arg1;
- (void)viewDidLoad;
- (void)checkSongDirectory;
@property(readonly, nonatomic) NSArray *sharedSongFileInfos; // @synthesize sharedSongFileInfos=_sharedSongFileInfos;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

