//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString;

@interface CbInputMethodInfo : NSObject
{
    NSString *key;
    NSString *controllerClassName;
    NSString *controllerClassNameIPhone;
    NSString *name;
    NSString *description;
    int trackType;
    NSArray *CSTFolders;
    NSString *defaultCSTName;
    _Bool allowsLoops;
    _Bool allowsQuantization;
    _Bool allowsTransposition;
    _Bool allowsOverDub;
    _Bool allowsVelocitySensitivity;
    _Bool allowsCymbalBassTrigger;
    _Bool isBiggerThanOtherTIsIfNecessary;
    NSString *templateSongName;
    _Bool canSaveCST;
    _Bool isFakeEntry;
    NSString *fakeEntryResultingIMKey;
    NSString *_defaultCSTNameChinese;
    NSString *_defaultGenInstGenreID;
    NSString *_defaultGenInstCharacterID;
}

+ (id)fakeInfoWithKey:(id)arg1 andName:(id)arg2 description:(id)arg3 ibSndLevelClassName:(id)arg4 ibSndLevelClassNameiPhone:(id)arg5 trackInputMethodKey:(id)arg6;
+ (id)infoWithKey:(id)arg1 className:(id)arg2 classNameIPhone:(id)arg3 andName:(id)arg4 description:(id)arg5 templateSongName:(id)arg6 trackType:(int)arg7 CSTFolders:(id)arg8 defCSTName:(id)arg9 defCSTNameForChinese:(id)arg10 defGenInstGenre:(id)arg11 defGenInstCharacter:(id)arg12 loops:(_Bool)arg13 quantization:(_Bool)arg14 transposition:(_Bool)arg15 overDub:(_Bool)arg16 velocitySensitivity:(_Bool)arg17 cymbalBassTrigger:(_Bool)arg18 canSaveCST:(_Bool)arg19 isBiggerThanOtherTIsIfNecessary:(_Bool)arg20;
@property(retain, nonatomic) NSString *defaultGenInstCharacterID; // @synthesize defaultGenInstCharacterID=_defaultGenInstCharacterID;
@property(retain, nonatomic) NSString *defaultGenInstGenreID; // @synthesize defaultGenInstGenreID=_defaultGenInstGenreID;
@property(retain, nonatomic) NSString *defaultCSTNameChinese; // @synthesize defaultCSTNameChinese=_defaultCSTNameChinese;
@property(retain, nonatomic) NSString *fakeEntryResultingIMKey; // @synthesize fakeEntryResultingIMKey;
@property(nonatomic) _Bool canSaveCST; // @synthesize canSaveCST;
@property(nonatomic) _Bool isBiggerThanOtherTIsIfNecessary; // @synthesize isBiggerThanOtherTIsIfNecessary;
@property(nonatomic) _Bool allowsCymbalBassTrigger; // @synthesize allowsCymbalBassTrigger;
@property(nonatomic) _Bool allowsVelocitySensitivity; // @synthesize allowsVelocitySensitivity;
@property(nonatomic) _Bool allowsOverDub; // @synthesize allowsOverDub;
@property(nonatomic) _Bool allowsTransposition; // @synthesize allowsTransposition;
@property(nonatomic) _Bool allowsQuantization; // @synthesize allowsQuantization;
@property(nonatomic) _Bool allowsLoops; // @synthesize allowsLoops;
@property(retain, nonatomic) NSString *defaultCSTName; // @synthesize defaultCSTName;
@property(retain, nonatomic) NSArray *CSTFolders; // @synthesize CSTFolders;
@property int trackType; // @synthesize trackType;
@property(retain, nonatomic) NSString *templateSongName; // @synthesize templateSongName;
@property(retain, nonatomic) NSString *description; // @synthesize description;
@property(retain, nonatomic) NSString *name; // @synthesize name;
@property(retain, nonatomic) NSString *controllerClassNameIPhone; // @synthesize controllerClassNameIPhone;
@property(retain, nonatomic) NSString *controllerClassName; // @synthesize controllerClassName;
@property(retain, nonatomic) NSString *key; // @synthesize key;
@property(nonatomic) _Bool isFakeEntry; // @synthesize isFakeEntry;
- (void).cxx_destruct;
- (void)dealloc;

@end

