//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CbInputChannelController;

@protocol CbInputChannelControllerDelegate <NSObject>
- (_Bool)stereoIsAllowedForInputChannelController:(CbInputChannelController *)arg1;
- (void)inputChannelController:(CbInputChannelController *)arg1 activeChannelIndex:(long long *)arg2 numChannels:(long long *)arg3;
- (void)inputChannelController:(CbInputChannelController *)arg1 setActiveChannelIndex:(long long)arg2 numChannels:(long long)arg3;
@end

