//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableSet, UIImageView;

@interface CbKeysComperButtonRowContainerView : UIView
{
    _Bool _isEmpty;
    NSMutableSet *_activeTouches;
    unsigned long long _touchCount;
    unsigned long long _previousTouchCount;
    unsigned long long _altIndex;
    unsigned long long _previousAltIndex;
    UIImageView *_offImageView;
    UIImageView *_normalImageView;
    UIImageView *_pulseImageView;
}

@property _Bool isEmpty; // @synthesize isEmpty=_isEmpty;
@property(retain) UIImageView *pulseImageView; // @synthesize pulseImageView=_pulseImageView;
@property(retain) UIImageView *normalImageView; // @synthesize normalImageView=_normalImageView;
@property(retain) UIImageView *offImageView; // @synthesize offImageView=_offImageView;
@property unsigned long long previousAltIndex; // @synthesize previousAltIndex=_previousAltIndex;
@property unsigned long long altIndex; // @synthesize altIndex=_altIndex;
@property unsigned long long previousTouchCount; // @synthesize previousTouchCount=_previousTouchCount;
@property unsigned long long touchCount; // @synthesize touchCount=_touchCount;
@property(retain) NSMutableSet *activeTouches; // @synthesize activeTouches=_activeTouches;
- (void).cxx_destruct;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

