//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CbComperButtonRow.h"

#import "MAUIForwardTouchGestureRecognizerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class MAUIForwardTouchGestureRecognizer, NSMutableArray, NSString, NSTimer, UIImage, UITouch;

@interface CbKeysComperButtonRow : CbComperButtonRow <UIGestureRecognizerDelegate, MAUIForwardTouchGestureRecognizerDelegate>
{
    NSMutableArray *_containerViews;
    NSMutableArray *_eventArray;
    UITouch *_lastTouch;
    NSTimer *_popTimer;
    double _offImageYOffset;
    UIImage *_offImage;
    UIImage *_pressedImage;
    UIImage *_pressedPulseImage;
    UIImage *_highlightedImage;
    UIImage *_highlightedPulseImage;
    unsigned long long _elementQty;
    unsigned long long _maxAltIndex;
    MAUIForwardTouchGestureRecognizer *_forwardTouchGestureRecognizer;
}

@property(retain, nonatomic) MAUIForwardTouchGestureRecognizer *forwardTouchGestureRecognizer; // @synthesize forwardTouchGestureRecognizer=_forwardTouchGestureRecognizer;
@property(nonatomic) unsigned long long maxAltIndex; // @synthesize maxAltIndex=_maxAltIndex;
@property(nonatomic) unsigned long long elementQty; // @synthesize elementQty=_elementQty;
@property(retain, nonatomic) UIImage *highlightedPulseImage; // @synthesize highlightedPulseImage=_highlightedPulseImage;
@property(retain, nonatomic) UIImage *highlightedImage; // @synthesize highlightedImage=_highlightedImage;
@property(retain, nonatomic) UIImage *pressedPulseImage; // @synthesize pressedPulseImage=_pressedPulseImage;
@property(retain, nonatomic) UIImage *pressedImage; // @synthesize pressedImage=_pressedImage;
@property(retain, nonatomic) UIImage *offImage; // @synthesize offImage=_offImage;
@property(nonatomic) double offImageYOffset; // @synthesize offImageYOffset=_offImageYOffset;
- (void).cxx_destruct;
- (_Bool)isEmptyAtIndex:(long long)arg1;
- (void)setEmpty:(_Bool)arg1 atIndex:(long long)arg2;
- (void)clearSelectionIfNotEqualToIndex:(long long)arg1;
- (void)selectChordAtIndex:(unsigned long long)arg1;
- (unsigned long long)_containerIndexForTouch:(id)arg1;
- (unsigned long long)_locationIndexForTouch:(id)arg1;
- (void)animate;
- (void)_selectItemAtIndex:(long long)arg1 usePressedImage:(_Bool)arg2;
- (void)_setCurrentSelectionIndex:(long long)arg1 force:(_Bool)arg2 interactive:(_Bool)arg3;
- (void)setCurrentSelectionIndex:(long long)arg1;
- (void)setCurrentSelectionIndexNonInteractively:(long long)arg1;
- (void)_resetPopTimer;
- (void)_setAltIndexForTouchCount:(unsigned long long)arg1;
- (void)_removeTouchFromContainers:(id)arg1;
- (void)processEvents;
- (void)_pushEvent:(id)arg1;
- (void)mauiTouchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)mauiTouchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)mauiTouchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)mauiTouchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)reset;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setEditingChords:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

