//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

#import "CbScreenshotable-Protocol.h"

@class CbStrokeLabel, UIImage, UIImageView;

@interface CbLeslieSlider : UIControl <CbScreenshotable>
{
    int value;
    UIImage *backgroundImage;
    UIImageView *slider;
    UIImage *onImage;
    UIImage *offImage;
    CbStrokeLabel *onLabel;
    CbStrokeLabel *offLabel;
    CbStrokeLabel *label;
    _Bool verticalMode;
}

@property(nonatomic) _Bool verticalMode; // @synthesize verticalMode;
@property(nonatomic) int value; // @synthesize value;
- (void).cxx_destruct;
- (void)restoreFromScreenshotType:(int)arg1;
- (void)prepareForScreenshotType:(int)arg1;
- (void)setAssetSet:(id)arg1;
- (void)settingsDidChange;
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)cancelTrackingWithEvent:(id)arg1;
- (_Bool)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (_Bool)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)updateForPoint:(struct CGPoint)arg1;
- (id)imageForState:(int)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

