//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "CbMediaImportContentSourceProtocol-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class CbFilterView, CbLoopsFilterButton, CbMediaImportController, NSArray, NSDictionary, NSIndexPath, NSLayoutConstraint, NSMutableDictionary, NSMutableSet, NSObject, NSSet, NSString, UIButton, UIImage, UILabel, UIScrollView, UISearchBar, UISlider, UITableView, UIView;
@protocol CbLoopSearchModelInterface, CbMediaImportTargetProtocol;

@interface CbLoopsViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, CbMediaImportContentSourceProtocol, UIGestureRecognizerDelegate>
{
    NSDictionary *_descriptorKeywordsMappingDict;
    NSDictionary *_genreKeywordsMappingDict;
    NSDictionary *_instrumentKeywordsOrderDict;
    NSArray *_genreKeywords;
    NSSet *_availableGenreKeywords;
    NSString *_currentInstrumentKeyword;
    NSMutableSet *_currentGenreKeywords;
    NSMutableSet *_currentDescriptorKeywords;
    long long _playingRow;
    NSDictionary *_instrumentIconMapping;
    UIImage *_realInstrumentIcon;
    UIImage *_redInstrumentIcon;
    UIImage *_softInstrumentIcon;
    UIImage *_playIcon;
    NSMutableDictionary *_assetsToInvalidate;
    _Bool _instrumentViewSetupDone;
    _Bool _descriptorsViewSetupDone;
    _Bool _resetButtonEnabled;
    _Bool _allowToCacheVisibleScrollRect;
    _Bool _searchBarIsEditing;
    _Bool _filterViewVisibleOnStartDragging;
    _Bool _disableFilterViewScrolling;
    _Bool _ignoreSearchBarDelegateCalls;
    struct CGPoint _contentOffsetStartDragging;
    double _filterViewHeightOnDragStart;
    _Bool _forceToResultTablePage;
    _Bool _shouldShowIndexTitles;
    _Bool _scrollViewIsDecelerating;
    _Bool _scrollViewIsDragging;
    UITableView *_resultTableView;
    UITableView *_genreTableView;
    UIView *_mainView;
    UIView *_instrumentView;
    UIView *_genreView;
    UIView *_descriptorsView;
    UIView *_noLoopsAvailableView;
    UIScrollView *_instrumentButtonsContainerView;
    UIView *_descriptorsButtonsContainerView;
    UILabel *_selectedInstrumentLabel;
    UILabel *_selectedGenreLabel;
    UILabel *_selectedDescriptorsLabel;
    UILabel *_numberOfResultItemsLabel;
    UISlider *_volumeSlider;
    UISearchBar *_searchBar;
    CbFilterView *_filterView;
    UILabel *_filterViewDescriptionLabel;
    UIScrollView *_descriptorsScrollView;
    CbLoopsFilterButton *_resetFilterButton;
    CbLoopsFilterButton *_leftFilterButton;
    CbLoopsFilterButton *_middleFilterButton;
    CbLoopsFilterButton *_rightFilterButton;
    CbLoopsFilterButton *_favoriteFilterButton;
    CbLoopsFilterButton *_dummyFilterButton;
    UIButton *_resetButton;
    UIView *_moreAppleLoopsButtonContainerView;
    UIButton *_moreAppleLoopsButton;
    UIView *_resetButtonContainerView;
    UIView *_filterButtonContainerView;
    id <CbMediaImportTargetProtocol> _mediaImportTargetViewController;
    CbMediaImportController *_mediaImportController;
    NSObject<CbLoopSearchModelInterface> *_searchEngine;
    NSIndexPath *_playingIndexPath;
    NSLayoutConstraint *_filterViewTopConstraint;
    NSLayoutConstraint *_filterViewHeightConstraint;
    double _filterViewOriginalHeight;
    double _filterViewMinimalHeight;
    NSString *_searchbarLastEditingText;
    UIView *_searchBarShrinkingView;
}

+ (void)rebuildAdditionalKeywordsArray;
+ (void)resetLoopBrowserFilters;
+ (void)resetScrollRectMemory;
@property(retain, nonatomic) UIView *searchBarShrinkingView; // @synthesize searchBarShrinkingView=_searchBarShrinkingView;
@property(retain, nonatomic) NSString *searchbarLastEditingText; // @synthesize searchbarLastEditingText=_searchbarLastEditingText;
@property(nonatomic) double filterViewMinimalHeight; // @synthesize filterViewMinimalHeight=_filterViewMinimalHeight;
@property(nonatomic) double filterViewOriginalHeight; // @synthesize filterViewOriginalHeight=_filterViewOriginalHeight;
@property(retain, nonatomic) NSLayoutConstraint *filterViewHeightConstraint; // @synthesize filterViewHeightConstraint=_filterViewHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *filterViewTopConstraint; // @synthesize filterViewTopConstraint=_filterViewTopConstraint;
@property(nonatomic) _Bool scrollViewIsDragging; // @synthesize scrollViewIsDragging=_scrollViewIsDragging;
@property(nonatomic) _Bool scrollViewIsDecelerating; // @synthesize scrollViewIsDecelerating=_scrollViewIsDecelerating;
@property(nonatomic) _Bool shouldShowIndexTitles; // @synthesize shouldShowIndexTitles=_shouldShowIndexTitles;
@property(retain, nonatomic) NSSet *availableGenreKeywords; // @synthesize availableGenreKeywords=_availableGenreKeywords;
@property(retain, nonatomic) NSIndexPath *playingIndexPath; // @synthesize playingIndexPath=_playingIndexPath;
@property(retain, nonatomic) NSObject<CbLoopSearchModelInterface> *searchEngine; // @synthesize searchEngine=_searchEngine;
@property(nonatomic) _Bool forceToResultTablePage; // @synthesize forceToResultTablePage=_forceToResultTablePage;
@property(nonatomic) __weak CbMediaImportController *mediaImportController; // @synthesize mediaImportController=_mediaImportController;
@property(nonatomic) __weak id <CbMediaImportTargetProtocol> mediaImportTargetViewController; // @synthesize mediaImportTargetViewController=_mediaImportTargetViewController;
@property(retain, nonatomic) UIView *filterButtonContainerView; // @synthesize filterButtonContainerView=_filterButtonContainerView;
@property(retain, nonatomic) UIView *resetButtonContainerView; // @synthesize resetButtonContainerView=_resetButtonContainerView;
@property(retain, nonatomic) UIButton *moreAppleLoopsButton; // @synthesize moreAppleLoopsButton=_moreAppleLoopsButton;
@property(retain, nonatomic) UIView *moreAppleLoopsButtonContainerView; // @synthesize moreAppleLoopsButtonContainerView=_moreAppleLoopsButtonContainerView;
@property(retain, nonatomic) UIButton *resetButton; // @synthesize resetButton=_resetButton;
@property(retain, nonatomic) CbLoopsFilterButton *dummyFilterButton; // @synthesize dummyFilterButton=_dummyFilterButton;
@property(retain, nonatomic) CbLoopsFilterButton *favoriteFilterButton; // @synthesize favoriteFilterButton=_favoriteFilterButton;
@property(retain, nonatomic) CbLoopsFilterButton *rightFilterButton; // @synthesize rightFilterButton=_rightFilterButton;
@property(retain, nonatomic) CbLoopsFilterButton *middleFilterButton; // @synthesize middleFilterButton=_middleFilterButton;
@property(retain, nonatomic) CbLoopsFilterButton *leftFilterButton; // @synthesize leftFilterButton=_leftFilterButton;
@property(retain, nonatomic) CbLoopsFilterButton *resetFilterButton; // @synthesize resetFilterButton=_resetFilterButton;
@property(retain, nonatomic) UIScrollView *descriptorsScrollView; // @synthesize descriptorsScrollView=_descriptorsScrollView;
@property(retain, nonatomic) UILabel *filterViewDescriptionLabel; // @synthesize filterViewDescriptionLabel=_filterViewDescriptionLabel;
@property(retain, nonatomic) CbFilterView *filterView; // @synthesize filterView=_filterView;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) UISlider *volumeSlider; // @synthesize volumeSlider=_volumeSlider;
@property(retain, nonatomic) UILabel *numberOfResultItemsLabel; // @synthesize numberOfResultItemsLabel=_numberOfResultItemsLabel;
@property(retain, nonatomic) UILabel *selectedDescriptorsLabel; // @synthesize selectedDescriptorsLabel=_selectedDescriptorsLabel;
@property(retain, nonatomic) UILabel *selectedGenreLabel; // @synthesize selectedGenreLabel=_selectedGenreLabel;
@property(retain, nonatomic) UILabel *selectedInstrumentLabel; // @synthesize selectedInstrumentLabel=_selectedInstrumentLabel;
@property(retain, nonatomic) UIView *descriptorsButtonsContainerView; // @synthesize descriptorsButtonsContainerView=_descriptorsButtonsContainerView;
@property(retain, nonatomic) UIScrollView *instrumentButtonsContainerView; // @synthesize instrumentButtonsContainerView=_instrumentButtonsContainerView;
@property(retain, nonatomic) UIView *noLoopsAvailableView; // @synthesize noLoopsAvailableView=_noLoopsAvailableView;
@property(retain, nonatomic) UIView *descriptorsView; // @synthesize descriptorsView=_descriptorsView;
@property(retain, nonatomic) UIView *genreView; // @synthesize genreView=_genreView;
@property(retain, nonatomic) UIView *instrumentView; // @synthesize instrumentView=_instrumentView;
@property(retain, nonatomic) UIView *mainView; // @synthesize mainView=_mainView;
@property(retain, nonatomic) UITableView *genreTableView; // @synthesize genreTableView=_genreTableView;
@property(retain, nonatomic) UITableView *resultTableView; // @synthesize resultTableView=_resultTableView;
- (void).cxx_destruct;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (_Bool)indexTitlesEnabled;
- (void)keyboardDidHide:(id)arg1;
- (void)audioDriverChangedHandler:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (_Bool)searchBarShouldEndEditing:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (id)iconNameForFile:(id)arg1;
- (id)localizedNameForFile:(id)arg1;
- (id)chineseInstrumentsReplacementForFilename:(id)arg1;
- (void)moreAppleLoopsButtonAction:(id)arg1;
- (void)favoriteButtonAction:(id)arg1;
- (void)descriptorsChooserButtonAction:(id)arg1;
- (void)genreChooserButtonAction:(id)arg1;
- (void)instrumentChooserButtonAction:(id)arg1;
- (void)_rowFavoriteButtonAction:(id)arg1;
- (void)_scrollFilterViewToVisibleAreaGesture:(id)arg1;
- (void)_scrollFilterViewToVisibleAreaAnimated:(_Bool)arg1;
- (void)_rowImportButtonAction:(id)arg1;
- (void)volumeSliderDoubleTapAction:(id)arg1;
- (void)volumeSliderAction:(id)arg1;
- (void)resetButtonAction:(id)arg1;
- (void)descriptorButtonAction:(id)arg1;
- (void)instrumentButtonAction:(id)arg1;
- (void)filterButtonActionForFilter:(int)arg1;
- (id)_adjustNameIfNeeded:(id)arg1 forIndexPath:(id)arg2;
- (long long)unreadAvailableContentCount;
- (void)updateButtonForFilter:(int)arg1;
- (void)updateFilterLabels;
- (struct CGSize)preferredContentSize;
- (id)fullpathFromURLSearchResult:(id)arg1;
- (id)loopPackNameFromURLSearchResult:(id)arg1;
- (void)descriptorControlAction:(id)arg1;
- (void)setupInstrumentsView;
- (void)setupDescriptorsButtonsContainerView;
- (void)didChooseKeywords:(id)arg1 forCategory:(id)arg2;
- (void)setupView:(id)arg1 forKeywords:(id)arg2 keywordsMappingDict:(id)arg3;
- (id)createSearchEngine;
- (Class)searchModelClass;
- (void)preListenAudioFile:(id)arg1 changeFileOnly:(_Bool)arg2;
- (void)delayedSetPrelisten:(id)arg1;
- (void)clearMediaImportControllerRef;
- (id)segmentedControlPlaceholderString;
- (long long)currentItemsCount;
- (void)updateTitleForMediaImporter;
- (void)controllerDidMinimize:(_Bool)arg1;
- (void)controllerWillMinimize:(_Bool)arg1;
- (void)controllerWillBeHiddenInMediaController;
- (void)controllerWillBeShownInMediaController;
- (void)saveScrollPositionForPoint:(struct CGPoint)arg1;
- (void)handleTableEntryLongPressedAction:(id)arg1;
- (void)stopPrelisteningImmediately;
- (void)stopPrelistening;
- (id)dragFileInfoForTableViewPoint:(struct CGPoint)arg1;
- (void)scrollTableViewToTop;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willDeselectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 indentationLevelForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateFilterView;
- (void)dealloc;
- (void)cleanup;
- (void)didReceiveMemoryWarning;
- (_Bool)specialContentFilterOn;
- (_Bool)isPhonePlusUI;
- (_Bool)isSheet;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (id)defaultBackgroundColor;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithMediaImporterController:(id)arg1;
- (void)rememberAssetSetWithName:(id)arg1 fromFamily:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

