//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "CbInstrumentBrowserDelegate-Protocol.h"
#import "CbSongCollectionManagerDelegate-Protocol.h"
#import "MAUITransitionViewDelegate-Protocol.h"

@class CbAlert, CbDocumentBrowserContainerViewController, CbSongMainViewController, CbSongTempOpenCloseAnimationHelperViewController, MAUILEDLevelMeterView, MAUIProgressViewController, MAUISlider, MAUITransitionView, NSString, UIAlertController, UIButton, UIColor, UIImage, UIImageView, UIView;

@interface CbMainContainerViewController : UIViewController <CbSongCollectionManagerDelegate, MAUITransitionViewDelegate, CbInstrumentBrowserDelegate>
{
    _Bool _shouldShowCoachingTipsAfterRotate;
    MAUITransitionView *_transitionView;
    CbSongTempOpenCloseAnimationHelperViewController *_songOpenCloseTransitioHelper;
    CbDocumentBrowserContainerViewController *_songBrowser;
    CbSongMainViewController *_songMainViewController;
    MAUIProgressViewController *_progressViewCon;
    UIAlertController *_songSavingAlert;
    CbAlert *_audioOutputRouteAlert;
    UIColor *_navigationBarAmbientColor;
    UIImage *_navigationBarAmbientImage;
    _Bool _launching;
    _Bool _instrumentBrowserAtLaunch;
    _Bool _songLoadingFinished;
    _Bool _songMustBeClosedAlertOpen;
    _Bool _iCloudSongWasClosedOnSleep;
    UIImageView *_fakeOpenSongContentView;
    UIImageView *_fakeOpenSongNavBarView;
    _Bool _newSongIsSpecialContentSong;
    NSString *_audioInPortOnSuspend;
    NSString *_audioOutPortOnSuspend;
    UIView *_contentView;
    UIView *_navigationBarView;
    UIImageView *_navigationBarAmbientView;
    UIView *_dummyNavigationBarView;
    UIButton *_mySongsButton;
    UIButton *_instrumentsButton;
    UIButton *_homeButton;
    UIButton *_settingsButton;
    MAUISlider *_masterVolumeSlider;
    MAUILEDLevelMeterView *_masterVolumeLevelMeterL;
    MAUILEDLevelMeterView *_masterVolumeLevelMeterR;
    UIView *_transportControlsGroupView;
    UIView *_masterVolumeGroupView;
    UIImageView *_specialContentSongCreationFullScrenshotView;
    UIAlertController *_showSwitchOnInputMonitoringAlert;
    UIButton *_backTestsButton;
    NSString *_previousOutputPort;
}

+ (id)createProgressViewControllerIndeterminate:(_Bool)arg1 canCancel:(_Bool)arg2;
@property(retain, nonatomic) NSString *previousOutputPort; // @synthesize previousOutputPort=_previousOutputPort;
@property(retain, nonatomic) UIButton *backTestsButton; // @synthesize backTestsButton=_backTestsButton;
@property(retain, nonatomic) UIAlertController *showSwitchOnInputMonitoringAlert; // @synthesize showSwitchOnInputMonitoringAlert=_showSwitchOnInputMonitoringAlert;
@property(retain, nonatomic) UIImageView *specialContentSongCreationFullScrenshotView; // @synthesize specialContentSongCreationFullScrenshotView=_specialContentSongCreationFullScrenshotView;
@property(readonly, nonatomic) _Bool songLoadingFinished; // @synthesize songLoadingFinished=_songLoadingFinished;
@property(retain, nonatomic) UIView *masterVolumeGroupView; // @synthesize masterVolumeGroupView=_masterVolumeGroupView;
@property(retain, nonatomic) UIView *transportControlsGroupView; // @synthesize transportControlsGroupView=_transportControlsGroupView;
@property(retain, nonatomic) MAUILEDLevelMeterView *masterVolumeLevelMeterR; // @synthesize masterVolumeLevelMeterR=_masterVolumeLevelMeterR;
@property(retain, nonatomic) MAUILEDLevelMeterView *masterVolumeLevelMeterL; // @synthesize masterVolumeLevelMeterL=_masterVolumeLevelMeterL;
@property(retain, nonatomic) MAUISlider *masterVolumeSlider; // @synthesize masterVolumeSlider=_masterVolumeSlider;
@property(retain, nonatomic) UIButton *settingsButton; // @synthesize settingsButton=_settingsButton;
@property(retain, nonatomic) UIButton *homeButton; // @synthesize homeButton=_homeButton;
@property(retain, nonatomic) UIButton *instrumentsButton; // @synthesize instrumentsButton=_instrumentsButton;
@property(retain, nonatomic) UIButton *mySongsButton; // @synthesize mySongsButton=_mySongsButton;
@property(retain, nonatomic) UIView *dummyNavigationBarView; // @synthesize dummyNavigationBarView=_dummyNavigationBarView;
@property(readonly, nonatomic) CbSongMainViewController *songMainViewController; // @synthesize songMainViewController=_songMainViewController;
@property(retain, nonatomic) UIImageView *navigationBarAmbientView; // @synthesize navigationBarAmbientView=_navigationBarAmbientView;
@property(retain, nonatomic) UIView *navigationBarView; // @synthesize navigationBarView=_navigationBarView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (id)childViewControllerForScreenEdgesDeferringSystemGestures;
- (unsigned long long)preferredScreenEdgesDeferringSystemGestures;
- (void)_executeQuickActionAccordingToPrefs;
- (void)doAppQuickActionAcordingToPrefs;
- (void)updateCbQuickActionItems;
- (_Bool)showSwitchOnInputMonitoringAlertIfNeeded;
- (_Bool)showAudioOutputRouteAlertIfNeeded;
- (void)_audioDriverWillChange:(id)arg1;
- (void)showTooLowDiskForRecordingAlert;
- (void)_handleTooLowDiskForRecording:(id)arg1;
- (void)_handleAppStartScreenClosed:(id)arg1;
- (void)showAppleLoopCouldNotBeLoadedAlert;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (_Bool)canBecomeFirstResponder;
- (id)undoManager;
- (void)removeLoadingProgress;
- (void)showLoadingProgressAndForceFlushTransaction;
- (void)showLoadingProgress;
- (void)createLoadingProgressForSong:(id)arg1;
- (void)removeSpecialContentSongCreationFullScrenshotViewIfNeeded;
- (void)initialSongViewBlendDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)startInstrumentBrowserTransition:(id)arg1 showDummyNavigationBar:(_Bool)arg2 overwriteDefaultStartView:(id)arg3 overwriteDefaultSongScreenShotImage:(id)arg4 useCSTCacheScreenshot:(_Bool)arg5;
- (void)transitionViewDidFinish:(id)arg1;
- (void)removeSBTransitionViewAnimated:(_Bool)arg1;
- (void)removeIBTransitionView;
- (void)removeOpenSongTransitionViewHelperAnimated:(_Bool)arg1 includeSongBrowser:(_Bool)arg2;
- (void)_initDummySongNavigationBar;
- (void)_reopenSleepingiCloudSongIfPossible:(id)arg1;
- (void)cancelPendingSleepingCloudSongReopeningIfNeeded;
- (void)_reopenSleepingOrResolvediCloudSongAtURL:(id)arg1;
- (_Bool)quickSaveSongIfNecessaryWithoutScreenShotIfOpen:(_Bool)arg1;
- (_Bool)_saveAndCloseCurrentSongImmediately:(_Bool)arg1 closeSongOnlyIfSaveSucceeded:(_Bool)arg2 appIsSuspending:(_Bool)arg3 outNavBarScreenshot:(id *)arg4 outSongScreenshot:(id *)arg5 error:(id *)arg6;
- (_Bool)saveCurrentSongImmediatelyWithError:(id *)arg1;
- (void)removeSongMainController;
- (void)createSongMainViewControllerWithSong:(id)arg1 isNew:(_Bool)arg2;
- (void)cancelSongSavingErrorAlertIfOpen:(_Bool)arg1;
- (void)_createNewSongWithInputMethodOrGridInfoDict:(id)arg1;
- (void)takeScreenshotsBig:(id *)arg1 small:(id *)arg2;
- (void)openSong:(id)arg1 zoomFromRect:(struct CGRect)arg2;
- (void)openSong:(id)arg1;
- (void)requestSongBrowserOpenSong:(id)arg1 zoomFromRect:(struct CGRect)arg2;
- (void)showDocBrowserLocationsExplanationDialogIfNecessary;
- (void)showDocBrowserMigrationInfoDialogIfNecessary;
- (void)newDocumentCreationFailedBeforeEvenStartingToCreateSong;
- (void)_songCollectionManager:(id)arg1 operation:(int)arg2 failedWithError:(id)arg3 showAlertIfNeeded:(_Bool)arg4;
- (void)songCollectionManager:(id)arg1 operation:(int)arg2 failedWithError:(id)arg3;
- (_Bool)songCollectionManager:(id)arg1 operation:(int)arg2 progress:(float)arg3;
- (void)songCollectionManager:(id)arg1 operationComplete:(int)arg2 userInfo:(id)arg3;
- (void)_songBrowserDidShowAndAllowMigrationAlert:(_Bool)arg1;
- (void)songBrowserFadeOutDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)removeSongBrowser;
- (_Bool)isSongBrowserExisting;
- (void)_showSongBrowserWithDocumentURL:(id)arg1 alpha:(double)arg2 allowMigrationAlert:(_Bool)arg3;
- (void)_fadeInSongBrowserWithDocumentURL:(id)arg1 allowAlreadyExisting:(_Bool)arg2 allowMigrationAlert:(_Bool)arg3;
- (void)_fadeInSongBrowserWithDocumentURL:(id)arg1;
- (_Bool)songSavingErrorAlertIsOpen;
- (void)closeCurrentOpenSongAndShowSongBrowser;
- (void)_stopAllPlaybackForSavingOrClosingSong:(_Bool)arg1;
- (void)_closeSongAndSongUIAndOpenSongBrowser:(id)arg1;
- (void)blendInSongBrowser:(_Bool)arg1 deleteOpenSong:(_Bool)arg2;
- (void)loadAndAddSongBrowserForAppStart;
- (void)_addSongBrowserToHierarchyWithAlpha:(double)arg1;
- (void)instrumentBrowserDidShow:(id)arg1;
- (void)instrumentBrowserCancelled:(id)arg1 actionButton:(id)arg2;
- (void)instrumentBrowser:(id)arg1 finishedWithSelectedIMKey:(id)arg2 selectedSecondLevelItemKey:(id)arg3 additionalSelectedItemInfo:(id)arg4;
- (void)showInstrumentBrowserWithCancelButton:(_Bool)arg1 animated:(_Bool)arg2;
- (void)refreshRetailStoreVersion;
- (void)_setInstrumentBrowserToolBarButtonHidden:(id)arg1;
- (_Bool)createFakeStoreVersion;
- (void)checkDemoSongSetting;
- (void)viewDidLayoutSubviews;
- (void)removeFakeOpenSongViewsAnimated:(_Bool)arg1;
- (void)showFakeOpenSongViewsWithNavbarImage:(id)arg1 songImage:(id)arg2;
- (void)moveNavBarAndContentViewByY:(double)arg1 animationDuration:(double)arg2;
- (void)replaceNavigationBar:(id)arg1 wantsAmbientGradient:(_Bool)arg2;
- (void)removeNavigationBar:(id)arg1;
- (void)addNavigationBar:(id)arg1 wantsAmbientGradient:(_Bool)arg2;
- (void)showDummySongNavigationBar;
- (void)clearNavigationBar;
- (void)setNavigationBarAmbientColor:(id)arg1 duration:(double)arg2;
- (void)_moveNavAmbientViewToNavigationBarAndSetBgColor:(id)arg1;
- (void)appWillBeSuspended;
- (void)appIsClosing;
- (void)appDidBecomeActive:(_Bool)arg1;
- (void)_showSongMustBeClosedAlertAndCloseSong;
- (void)_appWillCloseOrSuspend:(_Bool)arg1;
- (void)writeCurrentViewStateToPrefs;
- (void)appDidEnterSuspendedEventsOnlyMode;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)shouldAutorotate;
- (void)showStartupScreen;
- (void)startMainContainerViewController;
- (void)_showAppropriateBrowser;
- (void)showAppropriateBrowser;
- (void)dealloc;
- (void)viewDidUnload;
- (void)cleanUp;
- (void)didReceiveMemoryWarning;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

