//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CbMusicImportViewController.h"

#import "CbMediaImportContentSourceProtocol-Protocol.h"
#import "CbMusicImportMainController-Protocol.h"

@class AVPlayer, CbMediaImportController, NSString, NSURL;

@interface CbMusicImportRootViewController : CbMusicImportViewController <CbMediaImportContentSourceProtocol, CbMusicImportMainController>
{
    CbMediaImportController *_mediaImportController;
    AVPlayer *_avPlayer;
    NSURL *_currentPlayingURL;
    float _volume;
    int _totalItems;
}

- (void).cxx_destruct;
- (_Bool)runningInMgoContext;
- (id)mediaImportController;
- (void)stopPlaying;
- (void)playOrStopItem:(id)arg1;
@property(readonly, nonatomic) AVPlayer *avPlayer;
- (void)doModalSheetModeDirectImportForPoint:(struct CGPoint)arg1;
- (_Bool)directImportButtonsEnabled;
- (_Bool)isNormalModalSheetMode;
- (double)volume;
- (void)setVolume:(double)arg1;
- (void)setAvPlayerVolume:(float)arg1;
- (id)currentlyPlayingURL;
- (void)showCollection:(id)arg1 ofQuery:(id)arg2;
- (void)showCollection:(id)arg1 ofQuery:(id)arg2 animated:(_Bool)arg3;
- (void)showOrJumpOverArtist:(id)arg1 collection:(id)arg2 animated:(_Bool)arg3 title:(id)arg4;
- (void)showAllSelectedForQuery:(id)arg1;
- (id)view;
- (id)segmentedControlPlaceholderString;
- (long long)currentItemsCount;
- (void)updateTitleForMediaImporter;
- (void)updateItemCountLabel;
- (void)_updateItemCountLabel:(_Bool)arg1;
- (int)itemsCount;
- (void)controllerDidMinimize:(_Bool)arg1;
- (void)controllerWillMinimize:(_Bool)arg1;
- (void)controllerWillBeHiddenInMediaController;
- (void)controllerWillBeShownInMediaController;
- (void)buildControllers;
- (void)saveScrollPositionForPoint:(struct CGPoint)arg1;
- (void)handleTableEntryLongPressedAction:(id)arg1;
- (void)stopPrelisteningImmediately;
- (void)stopPrelistening;
- (id)dragFileInfoForTableViewPoint:(struct CGPoint)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)pushPlaylistControllerAnimated:(_Bool)arg1 forQuery:(id)arg2;
- (id)pushGenreListControllerAnimated:(_Bool)arg1 forQuery:(id)arg2;
- (id)pushArtistListControllerAnimated:(_Bool)arg1 forQuery:(id)arg2;
- (id)pushAlbumListControllerAnimated:(_Bool)arg1 forQuery:(id)arg2;
- (id)pushSongListControllerAnimated:(_Bool)arg1 forQuery:(id)arg2;
- (void)setControllerInfos;
- (void)cancel;
- (void)setMainController:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)dealloc;
- (void)clearMediaImportControllerRef;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithMediaImporterController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

