//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ECSingleton.h"

@class CbNotificationBannerView, NSMutableArray, NSString, UIColor, UIFont, UIImage, UIView;

@interface CbNotificationBanner : ECSingleton
{
    double displayTime;
    double animationTime;
    unsigned long long animationOptions;
    int animation;
    NSString *message;
    UIFont *font;
    UIFont *headerFont;
    struct CGRect headerFrame;
    UIImage *backgroundImage;
    struct CGRect bannerFrame;
    struct CGRect messageFrame;
    struct CGRect messageClippingBounds;
    _Bool useCustomLayerLayout;
    UIImage *iconImage;
    struct CGRect iconImageFrame;
    UIColor *backgroundColor;
    UIColor *borderColor;
    NSMutableArray *bannerMsgQueue;
    CbNotificationBannerView *_bannerView;
    _Bool assetsLoaded;
    UIView *_bannerMainView;
    id _delegate;
}

+ (id)sharedNotificationBanner;
+ (id)singleton;
+ (void)setSingleton:(id)arg1;
@property __weak id delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor;
@property(nonatomic) _Bool useCustomLayerLayout; // @synthesize useCustomLayerLayout;
@property(nonatomic) int animation; // @synthesize animation;
@property(nonatomic) unsigned long long animationOptions; // @synthesize animationOptions;
@property(nonatomic) struct CGRect messageClippingBounds; // @synthesize messageClippingBounds;
@property(nonatomic) struct CGRect messageFrame; // @synthesize messageFrame;
@property(nonatomic) struct CGRect bannerFrame; // @synthesize bannerFrame;
@property(nonatomic) double animationTime; // @synthesize animationTime;
@property(nonatomic) double displayTime; // @synthesize displayTime;
@property(nonatomic) struct CGRect iconImageFrame; // @synthesize iconImageFrame;
@property(retain, nonatomic) UIImage *iconImage; // @synthesize iconImage;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage;
@property(nonatomic) struct CGRect headerFrame; // @synthesize headerFrame;
@property(retain, nonatomic) UIFont *headerFont; // @synthesize headerFont;
@property(retain, nonatomic) UIFont *font; // @synthesize font;
@property(retain, nonatomic) NSString *message; // @synthesize message;
- (void).cxx_destruct;
- (void)clearMessageQueue;
- (void)showBannerWithMessage:(id)arg1 showImmediately:(_Bool)arg2;
- (void)showBannerWithMessage:(id)arg1;
- (void)showBanner;
- (void)dequeueMessages;
- (void)dequeueMessagesAndImmediately:(_Bool)arg1;
- (void)removeBanner;
@property(readonly, nonatomic) UIView *bannerMainView;
- (struct CGRect)slideFrame;
- (void)_expandBanner;
- (void)releaseResources;
- (void)setAssetSet:(id)arg1;
- (void)_applicationDidChangeOrientation:(id)arg1;
- (void)_applicationWillEnterForeground:(id)arg1;
- (void)_applicationDidEnterBackground:(id)arg1;
- (void)dealloc;
- (id)init;

@end

