//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, NSURL, NSUndoManager;

@interface CbNSDocumentReplacement : NSObject
{
    NSURL *_fileURL;
    NSString *_fileType;
    NSUndoManager *_undoManager;
    long long _dirtyCounter;
}

+ (void)setCbUndoManagerClass:(Class)arg1;
+ (Class)cbUndoManagerClass;
@property(retain, nonatomic) NSString *fileType; // @synthesize fileType=_fileType;
@property(retain, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
@property(nonatomic) long long _dirtyCounter; // @synthesize _dirtyCounter;
- (void).cxx_destruct;
- (void)saveDocument:(id)arg1;
- (_Bool)saveDocumentWithError:(id *)arg1;
- (_Bool)saveToURL:(id)arg1 ofType:(id)arg2 forSaveOperation:(unsigned long long)arg3 error:(id *)arg4;
- (_Bool)writeToURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (_Bool)readFromData:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (void)_handleUndoManagerNotifications:(id)arg1;
- (_Bool)_recoveringUndoStackFromLogic;
- (void)_setDirtyCounterAndPostNotificationIfChanged:(long long)arg1;
- (void)_decDirtyCounter;
- (void)_incDirtyCounter;
- (_Bool)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (id)dataOfType:(id)arg1 error:(id *)arg2;
- (void)close;
- (id)undoManager;
- (id)displayName;
- (id)initWithContentsOfURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3 allowOlderSongVersionOpeningWithProblems:(_Bool)arg4;
- (void)setAllowOpeningOlderSongVersionsWithProblems:(_Bool)arg1;
- (id)initWithContentsOfURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (_Bool)_initWithContentsOfURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;

@end

