//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class CbSIIMFretboardStringModel;

@interface CbPitchBendEvent : NSObject
{
    int _pitchBendValue;
    int _channel;
    unsigned char _mb3;
    CbSIIMFretboardStringModel *_stringModel;
}

@property(retain, nonatomic) CbSIIMFretboardStringModel *stringModel; // @synthesize stringModel=_stringModel;
@property(nonatomic) unsigned char mb3; // @synthesize mb3=_mb3;
@property(nonatomic) int channel; // @synthesize channel=_channel;
@property(nonatomic) int pitchBendValue; // @synthesize pitchBendValue=_pitchBendValue;
- (void).cxx_destruct;
- (id)initWithPitchBend:(int)arg1 channel:(int)arg2 mb3:(unsigned char)arg3 stringModel:(id)arg4;

@end

