//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class DfDocument, EcTimer, MAUIScrollView, NSArray, NSMutableArray, UIColor, UIImage, UIImageView, UIPanGestureRecognizer;
@protocol CbRegionCutterViewDelegate;

@interface CbRegionCutterView : UIView
{
    UIView *_topLineView;
    UIView *_bottomLineView;
    UIImageView *_cutterView;
    UIImage *_normalImage;
    UIImage *_highlightedImage;
    UIColor *_lineShadowColor;
    UIColor *_lineColor;
    UIColor *_highlightedLineColor;
    double _internalXOffset;
    double _leftAndRightTouchZoneInset;
    NSMutableArray *_slaveRegionTrackViews;
    NSMutableArray *_slaveRegionLayers;
    NSMutableArray *_slaveLineViews;
    UIView *_rulerSlaveLineView;
    MAUIScrollView *_scrollView;
    struct CGPoint _startScrollContentOffset;
    UIPanGestureRecognizer *_panRecognizer;
    _Bool _isZoomMode;
    long long _currentClock;
    _Bool _recognizerBegan;
    EcTimer *_longClickTimer;
    _Bool _externalZoomAnimationRunning;
    NSArray *_connectedRegions;
    double _xOffset;
    DfDocument *_document;
    id _target;
    SEL _action;
    id <CbRegionCutterViewDelegate> _delegate;
}

+ (id)addRegionCutterViewForRegionLayer:(id)arg1 toTracksView:(id)arg2 ctrl:(id)arg3 allTrackControllers:(id)arg4 rulerView:(id)arg5 atPositionInTrack:(double)arg6 target:(id)arg7 action:(SEL)arg8 delegate:(id)arg9;
@property(nonatomic) __weak id <CbRegionCutterViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool externalZoomAnimationRunning; // @synthesize externalZoomAnimationRunning=_externalZoomAnimationRunning;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(nonatomic) __weak DfDocument *document; // @synthesize document=_document;
@property(nonatomic) double xOffset; // @synthesize xOffset=_xOffset;
@property(retain, nonatomic) NSArray *connectedRegions; // @synthesize connectedRegions=_connectedRegions;
- (void).cxx_destruct;
- (void)updateCurrentPositionForNewXOffset:(double)arg1;
- (void)_longPressAction:(id)arg1;
- (void)_handleScrollViewDidScrollNotification:(id)arg1;
- (void)didMoveToSuperview;
- (void)addSlaveRegionInfoWithRegionLayer:(id)arg1 trackView:(id)arg2;
- (void)setCurrentPositionWithClock:(long long)arg1;
- (void)updateInternalClock;
- (long long)currentClock;
- (double)currentPosition;
- (void)_panAction:(id)arg1;
- (void)_panAction:(id)arg1 isAutoScroll:(_Bool)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)_endTouchMode:(_Bool)arg1;
- (void)_removeSlaveLineViews;
- (_Bool)highlighted;
- (void)setHighlighted:(_Bool)arg1;
- (void)_updateCutterSubviews;
- (void)removeFromSuperview;
- (void)createAndAddRulerSlaveLineView:(id)arg1;
- (void)createAndAddSlaveLineViews;
- (void)_updateSlaveLinePositionsAndHiddenState;
- (void)bringSlaveRegionLineViewsToFront;
- (void)_makeAndAddRegionSlaveLineWithSlaveIndex:(long long)arg1;
- (id)_makeLineViewWithXPos:(double)arg1 yPos:(double)arg2 height:(double)arg3;
- (void)_updateLineColors;
- (void)setAssetSet:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

