//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet, NSString;
@protocol CbScaleInstrumentProtocol;

@interface CbScaleController : NSObject <UITableViewDelegate, UITableViewDataSource>
{
    int keyMode;
    NSMutableDictionary *scales;
    NSMutableArray *scaleArray;
    NSMutableSet *usedScales;
    NSMutableDictionary *lastDescriptors;
    id <CbScaleInstrumentProtocol> _currentInstrument;
}

+ (id)sharedController;
@property(nonatomic) __weak id <CbScaleInstrumentProtocol> currentInstrument; // @synthesize currentInstrument=_currentInstrument;
@property(readonly, copy, nonatomic) NSMutableDictionary *scales; // @synthesize scales;
- (void).cxx_destruct;
- (id)minorPentatonicString;
- (id)majorString;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)_delayedScaleDescriptorChange:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)_fontSize;
- (id)scaleDescriptorAtIndexPath:(id)arg1;
- (id)selectedBackgroundViewForCell:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)selectCurrentDescriptorInTableView:(id)arg1;
- (id)_indexPathForCurrentScale;
- (void)keyChanged;
- (void)scaleDescriptorChanged:(id)arg1;
- (id)lastDescriptor;
- (void)resetUsedScaleDescriptors;
- (void)removeUsedScaleDescriptor:(id)arg1;
- (void)addUsedScaleDescriptor:(id)arg1;
- (id)scaleDescriptorForPreferencesKey:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)loadScales;
- (id)currentKeyScaleDescriptor;
- (id)defaultScale;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

