//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary;

@interface CbSCRequest : NSObject
{
    id _request;
    NSDictionary *_userInfo;
}

+ (id)performMethod:(int)arg1 onResource:(id)arg2 usingParameters:(id)arg3 userInfo:(id)arg4 withAccount:(id)arg5 sendingProgressHandler:(CDUnknownBlockType)arg6 responseHandler:(CDUnknownBlockType)arg7;
@property(retain, nonatomic) id request; // @synthesize request=_request;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
- (void).cxx_destruct;

@end

