//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@class CbSongMainViewController, DfDocument, UISegmentedControl, UIViewController;

@interface CbSettingsSheetController : UINavigationController
{
    DfDocument *_document;
    CbSongMainViewController *_songMainViewController;
    UISegmentedControl *_segmentedControl;
    UIViewController *_currentContentController;
    UIViewController *_currentContentNavigationController;
    long long _currentContentIndex;
}

+ (void)showModalSettingsSheetInViewController:(id)arg1 forDocument:(id)arg2 mainViewController:(id)arg3;
+ (_Bool)isSheetMode;
+ (void)addCloseButtonItemToViewController:(id)arg1 action:(SEL)arg2;
+ (void)addDefaultPhoneCloseButtonItemToViewController:(id)arg1;
- (void).cxx_destruct;
- (void)_closeButtonPressed:(id)arg1;
- (void)close;
- (void)closeAnimated:(_Bool)arg1 showHelpOnCompletion:(_Bool)arg2;
- (void)closeAnimated:(_Bool)arg1;
- (void)openModalForParentController:(id)arg1;
- (void)segmentedControlValueChangedAction:(id)arg1;
- (void)_loadContentViewWithIndex:(long long)arg1;
- (void)_closeCurrentContentController:(_Bool)arg1;
- (void)_songUIWillCloseHandler:(id)arg1;
- (void)phoneGlobalSettingsDoneButtonAction:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidUnload;
- (void)viewDidLoad;
@property(readonly, nonatomic) UISegmentedControl *segmentedControl;
- (void)dealloc;
- (id)initWithDocument:(id)arg1 songMainViewController:(id)arg2;

@end

