//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CbSIIMFretboardController.h"

#import "CbSmartStringsBowingDelegate-Protocol.h"

@class CbSIIMSmartStringsFretboardView, CbSmartStringsBallisticsModel, CbSmartStringsIMViewController, CbSmartStringsInteraction, NSArray, NSMutableSet, NSString;
@protocol CbSmartStringsDatasourceProtocol, CbSmartStringsMb3Datasource;

@interface CbSmartStringsFretboardController : CbSIIMFretboardController <CbSmartStringsBowingDelegate>
{
    CbSmartStringsInteraction *_currentInteraction;
    CbSmartStringsBallisticsModel *_ballisticsModel;
    NSArray *_tuningsArray;
    unsigned long long _numInstruments;
    unsigned long long _activeInstrumentIndex;
    long long _bowingMode;
    _Bool _bowing;
    int _bowedNote;
    NSMutableSet *_delayedPitchBendResets;
    _Bool _mustResetIntensity;
    id <CbSmartStringsDatasourceProtocol> _dataSource;
}

@property __weak id <CbSmartStringsDatasourceProtocol> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) long long bowingMode; // @synthesize bowingMode=_bowingMode;
@property(nonatomic) unsigned long long numInstruments; // @synthesize numInstruments=_numInstruments;
@property(nonatomic) unsigned long long activeInstrumentIndex; // @synthesize activeInstrumentIndex=_activeInstrumentIndex;
@property(retain, nonatomic) NSArray *tuningsArray; // @synthesize tuningsArray=_tuningsArray;
- (void).cxx_destruct;
- (void)stopAllStrings;
- (void)updateInteraction:(id)arg1 withRecognizer:(id)arg2;
- (int)currentVelocity;
- (void)_applyIntensity:(int)arg1;
- (void)updateInstantaneousVelocity:(float)arg1;
- (void)resetIntensity;
- (void)setNeedsIntensityReset;
- (void)_handleBallisticsUpdate:(id)arg1;
- (void)handleSingleSelectorUpdate:(id)arg1;
- (void)sendNoteOff:(int)arg1 toInstrumentID:(int)arg2 mb3:(unsigned char)arg3 toChannel:(int)arg4;
- (void)sendNoteOn:(int)arg1 toInstrumentID:(int)arg2 withVelocity:(unsigned char)arg3 mb3:(unsigned char)arg4 toChannel:(int)arg5;
- (void)stopBowedNotes:(_Bool)arg1;
- (void)startBowedNotesForGesture:(int)arg1 forRecognizer:(id)arg2;
- (void)_performPitchBendResetIfNeededForChannel:(int)arg1;
- (void)flushAllDelayedPitchBends;
- (void)resetPitchbendForStringModel:(id)arg1 mb3:(unsigned char)arg2;
- (void)touchNeckStringAtIndex:(long long)arg1 atFretIndex:(long long)arg2 forTouch:(id)arg3 touchesMoved:(_Bool)arg4 withGesture:(int)arg5;
- (void)dealloc;
- (id)init;
@property(retain) CbSIIMSmartStringsFretboardView *fretboardView; // @dynamic fretboardView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property __weak CbSmartStringsIMViewController<CbSmartStringsMb3Datasource> *rigController; // @dynamic rigController;
@property(readonly) Class superclass;

@end

