//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "CbSettingRootViewControllerDelegate-Protocol.h"

@class CbSettingsSheetController, CbSongMainViewController, DfDocument, NSString;

@interface CbSongSettingsViewController : UITableViewController <CbSettingRootViewControllerDelegate>
{
    long long _settingsTempoRow;
    long long _settingsKeyRow;
    long long _settingsTimeSignatureRow;
    long long _settingsEditCordsRow;
    long long _settingsTimeSnapRow;
    long long _settingsTempoKeyTimeSectionRows;
    DfDocument *_document;
    CbSongMainViewController *_mainViewController;
    CbSettingsSheetController *_settingsSheetController;
    _Bool _allowToCacheVisibleScrollRect;
}

+ (void)dismissSettingsPopover;
+ (_Bool)isOpen;
+ (void)initialize;
@property(nonatomic) CbSettingsSheetController *settingsSheetController; // @synthesize settingsSheetController=_settingsSheetController;
@property(nonatomic) CbSongMainViewController *mainViewController; // @synthesize mainViewController=_mainViewController;
@property(nonatomic) DfDocument *document; // @synthesize document=_document;
- (void)dynamicTypeChangedHandler:(id)arg1;
- (void)_sessionManagerPeerDidChangeHandler:(id)arg1;
- (void)_sessionManagerSongSettingsChangeHandler:(id)arg1;
- (struct CGSize)sizeForPopover;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)updateChineseInstrumentsVisibility:(id)arg1;
- (void)fadeOutSwitchAction:(id)arg1;
- (void)metronomeSwitchAction:(id)arg1;
- (void)showEditChordsAction:(id)arg1;
- (_Bool)shouldShowEditChordsEntry;
- (void)showHelpAction:(id)arg1;
- (void)_closeSheetAndOpenGlobalHelpDeferred:(_Bool)arg1;
- (void)phoneGlobalSettingsDoneButtonAction:(id)arg1;
- (void)doneButtonAction:(id)arg1;
- (_Bool)canControlSongArchitecture;
- (_Bool)adjustableDuringPlayOrRecord;
- (_Bool)adjustableDuringRecord;
- (id)disabledCellTextColor;
- (id)activeCellDetailedTextColor;
- (id)activeCellTextColor;
- (_Bool)shouldShowDoneButtonForSubMenuViewController:(id)arg1;
- (_Bool)shouldShowJamSessionRow;
- (_Bool)shouldShowMetronomeRow;
- (unsigned long long)supportedInterfaceOrientations;
- (void)dealloc;
- (void)viewDidUnload;
- (void)cleanup;
- (void)viewDidLoad;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

