//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSMutableArray, NSMutableDictionary, NSString;
@protocol CbStepSequencerLibraryModelDelegate;

@interface CbStepSequencerLibraryModel : NSObject
{
    id <CbStepSequencerLibraryModelDelegate> _delegate;
    NSMutableArray *_allTrackItems;
    NSMutableArray *_trackItems;
    NSMutableArray *_templateItems;
    NSMutableDictionary *_UUIDToItem;
    unsigned long long _displayContext;
    NSString *_selectedUUID;
    NSString *_previewingUUID;
}

+ (id)libraryDataForTrackSettings:(id)arg1 customPatterns:(id)arg2;
+ (id)customPatterns:(id)arg1;
+ (id)trackSettings:(id)arg1;
+ (id)defaultTrackSettings;
+ (id)newPatternUUID;
@property(copy, nonatomic) NSString *previewingUUID; // @synthesize previewingUUID=_previewingUUID;
@property(copy, nonatomic) NSString *selectedUUID; // @synthesize selectedUUID=_selectedUUID;
@property(nonatomic) unsigned long long displayContext; // @synthesize displayContext=_displayContext;
- (void).cxx_destruct;
- (void)addNewPatternItem;
- (id)uniqueItemName;
- (void)addItems:(id)arg1;
- (_Bool)hasUserData;
- (_Bool)hasPatternWithName:(id)arg1;
- (_Bool)shouldHideTrackPatterns;
- (id)uniqueItemName:(id)arg1;
- (id)previewItem;
- (id)indexPathForSelectedItem;
- (id)selectedItem;
- (id)indexPathForItem:(id)arg1;
- (id)itemForIndexPath:(id)arg1;
- (unsigned long long)numberOfItems;
- (void)removeItem:(id)arg1;
- (void)insertItem:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addItem:(id)arg1;
- (void)updateTrackItems;
- (void)setTemplateItems:(id)arg1;
@property(copy, nonatomic) NSDictionary *libraryData;
- (id)initWithDelegate:(id)arg1;

@end

