//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class CbStepSequenceRowModel, CbStepSequenceRowModelRandomizer, CbStepSequenceRowView, CbStepSequencerNoteModel, UITouch, UIView;

@protocol CbStepSequenceRowControllerDelegate
- (CDStruct_e28e794b)timeSignature;
- (UIView *)stepValuePopoverView;
- (unsigned long long)stepsPerRow;
- (void)removeActiveStepsForPageMenu;
- (void)updateActiveStepsForPageMenu;
- (void)collapseRowHeader;
- (void)expandRowHeader;
- (_Bool)rowHeaderExpanded;
- (void)rowShouldCollapse;
- (_Bool)hasExpandedRow;
- (void)rowShouldExpandForTouch:(UITouch *)arg1 rowView:(CbStepSequenceRowView *)arg2 fill:(double)arg3;
- (void)setTouchMode:(unsigned long long)arg1 forTouch:(UITouch *)arg2;
- (unsigned long long)sequencerTouchMode:(UITouch *)arg1;
- (void)setStepToggleMode:(unsigned long long)arg1 forTouch:(UITouch *)arg2;
- (unsigned long long)stepToggleModeForTouch:(UITouch *)arg1;
- (void)previewNoteForNoteModel:(CbStepSequencerNoteModel *)arg1;
- (void)showMenuForRowModel:(CbStepSequenceRowModel *)arg1 sourceView:(UIView *)arg2;
- (void)didUpdateRowModel:(CbStepSequenceRowModel *)arg1;
- (struct _NSRange)stepViewRange;
- (CbStepSequenceRowModelRandomizer *)randomizer;
@end

