//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class CbStepSequenceRowController, NSDictionary, UITouch;

@interface CbStepSequencerTouchProperties : NSObject
{
    UITouch *_touch;
    CbStepSequenceRowController *_rowController;
    unsigned long long _touchMode;
    unsigned long long _stepToggleMode;
    NSDictionary *_sequenceDataMemento;
    double _lastTouchTime;
    struct CGPoint _autoZoomContentOffsetMemento;
}

@property(nonatomic) struct CGPoint autoZoomContentOffsetMemento; // @synthesize autoZoomContentOffsetMemento=_autoZoomContentOffsetMemento;
@property(nonatomic) double lastTouchTime; // @synthesize lastTouchTime=_lastTouchTime;
@property(retain, nonatomic) NSDictionary *sequenceDataMemento; // @synthesize sequenceDataMemento=_sequenceDataMemento;
@property(nonatomic) unsigned long long stepToggleMode; // @synthesize stepToggleMode=_stepToggleMode;
@property(nonatomic) unsigned long long touchMode; // @synthesize touchMode=_touchMode;
@property(retain, nonatomic) CbStepSequenceRowController *rowController; // @synthesize rowController=_rowController;
@property(readonly, nonatomic) UITouch *touch; // @synthesize touch=_touch;
- (void).cxx_destruct;
- (id)initWithTouch:(id)arg1;

@end

