//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "AVAudioPlayerDelegate-Protocol.h"
#import "CbURLSessionControllerDelegate-Protocol.h"

@class AVAudioPlayer, CbStoreFrontDownloadProgress, MAUIColoredBackgroundButton, MWFeedItem, NSString, UILabel, UIScrollView, UIView;

@interface CbStoreDetailViewController : UIViewController <AVAudioPlayerDelegate, CbURLSessionControllerDelegate>
{
    MWFeedItem *_feedItem;
    _Bool _showBrowser;
    _Bool _downloadStarted;
    AVAudioPlayer *_avPlayer;
    MAUIColoredBackgroundButton *_getBtn;
    MAUIColoredBackgroundButton *_previewBtn;
    MAUIColoredBackgroundButton *_deleteBtn;
    UILabel *_downloadedLbl;
    CbStoreFrontDownloadProgress *_progressView;
    _Bool _pendingDeleteAfterSongClose;
    UIScrollView *_scrollView;
    UIView *_buttonView;
    UILabel *_titleLbl;
    UILabel *_descriptionLbl;
}

+ (struct CGSize)storeDetailPopoverSize;
@property(retain, nonatomic) UILabel *downloadedLbl; // @synthesize downloadedLbl=_downloadedLbl;
@property(retain, nonatomic) UILabel *descriptionLbl; // @synthesize descriptionLbl=_descriptionLbl;
@property(retain, nonatomic) UILabel *titleLbl; // @synthesize titleLbl=_titleLbl;
@property(retain, nonatomic) UIView *buttonView; // @synthesize buttonView=_buttonView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (_Bool)isWifiAvailable;
- (_Bool)isInternetReachable;
- (int)currentReachabilityStatus;
- (void)installationCompletedAtPath:(id)arg1;
- (void)downloadCompletedAtPath:(id)arg1;
- (void)currentDownloadProgress:(id)arg1;
- (void)audioPlayerDecodeErrorDidOccur:(id)arg1 error:(id)arg2;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (_Bool)packIsInstalled;
- (void)checkButtons;
- (void)createLayout;
- (float)featuredPackTitleOriginYAdjustment;
- (id)featuredPackSubTitleFont;
- (id)featuredPackTitleFont;
- (id)infoContentString;
- (int)contentPackSizeInMB;
- (id)pauseIcon;
- (id)playIcon;
- (id)roundedCornerButtonWithTitle:(id)arg1 redTitle:(_Bool)arg2 icon:(id)arg3;
- (double)secondaryContentWidth;
- (double)mainContentWidth;
- (id)contentLabelBeneathView:(id)arg1 withString:(id)arg2 secondRow:(_Bool)arg3;
- (id)headerLabelBeneathView:(id)arg1 secondRow:(_Bool)arg2;
- (id)deviderLineBeneathWith:(id)arg1 secondRow:(_Bool)arg2;
- (float)bannerImageHeight;
- (void)downloadBannerIcon;
- (void)updateBannerIcon:(id)arg1;
- (void)setupNavBar;
- (void)deleteContentPack;
- (void)handleSongBrowserDidAppear:(id)arg1;
- (_Bool)isPackUsedInOpenSong;
- (id)contentPackBundleName;
- (void)deleteBtnPressed:(id)arg1;
- (void)getBtnPressed:(id)arg1;
- (void)showNotConnectedToTheInternetAlert;
- (void)pauseDownload;
- (void)startDownload;
- (void)previewBtnPressed:(id)arg1;
- (void)initPreviewPlayer;
- (void)checkStatus:(id)arg1;
- (id)feedItem;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithFeedItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

