//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSDictionary, NSMutableDictionary;

@interface CbStepSequencePropertyNode : NSObject
{
    NSDictionary *_defaultProperties;
    NSMutableDictionary *_properties;
    NSArray *_clockPerStepThresholds;
    NSDictionary *_thresholdToClockPerStep;
    NSArray *_noteRepeatThresholds;
    NSDictionary *_thresholdToNoteRepeats;
    NSArray *_nextStepModeThresholds;
    NSDictionary *_thresholdToNextStepMode;
    float _swing;
    CbStepSequencePropertyNode *_parentNode;
}

+ (id)thresholdToNoteRepeats;
+ (unsigned long long)noteRepeatsForFill:(double)arg1;
+ (unsigned long long)playbackSpeedForClock:(long long)arg1;
+ (long long)clockForPlaybackSpeed:(unsigned long long)arg1;
+ (CDStruct_e28e794b)defaultTimeSignature;
+ (id)textForSequenceLength:(unsigned long long)arg1;
+ (id)textForPlaybackSpeed:(unsigned long long)arg1;
+ (id)textForPlaybackMode:(unsigned long long)arg1;
+ (long long)numberOfLinesForEditMode:(unsigned long long)arg1 lineBreaks:(_Bool)arg2;
+ (id)nameForEditMode:(unsigned long long)arg1 lineBreaks:(_Bool)arg2;
+ (id)nameForEditModeRandomization:(unsigned long long)arg1;
+ (unsigned long long)defaultVelocity;
+ (unsigned long long)maxVelocity;
+ (unsigned long long)maxModulation;
+ (unsigned long long)maxProbability;
+ (id)propertyNodeKey;
+ (id)nodeWithParent:(id)arg1;
@property(nonatomic) __weak CbStepSequencePropertyNode *parentNode; // @synthesize parentNode=_parentNode;
@property(nonatomic) float swing; // @synthesize swing=_swing;
- (void).cxx_destruct;
- (id)popoverValueForEditMode:(unsigned long long)arg1;
- (float)normalizedValueForModulation;
- (void)updateModulationWithMaxValue:(float)arg1 value:(float)arg2 outValue:(float *)arg3 didUpdateValue:(_Bool *)arg4;
- (float)normalizedValueForProbability;
- (void)updateProbabilityWithMaxValue:(float)arg1 value:(float)arg2 outValue:(float *)arg3 didUpdateValue:(_Bool *)arg4;
- (float)normalizedValueForNextStepMode;
- (void)updateNextStepModeWithMaxValue:(float)arg1 value:(float)arg2 outValue:(float *)arg3 didUpdateValue:(_Bool *)arg4;
- (float)normalizedValueWithMax:(float)arg1 value:(float)arg2;
- (float)normalizedValueForNoteRepeats;
- (void)updateNoteRepeatsWithMaxValue:(float)arg1 value:(float)arg2 outValue:(float *)arg3 didUpdateValue:(_Bool *)arg4;
- (float)normalizedValueForClockPerStep;
- (void)updateClockPerStepWithMaxValue:(float)arg1 value:(float)arg2 outValue:(float *)arg3 didUpdateValue:(_Bool *)arg4;
- (float)normalizedValueForNoteLength;
- (void)updateNoteLengthWithMaxValue:(float)arg1 value:(float)arg2 outValue:(float *)arg3 didUpdateValue:(_Bool *)arg4;
- (float)normalizedValueForPitchbend;
- (void)updatePitchbendWithMaxValue:(float)arg1 value:(float)arg2 outValue:(float *)arg3 didUpdateValue:(_Bool *)arg4;
- (float)normalizedValueForVelocity;
- (void)updateVelocityWithMaxValue:(float)arg1 value:(float)arg2 outValue:(float *)arg3 didUpdateValue:(_Bool *)arg4;
- (double)fillForEditMode:(unsigned long long)arg1;
- (id)textForPlaybackMode;
- (id)textForPlaybackSpeed;
- (_Bool)hasClockPerStep;
- (_Bool)hasNextStepMode;
- (_Bool)hasModulation;
- (_Bool)hasPitchbend;
- (_Bool)hasVelocity;
- (_Bool)isEmpty;
- (void)resetModulation;
- (void)resetProbability;
- (void)resetNextStepMode;
- (void)resetNoteRepeats;
- (void)resetNoteLength;
- (void)resetVelocity;
- (void)resetClockPerStep;
- (void)resetPitchbend;
- (void)reset;
@property(nonatomic) long long clockPerStep;
@property(nonatomic) unsigned long long modulation;
@property(nonatomic) unsigned long long probability;
@property(nonatomic) unsigned long long nextStepMode;
@property(nonatomic) unsigned long long noteRepeats;
@property(nonatomic) float noteLength;
@property(nonatomic) unsigned long long velocity;
@property(nonatomic) float pitchbend;
@property(retain, nonatomic) NSDictionary *nodeData;
- (id)init;

@end

