//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class CbStepSequencePropertyNode, NSDictionary;

@interface CbStepSequenceStepModel : NSObject
{
    _Bool _enabled;
    CbStepSequencePropertyNode *_propertyNode;
    unsigned long long _stepIndex;
}

@property(readonly, nonatomic) unsigned long long stepIndex; // @synthesize stepIndex=_stepIndex;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(readonly, nonatomic) CbStepSequencePropertyNode *propertyNode; // @synthesize propertyNode=_propertyNode;
- (void).cxx_destruct;
- (_Bool)isEmpty;
@property(retain, nonatomic) NSDictionary *stepData;
- (id)initWithParentNode:(id)arg1 stepIndex:(unsigned long long)arg2;

@end

