//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer, UIImageView;

@interface CbStepSequenceNextStepBadgeView : UIView
{
    UIImageView *_imageView;
    CAShapeLayer *_backgroundLayer;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setNextStepMode:(unsigned long long)arg1;
- (void)setIcon:(unsigned long long)arg1;
- (id)initWithIcon:(unsigned long long)arg1;

@end

