//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class APDCoachingTipsManager, CbSongMainViewController, CbTrackPanelViewController, DfDocument, DfTrack, MAUIPanSlider, NSMutableDictionary, UIButton, UITableViewCell;

@interface CbTrackInspectorViewController : UITableViewController
{
    long long _sectionIndexTrackSettings;
    long long _sectionIndexPlugins;
    long long _sectionIndexMasterEffects;
    long long _sectionIndexOutput;
    long long _numberOfSections;
    long long _numberOfRowsTrackSettingsSection;
    long long _numberOfRowsPluginsSection;
    long long _numberOfRowsMasterEffectsSection;
    long long _numberOfRowsOuputSection;
    long long _rowIndexTrackSettingsSubmenu;
    long long _rowIndexPluginsSubmenu;
    long long _rowIndexVisualEQ;
    long long _rowIndexPluginsStandardSlider;
    long long _rowIndexPluginsMasterTrackSlider;
    long long _rowIndexMasterEffectSubmenu;
    long long _rowIndexMasterEffectSliders;
    long long _rowIndexOutputTitle;
    long long _rowIndexOutputSliders;
    DfTrack *_track;
    DfDocument *_document;
    CbSongMainViewController *_songMainViewController;
    CbTrackPanelViewController *_trackPanelViewController;
    MAUIPanSlider *_volumeSlider;
    MAUIPanSlider *_panSlider;
    MAUIPanSlider *_echoSlider;
    MAUIPanSlider *_reverbSlider;
    MAUIPanSlider *_trebleSlider;
    MAUIPanSlider *_bassSlider;
    MAUIPanSlider *_masterTrebleSlider;
    MAUIPanSlider *_masterBassSlider;
    MAUIPanSlider *_compressorSlider;
    UITableViewCell *_masterEffectsSectionSlidersCell;
    UITableViewCell *_pluginSectionSlidersCell;
    UITableViewCell *_pluginSectionMasterSlidersCell;
    UITableViewCell *_outputSectionSlidersCell;
    UIButton *_muteButton;
    UIButton *_soloButton;
    APDCoachingTipsManager *_apdCoachingTipsManager;
    NSMutableDictionary *_internalStateDictionary;
}

@property(retain, nonatomic) NSMutableDictionary *internalStateDictionary; // @synthesize internalStateDictionary=_internalStateDictionary;
@property(retain, nonatomic) APDCoachingTipsManager *apdCoachingTipsManager; // @synthesize apdCoachingTipsManager=_apdCoachingTipsManager;
@property(retain, nonatomic) UIButton *soloButton; // @synthesize soloButton=_soloButton;
@property(retain, nonatomic) UIButton *muteButton; // @synthesize muteButton=_muteButton;
@property(retain, nonatomic) UITableViewCell *outputSectionSlidersCell; // @synthesize outputSectionSlidersCell=_outputSectionSlidersCell;
@property(retain, nonatomic) UITableViewCell *pluginSectionMasterSlidersCell; // @synthesize pluginSectionMasterSlidersCell=_pluginSectionMasterSlidersCell;
@property(retain, nonatomic) UITableViewCell *pluginSectionSlidersCell; // @synthesize pluginSectionSlidersCell=_pluginSectionSlidersCell;
@property(retain, nonatomic) UITableViewCell *masterEffectsSectionSlidersCell; // @synthesize masterEffectsSectionSlidersCell=_masterEffectsSectionSlidersCell;
@property(retain, nonatomic) MAUIPanSlider *compressorSlider; // @synthesize compressorSlider=_compressorSlider;
@property(retain, nonatomic) MAUIPanSlider *masterBassSlider; // @synthesize masterBassSlider=_masterBassSlider;
@property(retain, nonatomic) MAUIPanSlider *masterTrebleSlider; // @synthesize masterTrebleSlider=_masterTrebleSlider;
@property(retain, nonatomic) MAUIPanSlider *bassSlider; // @synthesize bassSlider=_bassSlider;
@property(retain, nonatomic) MAUIPanSlider *trebleSlider; // @synthesize trebleSlider=_trebleSlider;
@property(retain, nonatomic) MAUIPanSlider *reverbSlider; // @synthesize reverbSlider=_reverbSlider;
@property(retain, nonatomic) MAUIPanSlider *echoSlider; // @synthesize echoSlider=_echoSlider;
@property(retain, nonatomic) MAUIPanSlider *panSlider; // @synthesize panSlider=_panSlider;
@property(retain, nonatomic) MAUIPanSlider *volumeSlider; // @synthesize volumeSlider=_volumeSlider;
@property(nonatomic) CbTrackPanelViewController *trackPanelViewController; // @synthesize trackPanelViewController=_trackPanelViewController;
@property(nonatomic) CbSongMainViewController *songMainViewController; // @synthesize songMainViewController=_songMainViewController;
@property(nonatomic) DfDocument *document; // @synthesize document=_document;
@property(nonatomic) DfTrack *track; // @synthesize track=_track;
- (void).cxx_destruct;
- (void)restoreTrackInspectorInternalState:(id)arg1;
- (id)currentTrackInspectorInternalState;
- (void)_handleAutomationChanged:(id)arg1;
- (void)_handleTrackPropertyChange:(id)arg1;
- (void)_parameterDidChangeHandler:(id)arg1;
- (void)arrangeVsGridVisibilityChangedAnimated:(_Bool)arg1;
- (void)touchInstrumentVisibilyChangedAnimated:(_Bool)arg1;
- (void)setCompressorValue:(float)arg1;
- (float)compressorValue;
- (void)setBassValue:(float)arg1;
- (long long)bassValue;
- (void)setTrebleValue:(long long)arg1;
- (long long)trebleValue;
- (void)bypassEQIfNeeded;
- (void)updateName;
- (void)updateIsOn;
- (void)updateMute;
- (void)updateSolo;
- (void)updateCompressor;
- (void)updateBass;
- (void)updateTreble;
- (void)updateReverb;
- (void)updateEcho;
- (void)updatePan;
- (void)updateVolume;
- (void)updateControls;
- (void)showPluginUIAction:(id)arg1;
- (void)bypassMasterEQAction:(id)arg1;
- (void)compressorSliderAction:(id)arg1;
- (void)bassSliderAction:(id)arg1;
- (void)trebleSliderAction:(id)arg1;
- (void)reverbSliderAction:(id)arg1;
- (void)reverbSliderDoubleTapAction:(id)arg1;
- (void)echoSliderAction:(id)arg1;
- (void)soloButtonAction:(id)arg1;
- (void)muteButtonAction:(id)arg1;
- (void)panSliderAction:(id)arg1;
- (void)volumeSliderAction:(id)arg1;
- (struct CGSize)sizeForPopover;
- (double)widthForTrackPanel;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)updateForTrack:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)configureOutlets;
- (void)configureCoachingTips;
- (void)viewDidLoad;

@end

