//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAUIScrollView.h"

@class NSArray, UIPanGestureRecognizer, UITapGestureRecognizer, UITouch;

@interface CbTronScrollView : MAUIScrollView
{
    UITouch *_lastReceivedPanDelayerTouch;
    UITouch *_lastReceivedScrollPanTouch;
    UITouch *_lastScrollBlockedTouch;
    _Bool _blockScroll;
    _Bool _lockHorizontalScrolling;
    _Bool _lockVerticalScrolling;
    NSArray *_ignoreScrollingViews;
    CDUnknownBlockType _willScrollTest;
    CDUnknownBlockType _shouldScrollTest;
    CDUnknownBlockType _didScrollTest;
    CDUnknownBlockType _tapResponder;
    NSArray *_tapResponderIgnoredClasses;
    UIPanGestureRecognizer *_scrollPanDelayerGestureRecognizer;
    UITapGestureRecognizer *_tapGestureRecognizer;
}

@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) UIPanGestureRecognizer *scrollPanDelayerGestureRecognizer; // @synthesize scrollPanDelayerGestureRecognizer=_scrollPanDelayerGestureRecognizer;
@property(retain, nonatomic) NSArray *tapResponderIgnoredClasses; // @synthesize tapResponderIgnoredClasses=_tapResponderIgnoredClasses;
@property(copy, nonatomic) CDUnknownBlockType tapResponder; // @synthesize tapResponder=_tapResponder;
@property(nonatomic) _Bool lockVerticalScrolling; // @synthesize lockVerticalScrolling=_lockVerticalScrolling;
@property(nonatomic) _Bool lockHorizontalScrolling; // @synthesize lockHorizontalScrolling=_lockHorizontalScrolling;
@property(nonatomic) _Bool blockScroll; // @synthesize blockScroll=_blockScroll;
@property(copy, nonatomic) CDUnknownBlockType didScrollTest; // @synthesize didScrollTest=_didScrollTest;
@property(copy, nonatomic) CDUnknownBlockType shouldScrollTest; // @synthesize shouldScrollTest=_shouldScrollTest;
@property(copy, nonatomic) CDUnknownBlockType willScrollTest; // @synthesize willScrollTest=_willScrollTest;
@property(copy, nonatomic) NSArray *ignoreScrollingViews; // @synthesize ignoreScrollingViews=_ignoreScrollingViews;
- (void).cxx_destruct;
- (void)resetScrollingLocks;
- (void)handlePinch:(id)arg1;
- (void)setContentOffset:(struct CGPoint)arg1;
- (void)setContentOffset:(struct CGPoint)arg1 animated:(_Bool)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)_performTapResponderBlock:(id)arg1;
- (void)respondToTapUsingBlock:(CDUnknownBlockType)arg1 ignoringClasses:(id)arg2;
- (void)_handlePanAction:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

