//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CbButtonSwitch.h"

@interface CbVerticalButtonSwitch : CbButtonSwitch
{
}

- (void)setAssetSet:(id)arg1;
- (void)updatePositionAnimated:(_Bool)arg1;
- (void)updateForPoint:(struct CGPoint)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

