//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSMutableDictionary;

@interface CGenGFMatrix : NSObject <NSCoding>
{
    NSMutableDictionary *rowDict;
}

- (void).cxx_destruct;
- (id)description;
- (id)csvString;
- (id)sortedRowDictKeys;
- (id)normalizedCSVStringFromString:(id)arg1;
- (_Bool)valueForRow:(id)arg1 col:(id)arg2 outValue:(float *)arg3;
- (_Bool)parseCSVString:(id)arg1;
- (_Bool)parseCSVFileAtPath:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

