//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CGenGFPort.h"

@interface CGenGFPortNumeric : CGenGFPort
{
    double _value;
    double _min;
    double _max;
    void *_unused3[4];
}

+ (Class)baseClass;
- (void)setMaxDoubleValue:(double)arg1;
- (void)setMinDoubleValue:(double)arg1;
- (double)maxDoubleValue;
- (double)minDoubleValue;
- (void)setDoubleValue:(double)arg1;
- (double)doubleValue;
- (_Bool)setStateValue:(id)arg1;
- (id)stateValue;
- (_Bool)takeValue:(id)arg1 fromPort:(id)arg2;
- (Class)valueClass;
- (_Bool)acceptValuesOfClass:(Class)arg1;
- (_Bool)setValue:(id)arg1;
- (id)value;
- (id)initWithNode:(id)arg1 arguments:(id)arg2;

@end

