//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSMutableArray, NSMutableDictionary;

@interface CGenGFStringBins : NSObject <NSCoding>
{
    NSMutableArray *stringBins;
    NSMutableDictionary *stringToBinMap;
    NSMutableArray *binNames;
    _Bool stringsAreRegularExpression;
    NSMutableDictionary *regexDict;
}

@property(nonatomic) _Bool stringsAreRegularExpression; // @synthesize stringsAreRegularExpression;
- (void).cxx_destruct;
- (id)nameForBinAtIndex:(unsigned long long)arg1;
- (_Bool)setName:(id)arg1 forBinAtIndex:(unsigned long long)arg2;
- (_Bool)renameString:(id)arg1 toString:(id)arg2;
- (_Bool)removeStringsInBinAtIndex:(unsigned long long)arg1;
- (_Bool)removeString:(id)arg1;
- (_Bool)addString:(id)arg1 toBinAtIndex:(unsigned long long)arg2;
- (id)stringsInBinAtIndex:(unsigned long long)arg1;
- (unsigned long long)indexOfBinForString:(id)arg1;
- (unsigned long long)binCount;
- (_Bool)removeLastBin;
- (_Bool)appendBin;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;
- (unsigned long long)normalIndexOfBinForString:(id)arg1;
- (void)createDefaultBinNamesForNumberOfBins:(unsigned long long)arg1;
- (unsigned long long)regexIndexOfBinForString:(id)arg1;
- (void)updateRegexDict;

@end

