//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CGenGFComplexityMatrix.h"

@interface CGenGFComplexityMatrixImmutable : CGenGFComplexityMatrix
{
    _Bool _canBeMutated;
}

@property _Bool canBeMutated; // @synthesize canBeMutated=_canBeMutated;
- (_Bool)importCSV:(id)arg1 forFamily:(id)arg2;
- (_Bool)importFromFolder:(id)arg1;

@end

