//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DBLocalEndpoint.h"

@class DBLocalEndpointListenerThread;

@interface DBLocalEndpointIP : DBLocalEndpoint
{
    struct __CFSocket *_socket;
    struct __CFSocket *_socketv6;
    struct __CFData *_addressData;
    struct __CFData *_readData;
    struct __CFMessagePort *_messagePort;
    struct __CFRunLoopSource *_socketSource;
    struct __CFRunLoopSource *_socketv6Source;
    _Bool _hasSocketSendBufferSpace;
    _Bool _hasSocketv6SendBufferSpace;
    int _socketPort;
    DBLocalEndpointListenerThread *_listenerThread;
}

@property(readonly, nonatomic) _Bool hasSocketv6SendBufferSpace; // @synthesize hasSocketv6SendBufferSpace=_hasSocketv6SendBufferSpace;
@property(readonly, nonatomic) _Bool hasSocketSendBufferSpace; // @synthesize hasSocketSendBufferSpace=_hasSocketSendBufferSpace;
@property(readonly, nonatomic) struct __CFSocket *socketv6; // @synthesize socketv6=_socketv6;
@property(readonly, nonatomic) struct __CFSocket *socket; // @synthesize socket=_socket;
@property(readonly, nonatomic) int socketPort; // @synthesize socketPort=_socketPort;
@property(retain, nonatomic) DBLocalEndpointListenerThread *listenerThread; // @synthesize listenerThread=_listenerThread;
- (void).cxx_destruct;
- (int)sendLoopbackMessage:(struct __CFData *)arg1;
- (int)sendSocketMessage:(struct __CFData *)arg1 address:(struct __CFData *)arg2;
- (id)selfPeer;
- (void)sendLoopback:(id)arg1;
- (_Bool)setupSockets;
- (_Bool)setupMessagePort;
- (void)dealloc;
- (id)initWithName:(id)arg1;
- (id)init;

@end

