//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@protocol DfEventContainer
- (void)deselectAllEventsOfType:(unsigned long long)arg1 andControllerNumber:(CDStruct_5115be14)arg2;
- (void)selectAllEventsOfType:(unsigned long long)arg1 andControllerNumber:(CDStruct_5115be14)arg2;
- (_Bool)hasEventsOfType:(unsigned long long)arg1 andControllerNumber:(CDStruct_5115be14)arg2;
- (unsigned long long)countEventsOfType:(unsigned long long)arg1 andControllerNumber:(CDStruct_5115be14)arg2;
- (_Bool)hasSelectedEventsOfType:(unsigned long long)arg1 andControllerNumber:(CDStruct_5115be14)arg2;
- (unsigned long long)countSelectedEventsOfType:(unsigned long long)arg1 andControllerNumber:(CDStruct_5115be14)arg2;
- (void)deselectAllEventsOfType:(unsigned long long)arg1;
- (void)selectAllEventsOfType:(unsigned long long)arg1;
- (_Bool)hasEventsOfType:(unsigned long long)arg1;
- (unsigned long long)countEventsOfType:(unsigned long long)arg1;
- (_Bool)hasSelectedEventsOfType:(unsigned long long)arg1;
- (unsigned long long)countSelectedEventsOfType:(unsigned long long)arg1;
- (void)deselectAllEvents;
- (void)selectAllEvents;
- (_Bool)hasEvents;
- (unsigned long long)countEvents;
- (_Bool)hasSelectedEvents;
- (unsigned long long)countSelectedEvents;
@end

