//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, NSString;

@interface FileInZipInfo : NSObject
{
    unsigned long long _length;
    int _level;
    _Bool _crypted;
    unsigned long long _size;
    NSDate *_date;
    unsigned long long _crc32;
    NSString *_name;
}

@property(readonly, nonatomic) unsigned long long crc32; // @synthesize crc32=_crc32;
@property(readonly, nonatomic) NSDate *date; // @synthesize date=_date;
@property(readonly, nonatomic) unsigned long long size; // @synthesize size=_size;
@property(readonly, nonatomic) _Bool crypted; // @synthesize crypted=_crypted;
@property(readonly, nonatomic) int level; // @synthesize level=_level;
@property(readonly, nonatomic) unsigned long long length; // @synthesize length=_length;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void)dealloc;
- (id)initWithName:(id)arg1 length:(unsigned long long)arg2 level:(int)arg3 crypted:(_Bool)arg4 size:(unsigned long long)arg5 date:(id)arg6 crc32:(unsigned long long)arg7;

@end

