//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GAmpDesignerChessboardBasicViewController.h"

#import "GAmpDesignerChessboardBasicViewControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class GAmpDesignerChessboard_iPhone_PlayViewController, GPlugInCocoaViewController, NSString, UITapGestureRecognizer;

@interface GAmpDesignerChessboard_iPhone_ViewController : GAmpDesignerChessboardBasicViewController <UIGestureRecognizerDelegate, GAmpDesignerChessboardBasicViewControllerDelegate>
{
    UITapGestureRecognizer *_doubleTapGestureRecognizer;
    GPlugInCocoaViewController *_editViewController;
    GAmpDesignerChessboard_iPhone_PlayViewController *_playViewController;
}

+ (id)editorInfos;
@property(retain, nonatomic) GAmpDesignerChessboard_iPhone_PlayViewController *playViewController; // @synthesize playViewController=_playViewController;
@property(retain, nonatomic) GPlugInCocoaViewController *editViewController; // @synthesize editViewController=_editViewController;
@property(retain, nonatomic) UITapGestureRecognizer *doubleTapGestureRecognizer; // @synthesize doubleTapGestureRecognizer=_doubleTapGestureRecognizer;
- (void)layoutAmpView:(id)arg1;
- (_Bool)isRecording;
- (void)setNavBarAmbientParamEditModeColor:(id)arg1;
- (void)setNavBarAmbientColor:(id)arg1;
- (void)setParamEditMode:(_Bool)arg1;
- (_Bool)isParamEditMode;
- (struct MADSPUserPlugIn *)guitarAmpPlugIn;
- (unsigned long long)currentAmpType;
- (void)willMakeScreenShotHideLocalizations:(_Bool)arg1;
- (void)handleDoubleTapGesture:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setView:(id)arg1;
- (void)channelWillLoadChannelStrip;
- (void)paramEditModeWillChange:(_Bool)arg1 animated:(_Bool)arg2;
@property(readonly) GPlugInCocoaViewController *currentViewController;
- (void)didReceiveMemoryWarning;
- (void)disconnectFromPlugIn;
- (_Bool)connectWithPlugIn:(struct MADSPUserPlugIn *)arg1 communicationChannel:(int)arg2;
- (void)onViewDidLoad;
- (void)dealloc;
- (id)initWithPlugIn:(struct MADSPUserPlugIn *)arg1 editorID:(id)arg2 communicationChannel:(int)arg3 userData:(void *)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

