//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GAutoSync.h"

#import "GMessageToCocoaBridgeUser-Protocol.h"

@interface GAutoSync_GControl : GAutoSync <GMessageToCocoaBridgeUser>
{
    struct GControl *_control;
    struct GMessageToCocoaBridge *_messageListener;
    _Bool _inverse;
}

+ (id)autoSyncWithViewController:(id)arg1 control:(struct GControl *)arg2;
+ (_Bool)acceptsControl:(id)arg1;
@property(nonatomic) _Bool inverse; // @synthesize inverse=_inverse;
@property(nonatomic) struct GMessageToCocoaBridge *messageListener; // @synthesize messageListener=_messageListener;
@property(nonatomic) struct GControl *control; // @synthesize control=_control;
- (void)parameterValueChanged:(long long)arg1 newValue:(void *)arg2;
- (void)parameterStateChanged:(long long)arg1 newState:(void *)arg2;
- (void)parameterInfoChanged:(long long)arg1 newInfo:(void *)arg2;
- (id)parameterIDs;
- (long long)parameterIDForValueKey:(int)arg1;
- (void)onGMessage:(const struct GMessage *)arg1;
- (void)listenToGSender:(struct GSender *)arg1;
- (id)initWithViewController:(id)arg1 control:(struct GControl *)arg2;
- (_Bool)hasControl:(id)arg1;
- (void)disconnectControl;
- (void)dealloc;

@end

