//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GAutoSync.h"

#import "MAVeValueClient-Protocol.h"

@class MAVeElementBase, MAVeUIViewAdapter, NSString;

@interface GAutoSync_MAVeElementBase : GAutoSync <MAVeValueClient>
{
    _Bool _controlSnapsToIntegerValues;
    struct MAVeUIViewAdapter *_viewAdapter;
}

+ (_Bool)acceptsControl:(id)arg1;
+ (id)autoSyncWithViewController:(id)arg1 control:(id)arg2 syncInfo:(id)arg3;
@property(retain) MAVeUIViewAdapter *viewAdapter; // @synthesize viewAdapter=_viewAdapter;
@property(readonly) MAVeElementBase *veElementBase;
- (void)parameterMenuItemsChanged:(long long)arg1 newMenuItems:(void *)arg2;
- (void)parameterValueChanged:(long long)arg1 newValue:(void *)arg2;
- (void)parameterStateChanged:(long long)arg1 newState:(void *)arg2;
- (void)parameterInfoChanged:(long long)arg1 newInfo:(void *)arg2;
- (long long)parameterIDForValueID:(id)arg1;
- (id)valuesFromSyncInfo:(id)arg1;
- (id)parameterIDs;
- (void)initQuickHelpSupport;
- (id)initWithViewController:(id)arg1 control:(id)arg2 syncInfo:(id)arg3;
- (_Bool)controlHandlesMenuItems;
- (_Bool)hasParameterID:(long long)arg1;
- (_Bool)hasControl:(id)arg1;
- (void)disconnectControl;
- (void)dealloc;
- (void)controlValueChanged:(id)arg1;
- (void)valueFinishedChange:(id)arg1;
- (void)stringValueDidChange:(id)arg1;
- (void)valueDidChange:(id)arg1;
- (void)valueWillChange:(id)arg1;
@property _Bool controlSnapsToIntegerValues; // @synthesize controlSnapsToIntegerValues=_controlSnapsToIntegerValues;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

