//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIActivity.h>

#import "CbCheckSongOpenAlertDelegate-Protocol.h"

@class NSString, NSURL;

@interface GbSharingActivity : UIActivity <CbCheckSongOpenAlertDelegate>
{
    NSURL *_songPathURL;
}

+ (long long)activityCategory;
- (void).cxx_destruct;
- (void)checkSongOpenAlertDidFinishWithButtonIndex:(long long)arg1 alertInfo:(id)arg2 alertTag:(long long)arg3;
- (void)performActivityForService:(int)arg1;
- (void)_reallyPerformActivityForService:(int)arg1;
- (_Bool)canPerformWithActivityItems:(id)arg1;
- (void)startSharingExporterWithService:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

