//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPlugInCocoaViewController.h"

#import "GConcretePlugInViewController-Protocol.h"

@class MAVeEqUILinearSliderView, MAVeGraphCtrlChannelEQ, MAVeGrid, MAVeUIButtonView, MAVeUIGraphCtrlChannelEQView, MAVeUIGridView, MAVeUILabelView, MAVeUIPopupButtonView, MAVeUIScrubberView, NSMutableArray;

@interface GChannelEQBackgammonViewController : GPlugInCocoaViewController <GConcretePlugInViewController>
{
    MAVeGraphCtrlChannelEQ *_veGraphControl;
    MAVeUIGraphCtrlChannelEQView *_graphControlView;
    MAVeUIGridView *_gridView;
    MAVeUIButtonView *_analyzerButton;
    MAVeUIButtonView *_prePostButton;
    MAVeUIButtonView *_qCoupleButton;
    MAVeUIPopupButtonView *_processingPopupButton;
    MAVeUILabelView *_processingLabel;
    MAVeUILabelView *_gainLabel;
    MAVeEqUILinearSliderView *_gainSlider;
    MAVeUIScrubberView *_gainReadout;
    MAVeUIButtonView *_onOffButtonLC;
    MAVeUIButtonView *_onOffButtonLS;
    MAVeUIButtonView *_onOffButtonP1;
    MAVeUIButtonView *_onOffButtonP2;
    MAVeUIButtonView *_onOffButtonP3;
    MAVeUIButtonView *_onOffButtonP4;
    MAVeUIButtonView *_onOffButtonHS;
    MAVeUIButtonView *_onOffButtonHC;
    MAVeUILabelView *_gridLeftPlusLabel;
    MAVeUILabelView *_gridLeftMinusLabel;
    MAVeUILabelView *_gridRightPlusLabel;
    MAVeUILabelView *_gridRightMinusLabel;
    NSMutableArray *_veLabelMatrixViews;
    NSMutableArray *_veButtonHighlightViews;
}

+ (id)editorInfos;
@property(retain, nonatomic) NSMutableArray *veButtonHighlightViews; // @synthesize veButtonHighlightViews=_veButtonHighlightViews;
@property(retain, nonatomic) NSMutableArray *veLabelMatrixViews; // @synthesize veLabelMatrixViews=_veLabelMatrixViews;
@property(nonatomic) MAVeUILabelView *gridRightMinusLabel; // @synthesize gridRightMinusLabel=_gridRightMinusLabel;
@property(nonatomic) MAVeUILabelView *gridRightPlusLabel; // @synthesize gridRightPlusLabel=_gridRightPlusLabel;
@property(nonatomic) MAVeUILabelView *gridLeftMinusLabel; // @synthesize gridLeftMinusLabel=_gridLeftMinusLabel;
@property(nonatomic) MAVeUILabelView *gridLeftPlusLabel; // @synthesize gridLeftPlusLabel=_gridLeftPlusLabel;
@property(nonatomic) MAVeUIButtonView *onOffButtonHC; // @synthesize onOffButtonHC=_onOffButtonHC;
@property(nonatomic) MAVeUIButtonView *onOffButtonHS; // @synthesize onOffButtonHS=_onOffButtonHS;
@property(nonatomic) MAVeUIButtonView *onOffButtonP4; // @synthesize onOffButtonP4=_onOffButtonP4;
@property(nonatomic) MAVeUIButtonView *onOffButtonP3; // @synthesize onOffButtonP3=_onOffButtonP3;
@property(nonatomic) MAVeUIButtonView *onOffButtonP2; // @synthesize onOffButtonP2=_onOffButtonP2;
@property(nonatomic) MAVeUIButtonView *onOffButtonP1; // @synthesize onOffButtonP1=_onOffButtonP1;
@property(nonatomic) MAVeUIButtonView *onOffButtonLS; // @synthesize onOffButtonLS=_onOffButtonLS;
@property(nonatomic) MAVeUIButtonView *onOffButtonLC; // @synthesize onOffButtonLC=_onOffButtonLC;
@property(nonatomic) MAVeUIScrubberView *gainReadout; // @synthesize gainReadout=_gainReadout;
@property(nonatomic) MAVeEqUILinearSliderView *gainSlider; // @synthesize gainSlider=_gainSlider;
@property(nonatomic) MAVeUILabelView *gainLabel; // @synthesize gainLabel=_gainLabel;
@property(nonatomic) MAVeUILabelView *processingLabel; // @synthesize processingLabel=_processingLabel;
@property(nonatomic) MAVeUIPopupButtonView *processingPopupButton; // @synthesize processingPopupButton=_processingPopupButton;
@property(nonatomic) MAVeUIButtonView *qCoupleButton; // @synthesize qCoupleButton=_qCoupleButton;
@property(nonatomic) MAVeUIButtonView *prePostButton; // @synthesize prePostButton=_prePostButton;
@property(nonatomic) MAVeUIButtonView *analyzerButton; // @synthesize analyzerButton=_analyzerButton;
@property(nonatomic) MAVeUIGridView *gridView; // @synthesize gridView=_gridView;
@property(nonatomic) MAVeUIGraphCtrlChannelEQView *graphControlView; // @synthesize graphControlView=_graphControlView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateAnalyzerCurveAppearance;
- (void)setCurve:(id)arg1 forShapeWithID:(id)arg2;
- (void)setCurve:(id)arg1 forBandWithID:(id)arg2;
- (id)graphBandIDFromPlugInBandID:(long long)arg1;
- (id)bandIDFromBandIndex:(long long)arg1;
- (long long)bandIndexFromBandID:(id)arg1;
- (id)allGraphBandIDs;
- (void)onPropertyChanged:(void *)arg1 newData:(void *)arg2;
- (void)onParameterValueChanged:(long long)arg1 newValue:(void *)arg2;
@property(readonly, nonatomic) MAVeGrid *veGrid;
@property(readonly, nonatomic) MAVeGraphCtrlChannelEQ *veGraphControl; // @synthesize veGraphControl=_veGraphControl;
- (void)setVeGraphControl:(id)arg1;
@property(nonatomic) long long bandSelection;
@property(readonly, nonatomic) _Bool bypassed;
- (void)setGridSignAppearanceToBypassed:(_Bool)arg1 analyzer:(_Bool)arg2;
- (void)onOffButtonChanged:(id)arg1;
- (void)setBandAtIndex:(long long)arg1 on:(_Bool)arg2;
- (void)onBypassedChanged:(_Bool)arg1;
- (void)onBandSelectionChanged:(long long)arg1;
- (void)handleSingleTap:(id)arg1;
- (void)initVeButtonHighlightViews;
- (void)initVeLabelMatrix;
- (void)initVeGraphControl;
- (void)onFinalizeView;
- (void)onViewDidLoad;
- (id)initWithPlugIn:(struct MADSPUserPlugIn *)arg1 editorID:(id)arg2 communicationChannel:(int)arg3 nibName:(id)arg4 bundle:(id)arg5;
- (id)initWithPlugIn:(struct MADSPUserPlugIn *)arg1 editorID:(id)arg2 communicationChannel:(int)arg3 userData:(void *)arg4;
- (void)didReceiveMemoryWarning;
- (void)dealloc;

@end

