//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class GChTuning, NSMutableArray, NSString;

@interface GChLibrary : NSObject
{
    GChTuning *tuning;
    NSMutableArray *basicChords;
    NSString *libraryName;
    NSString *libraryPath;
    long long runTimeID;
    _Bool isReadOnlyLibrary;
}

- (void).cxx_destruct;
- (id)description;
- (id)libraryName;
- (void)setLibraryName:(id)arg1;
- (void)replaceChordRange2:(id)arg1 withChord:(id)arg2;
- (void)deleteChordRange:(id)arg1;
- (void)addBasicChord:(id)arg1;
- (void)deleteChordRangePriv:(id)arg1;
- (void)addChordRangePriv:(id)arg1;
- (unsigned long long)numberOfBasicChords;
- (unsigned long long)numberOfChords;
- (id)basicChords;
- (id)libraryPath;
- (_Bool)isReadOnlyLibrary;
- (void)setIsReadOnlyLibrary:(_Bool)arg1;
- (long long)runTimeID;
- (id)tuning;
- (void)dealloc;
- (id)initWithTuning:(id)arg1 libraryPath:(id)arg2;
- (void)updateLibraryFile:(id)arg1;
- (_Bool)readChordChunksFromBuffer:(char *)arg1 withLength:(unsigned long long)arg2 dbChordCount:(unsigned long long *)arg3;
- (id)wholeLibraryFileContent;
- (unsigned int)writeTuningChunkToBuffer:(char *)arg1 remLength:(int)arg2;
- (unsigned int)tuningChunkSize;

@end

