//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GenInstModelUICoordinator_CharacterDefinitionsBase.h"

@interface GenInstModelUICoordinator_CharacterDefinitions_SimpleBassPlayer : GenInstModelUICoordinator_CharacterDefinitionsBase
{
}

- (_Bool)isXYPadKey:(id)arg1;
- (void)setupKnownParameterIDs;
- (void)setupParameterToGenerateOptionsMap;
- (void)setupParameterChangeConditions;
- (void)setupParameterDependencies;
- (void)setupParameterTemplates;
- (id)initialDrumRegionParameterValues;
- (id)initialRegionParameterValuesForTrackModel:(id)arg1;

@end

