//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, NSString;
@protocol GenInstDrummer_TrackModelProtocol;

@protocol GenInstModelUICoordinatorCharacterDefinitionsProtocol <NSObject>
- (_Bool)isXYPadKey:(NSString *)arg1;
- (NSDictionary *)initialRegionParameterValuesForTrackModel:(id <GenInstDrummer_TrackModelProtocol>)arg1;
- (NSArray *)knownParameterIDs;
- (NSDictionary *)parameterGenerateOptions;
- (NSDictionary *)parameterChangeConditions;
- (NSDictionary *)parameterDependencies;
- (NSDictionary *)parameterTemplates;
- (NSDictionary *)parameters;
@end

