//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString, NSURL;

@protocol GenInstDownload <NSObject>
- (void)downloadContentForPatchWithURL:(NSURL *)arg1 groupInfo:(NSDictionary *)arg2;
- (_Bool)isContentBeingDownloadedForPatchWithURL:(NSURL *)arg1;
- (_Bool)contentWasDownloadedForPatchWithURL:(NSURL *)arg1;
- (void)downloadDefaultContentForGenreIdentifier:(NSString *)arg1 characterIdentifier:(NSString *)arg2 groupInfo:(NSDictionary *)arg3;
- (_Bool)isDefaultContentBeingDownloadedForGenreIdentifier:(NSString *)arg1 characterIdentifier:(NSString *)arg2;
- (_Bool)defaultContentWasDownloadedForGenreIdentifier:(NSString *)arg1 characterIdentifier:(NSString *)arg2;
@end

