//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class GenInstDrummerLibraryModificationDateTracker, GenInstGenreCharacterToLibraryStyleAdapter, NSURL;

@interface GenInstDrummerLibrary : NSObject
{
    struct unique_ptr<CGenGenerator, std::__1::default_delete<CGenGenerator>> _generator;
    _Bool _isLibraryValid;
    GenInstDrummerLibraryModificationDateTracker *_genInstDrummerLibraryModificationDateTracker;
    NSURL *_loadedLibraryURL;
    GenInstGenreCharacterToLibraryStyleAdapter *_libraryStyleAdapter;
}

+ (id)defaultGenreCharacterDatabase;
+ (id)genreCharacterDatabaseFromURL:(id)arg1;
+ (id)genreCharacterDatabaseFromURLCache;
+ (id)defaultGenreCharacterDatabaseURL;
+ (id)defaultLibraryURL;
+ (_Bool)isDefaultGenInstContentAvailable;
+ (_Bool)isGenreMappingPlistAvailable;
+ (_Bool)isPatchDirectoryAvailable;
+ (_Bool)isLibraryAvailable;
+ (_Bool)getPatchFolderFileRef:(struct CFileRef *)arg1;
@property(retain, nonatomic) GenInstGenreCharacterToLibraryStyleAdapter *libraryStyleAdapter; // @synthesize libraryStyleAdapter=_libraryStyleAdapter;
@property(retain, nonatomic) NSURL *loadedLibraryURL; // @synthesize loadedLibraryURL=_loadedLibraryURL;
@property(retain, nonatomic) GenInstDrummerLibraryModificationDateTracker *genInstDrummerLibraryModificationDateTracker; // @synthesize genInstDrummerLibraryModificationDateTracker=_genInstDrummerLibraryModificationDateTracker;
@property(nonatomic) _Bool isLibraryValid; // @synthesize isLibraryValid=_isLibraryValid;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)libraryStyleAdapterResultForCharacterIdentifier:(id)arg1;
- (void)purgeStylesWithCharacterIdentifiers:(id)arg1;
- (void)checkIfLibraryIsValid;
- (void)libraryDidLoad;
- (void)libraryWillLoad;
- (void)loadLibrary;
- (void)reloadLibraryIfNewerLibraryFilesAreOnDisk;
- (struct CGenGenerator *)generator;
- (void)setupModificationDateTracker;
- (void)dealloc;
- (id)init;

@end

