//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "GenInstModelProtocol-Protocol.h"

@class GenInstDrummerModel, NSString;

@interface GenInstModel : NSObject <GenInstModelProtocol>
{
    struct CSong *_song;
    GenInstDrummerModel *_genInstDrummerModel;
    _Bool _clampEventsToRegionStart;
}

- (id)library;
- (void)handleTrackTypeChangedFromGenInst:(id)arg1;
- (void)handleTrackTypeChangedToGenInst:(id)arg1;
- (void)removeNotifications;
- (void)addNotifications;
- (void)setStateFromStateVersion5:(id)arg1;
- (void)setStateFromStateVersion4:(id)arg1;
- (void)setStateFromStateVersion3:(id)arg1;
- (void)setStateFromStateVersion2:(id)arg1;
- (void)setState:(id)arg1;
- (id)state;
- (void)persistentIO:(struct TPersistentIOPrms *)arg1;
- (id)genInstDictionaryChunkForRegion:(const struct CRegion *)arg1;
- (void)registerLastSelectedGenre:(id)arg1 character:(id)arg2;
- (struct CGenDrumMapBase *)drumMapForRegion:(const struct CMSeq *)arg1;
- (_Bool)clampEventsToRegionStart;
- (void)setClampEventsToRegionStart:(_Bool)arg1;
- (void)purgeUnneededTrackModels;
- (void)cancelAllGenerateJobs;
- (_Bool)hasRunningGenerateJobs;
- (_Bool)isDefaultGenInstContentAvailable;
- (void)setUndoState:(id)arg1;
- (id)undoState;
- (void)generateEventsWithSameSeedsForSelectedRegionsInFolder:(int)arg1;
- (void)generateEventsWithNewSeedsForSelectedRegionsInFolder:(int)arg1;
- (void)prepareGenerateToSpeedUpFirstPlayOnTrack:(struct CVirtualTrack)arg1;
- (void)convertSelectedMidiRegionsToDrummerRegionsInFolder:(int)arg1;
- (void)convertSelectedDrummerRegionsToMidiRegionsInFolder:(int)arg1;
- (vector_e94a763c)allDrumTracksInSong;
- (unsigned long long)numberOfDrummerTracks;
- (_Bool)allowCreationOfAdditionalAnimalTrackForSong:(struct CSong *)arg1;
- (_Bool)drumTrackExists;
- (id)modelUICoordinator;
- (void)setAutoSelectRegions:(_Bool)arg1;
- (_Bool)autoSelectRegions;
- (id)genInstDrummerTrackModelForMSeq:(const struct CMSeq *)arg1;
- (id)genInstDrummerTrackModelForSeqID:(int)arg1;
- (id)genInstDrummerTrackModelForVirtualTrack:(struct CVirtualTrack)arg1;
- (struct CSong *)song;
- (void)detachSong;
- (void)cleanup;
- (void)dealloc;
- (id)initWithSong:(struct CSong *)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

