//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPlugInCocoaViewController.h"

#import "GConcretePlugInViewController-Protocol.h"
#import "MAVeRemixerXPad_ActionDelegate-Protocol.h"
#import "MAVeRemixerXYPad_ActionDelegate-Protocol.h"

@class MAVeButton, MAVeEmitterOverlay, MAVeGrid, MAVeRemixerUIEffectBackgroundView, MAVeRemixerUIEffectSelectorButtonView, MAVeRemixerUIXPadView, MAVeRemixerUIXYPadView, MAVeRemixerXPad, MAVeRemixerXYPad, MAVeUIActionAreaView, MAVeUIBackgroundPlateView, MAVeUIButtonView, MAVeUIEmitterOverlayView, MAVeUIGridView, MAVeUILabelView, MAVeUIMenuGridView, NSArray, NSString;

@interface GLiveRemixerViewController : GPlugInCocoaViewController <GConcretePlugInViewController, MAVeRemixerXYPad_ActionDelegate, MAVeRemixerXPad_ActionDelegate>
{
    NSArray *_xyPadEffectInfos;
    double _centerGridLineGapWidth;
    struct MAVeUIActionAreaView *_backgroundActionAreaView;
    struct MAVeUIBackgroundPlateView *_leftmostEffectRootView;
    struct MAVeRemixerUIEffectBackgroundView *_leftmostEffectBackgroundView;
    struct MAVeUIGridView *_leftmostEffectGridView;
    struct MAVeRemixerUIXYPadView *_leftmostEffectXYPadView;
    struct MAVeUIButtonView *_leftmostEffectLatchButtonView;
    struct MAVeUIMenuGridView *_leftmostEffectMenuGridView;
    struct MAVeRemixerUIEffectSelectorButtonView *_leftmostEffectSelectorButtonView;
    struct MAVeRemixerUIEffectBackgroundView *_leftEffectBackgroundView;
    struct MAVeRemixerUIXYPadView *_leftEffectYPadView;
    struct MAVeUIGridView *_leftEffectGridView;
    struct MAVeUILabelView *_leftEffectLabelView;
    struct MAVeUIButtonView *_resetButtonView;
    struct MAVeRemixerUIXPadView *_centerTopEffectXPadView;
    struct MAVeRemixerUIXPadView *_centerMiddleEffectXPadView;
    struct MAVeRemixerUIXPadView *_centerBottomEffectXPadView;
    struct MAVeRemixerUIEffectBackgroundView *_rightEffectBackgroundView;
    struct MAVeRemixerUIXYPadView *_rightEffectYPadView;
    struct MAVeUIGridView *_rightEffectGridView;
    struct MAVeUILabelView *_rightEffectLabelView;
    struct MAVeUIBackgroundPlateView *_rightmostEffectRootView;
    struct MAVeRemixerUIEffectBackgroundView *_rightmostEffectBackgroundView;
    struct MAVeUIGridView *_rightmostEffectGridView;
    struct MAVeRemixerUIXYPadView *_rightmostEffectXYPadView;
    struct MAVeUIButtonView *_rightmostEffectLatchButtonView;
    struct MAVeUIMenuGridView *_rightmostEffectMenuGridView;
    struct MAVeRemixerUIEffectSelectorButtonView *_rightmostEffectSelectorButtonView;
    struct MAVeUIEmitterOverlayView *_leftmostEffectEmitterOverlayView;
    struct MAVeUIEmitterOverlayView *_leftEffectEmitterOverlayView;
    struct MAVeUIEmitterOverlayView *_rightEffectEmitterOverlayView;
    struct MAVeUIEmitterOverlayView *_rightmostEffectEmitterOverlayView;
}

@property MAVeUIEmitterOverlayView *rightmostEffectEmitterOverlayView; // @synthesize rightmostEffectEmitterOverlayView=_rightmostEffectEmitterOverlayView;
@property MAVeUIEmitterOverlayView *rightEffectEmitterOverlayView; // @synthesize rightEffectEmitterOverlayView=_rightEffectEmitterOverlayView;
@property MAVeUIEmitterOverlayView *leftEffectEmitterOverlayView; // @synthesize leftEffectEmitterOverlayView=_leftEffectEmitterOverlayView;
@property MAVeUIEmitterOverlayView *leftmostEffectEmitterOverlayView; // @synthesize leftmostEffectEmitterOverlayView=_leftmostEffectEmitterOverlayView;
@property MAVeRemixerUIEffectSelectorButtonView *rightmostEffectSelectorButtonView; // @synthesize rightmostEffectSelectorButtonView=_rightmostEffectSelectorButtonView;
@property MAVeUIMenuGridView *rightmostEffectMenuGridView; // @synthesize rightmostEffectMenuGridView=_rightmostEffectMenuGridView;
@property MAVeUIButtonView *rightmostEffectLatchButtonView; // @synthesize rightmostEffectLatchButtonView=_rightmostEffectLatchButtonView;
@property MAVeRemixerUIXYPadView *rightmostEffectXYPadView; // @synthesize rightmostEffectXYPadView=_rightmostEffectXYPadView;
@property MAVeUIGridView *rightmostEffectGridView; // @synthesize rightmostEffectGridView=_rightmostEffectGridView;
@property MAVeRemixerUIEffectBackgroundView *rightmostEffectBackgroundView; // @synthesize rightmostEffectBackgroundView=_rightmostEffectBackgroundView;
@property MAVeUIBackgroundPlateView *rightmostEffectRootView; // @synthesize rightmostEffectRootView=_rightmostEffectRootView;
@property MAVeUILabelView *rightEffectLabelView; // @synthesize rightEffectLabelView=_rightEffectLabelView;
@property MAVeUIGridView *rightEffectGridView; // @synthesize rightEffectGridView=_rightEffectGridView;
@property MAVeRemixerUIXYPadView *rightEffectYPadView; // @synthesize rightEffectYPadView=_rightEffectYPadView;
@property MAVeRemixerUIEffectBackgroundView *rightEffectBackgroundView; // @synthesize rightEffectBackgroundView=_rightEffectBackgroundView;
@property MAVeRemixerUIXPadView *centerBottomEffectXPadView; // @synthesize centerBottomEffectXPadView=_centerBottomEffectXPadView;
@property MAVeRemixerUIXPadView *centerMiddleEffectXPadView; // @synthesize centerMiddleEffectXPadView=_centerMiddleEffectXPadView;
@property MAVeRemixerUIXPadView *centerTopEffectXPadView; // @synthesize centerTopEffectXPadView=_centerTopEffectXPadView;
@property MAVeUIButtonView *resetButtonView; // @synthesize resetButtonView=_resetButtonView;
@property MAVeUILabelView *leftEffectLabelView; // @synthesize leftEffectLabelView=_leftEffectLabelView;
@property MAVeUIGridView *leftEffectGridView; // @synthesize leftEffectGridView=_leftEffectGridView;
@property MAVeRemixerUIXYPadView *leftEffectYPadView; // @synthesize leftEffectYPadView=_leftEffectYPadView;
@property MAVeRemixerUIEffectBackgroundView *leftEffectBackgroundView; // @synthesize leftEffectBackgroundView=_leftEffectBackgroundView;
@property MAVeRemixerUIEffectSelectorButtonView *leftmostEffectSelectorButtonView; // @synthesize leftmostEffectSelectorButtonView=_leftmostEffectSelectorButtonView;
@property MAVeUIMenuGridView *leftmostEffectMenuGridView; // @synthesize leftmostEffectMenuGridView=_leftmostEffectMenuGridView;
@property MAVeUIButtonView *leftmostEffectLatchButtonView; // @synthesize leftmostEffectLatchButtonView=_leftmostEffectLatchButtonView;
@property MAVeRemixerUIXYPadView *leftmostEffectXYPadView; // @synthesize leftmostEffectXYPadView=_leftmostEffectXYPadView;
@property MAVeUIGridView *leftmostEffectGridView; // @synthesize leftmostEffectGridView=_leftmostEffectGridView;
@property MAVeRemixerUIEffectBackgroundView *leftmostEffectBackgroundView; // @synthesize leftmostEffectBackgroundView=_leftmostEffectBackgroundView;
@property MAVeUIBackgroundPlateView *leftmostEffectRootView; // @synthesize leftmostEffectRootView=_leftmostEffectRootView;
@property MAVeUIActionAreaView *backgroundActionAreaView; // @synthesize backgroundActionAreaView=_backgroundActionAreaView;
@property(nonatomic) double centerGridLineGapWidth; // @synthesize centerGridLineGapWidth=_centerGridLineGapWidth;
@property(retain, nonatomic) NSArray *xyPadEffectInfos; // @synthesize xyPadEffectInfos=_xyPadEffectInfos;
- (id)assetPathForLabelView:(struct MAVeUILabelView *)arg1 highlighted:(_Bool)arg2;
- (id)buttonAssetSetPathWithName:(id)arg1;
- (id)backgroundAssetSetPathWithName:(id)arg1;
- (void)remixerXYPadDidEndTracking:(id)arg1;
- (void)remixerXYPadContinuesTracking:(id)arg1 position:(struct CGPoint)arg2;
- (void)remixerXYPadWillStartTracking:(id)arg1;
- (void)remixerXPadWillStartTracking:(id)arg1;
- (void)rightmostEffectSelectionChanged:(id)arg1;
- (void)rightmostEffectSelectorButtonPressed:(id)arg1;
- (void)leftmostEffectSelectionChanged:(id)arg1;
- (void)leftmostEffectSelectorButtonPressed:(id)arg1;
- (void)updateResetButton:(_Bool)arg1;
- (void)updateEffectHighlight:(_Bool)arg1 background:(id)arg2 xyPad:(id)arg3 emitterOverlayView:(struct MAVeUIEmitterOverlayView *)arg4 grid:(id)arg5;
- (void)updateEffectSelection:(long long)arg1 selectionButton:(id)arg2 background:(id)arg3 xyPad:(id)arg4 grid:(id)arg5;
- (void)updateRightmostHighlight:(_Bool)arg1;
- (void)updateRightmostEffectSelection:(long long)arg1;
- (void)updateLeftmostHighlight:(_Bool)arg1;
- (void)updateLeftmostEffectSelection:(long long)arg1;
- (void)updateEffectFocus;
- (void)updateAssetSetPathOfGrid:(id)arg1 highlighted:(_Bool)arg2;
- (void)onPropertyChanged:(void *)arg1 newData:(void *)arg2;
- (void)onParameterValueChanged:(long long)arg1 newValue:(void *)arg2;
- (id)xyPadEffectInfoForSelection:(long long)arg1;
@property(nonatomic) long long effectFocus;
@property(readonly) MAVeButton *rightmostEffectLatchButton;
@property(readonly) MAVeRemixerXYPad *rightmostEffectXYPad;
@property(readonly) MAVeEmitterOverlay *rightmostEffectEmitterOverlay;
@property(readonly) MAVeGrid *rightmostEffectGrid;
@property(readonly) MAVeRemixerXYPad *rightEffectYPad;
@property(readonly) MAVeEmitterOverlay *rightEffectEmitterOverlay;
@property(readonly) MAVeGrid *rightEffectGrid;
@property(readonly) MAVeButton *leftmostEffectLatchButton;
@property(readonly) MAVeRemixerXYPad *leftmostEffectXYPad;
@property(readonly) MAVeEmitterOverlay *leftmostEffectEmitterOverlay;
@property(readonly) MAVeGrid *leftmostEffectGrid;
- (id)rightEffectBackground;
- (id)rightmostEffectBackground;
- (id)leftEffectBackground;
- (id)leftmostEffectBackground;
@property(readonly) MAVeRemixerXPad *centerBottomEffectXPad;
@property(readonly) MAVeRemixerXPad *centerMiddleEffectXPad;
@property(readonly) MAVeRemixerXPad *centerTopEffectXPad;
@property(readonly) MAVeRemixerXYPad *leftEffectYPad;
@property(readonly) MAVeEmitterOverlay *leftEffectEmitterOverlay;
@property(readonly) MAVeGrid *leftEffectGrid;
- (void)onFinalizeView;
- (void)autoSyncControls;
- (void)onViewDidLoad;
- (void)dealloc;
- (id)initWithPlugIn:(struct MADSPUserPlugIn *)arg1 editorID:(id)arg2 communicationChannel:(int)arg3 nibName:(id)arg4 bundle:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

