//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSLayoutConstraint, NSObject, NSString, UIButton, UITableView, UIView;
@protocol CbExternalGuitarPedalBoardPoolViewControllerDelegate_iPhone;

@interface GPedalBoardChessboardPool_iPhone_ViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    struct NSObject *_delegate;
    long long _selection;
    UITableView *_itemTableView;
    UIButton *_cancelButton;
    NSLayoutConstraint *_cancelButtonTrailingConstraint;
    UIView *_headerView;
}

@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) NSLayoutConstraint *cancelButtonTrailingConstraint; // @synthesize cancelButtonTrailingConstraint=_cancelButtonTrailingConstraint;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UITableView *itemTableView; // @synthesize itemTableView=_itemTableView;
@property(nonatomic) long long selection; // @synthesize selection=_selection;
@property(nonatomic) NSObject<CbExternalGuitarPedalBoardPoolViewControllerDelegate_iPhone> *delegate; // @synthesize delegate=_delegate;
- (void)cancelButtonReleased:(id)arg1;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (id)init;
- (long long)tableView:(id)arg1 indentationLevelForRowAtIndexPath:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

