//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MAPlgUIPedalBoardPool_iPad;

@interface GPedalBoardChessboardPool_iPad_ViewController : UIViewController
{
}

+ (id)viewControllerWithSize:(struct CGSize)arg1;
@property(readonly, nonatomic) MAPlgUIPedalBoardPool_iPad *pool;
- (id)initWithSize:(struct CGSize)arg1;
- (void)dealloc;

@end

