//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol LgGridModel, LgGridObserver, NSObject;

@protocol LgGridController <NSObject>
- (_Bool)createEmptyCellInGrid:(int)arg1 atLocation:(struct LgGridLocation)arg2;
- (int)createNewGridWithNumberOfColumns:(unsigned long long)arg1;
- (void)removeObserver:(id <LgGridObserver>)arg1;
- (void)addObserver:(id <LgGridObserver>)arg1;
- (void)endTransaction:(int)arg1 withMode:(int)arg2;
- (void)beginTransaction:(int)arg1 withMode:(int)arg2;
- (_Bool)isCellRecording;
- (_Bool)stopCellRecordingAndPlayClipAfterwards:(_Bool)arg1;
- (_Bool)startCellRecordingForGrid:(int)arg1 intoCellAtLocation:(struct LgGridLocation)arg2;
- (_Bool)pauseGrid:(int)arg1 type:(unsigned int)arg2 group:(id <NSObject>)arg3 completion:(void (^)(void))arg4;
- (_Bool)stopGrid:(int)arg1 type:(unsigned int)arg2 group:(id <NSObject>)arg3 completion:(void (^)(void))arg4;
- (_Bool)playGrid:(int)arg1 type:(unsigned int)arg2 group:(id <NSObject>)arg3;
- (id <LgGridModel>)modelForGrid:(int)arg1;
- (_Bool)enumerateGrids:(void (^)(id <LgGridModel>, _Bool *))arg1;
@end

