//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MAAnimation;

@protocol MAAnimationDelegates <NSObject>

@optional
- (void)maAnimationOnStopAnimation:(MAAnimation *)arg1;
- (_Bool)maAnimationOnStartAnimation:(MAAnimation *)arg1;
- (float)maAnimation:(MAAnimation *)arg1 calculateT:(float)arg2;
- (_Bool)maAnimation:(MAAnimation *)arg1 animate:(float)arg2;
@end

