//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@class MADirectoryIndexNode, NSMutableSet, NSString;

@interface MADirectoryIndex : NSObject <NSCoding>
{
    NSString *standardizedPath;
    NSMutableSet *linkedIndexPaths;
    MADirectoryIndexNode *indexRoot;
    unsigned long long numIndexedObjects;
}

+ (id)indexOfDirectoryAtPath:(id)arg1 withFilter:(CDUnknownBlockType)arg2;
@property(readonly) unsigned long long numIndexedObjects; // @synthesize numIndexedObjects;
@property(readonly) MADirectoryIndexNode *indexRoot; // @synthesize indexRoot;
- (void).cxx_destruct;
- (_Bool)itemAtPathIsAnAlias:(id)arg1;
- (id)newNodeByResolveAndIndexAliasAtPath:(id)arg1 atDepth:(unsigned long long)arg2 withFilter:(CDUnknownBlockType)arg3 shouldStop:(_Bool *)arg4;
- (id)newNodeByResolvingAndIndexSymbolicLinkAtPath:(id)arg1 atDepth:(unsigned long long)arg2 withFilter:(CDUnknownBlockType)arg3 shouldStop:(_Bool *)arg4;
- (id)newNodeByIndexingDirectoryAtPath:(id)arg1 atDepth:(unsigned long long)arg2 withFilter:(CDUnknownBlockType)arg3 shouldStop:(_Bool *)arg4;
- (id)newIndexItemAtPath:(id)arg1 withAttributes:(id)arg2 atDepth:(unsigned long long)arg3 withFilter:(CDUnknownBlockType)arg4 shouldStop:(_Bool *)arg5;
- (void)updateIndexWithFilter:(CDUnknownBlockType)arg1;
- (_Bool)isEqual:(id)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithPath:(id)arg1 filter:(CDUnknownBlockType)arg2;

@end

