//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MADSPPlugInUserDataObjc_Dictionary.h"

@interface MADSPPlugInUserDataObjc_PropertyInfo : MADSPPlugInUserDataObjc_Dictionary
{
}

+ (id)propertyInfoReadable:(_Bool)arg1 writeable:(_Bool)arg2;
+ (id)propertyInfoWithUserData:(void *)arg1;
@property(nonatomic, getter=isWriteable) _Bool writeable;
@property(nonatomic, getter=isReadable) _Bool readable;
- (id)initReadable:(_Bool)arg1 writeable:(_Bool)arg2;

@end

