//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MADSPPlugInUserDataObjc_Dictionary.h"

@interface MADSPPlugInUserDataObjc_GridLine : MADSPPlugInUserDataObjc_Dictionary
{
}

+ (id)gridLineWithType:(int)arg1 position:(double)arg2;
+ (id)gridLineWithUserData:(void *)arg1;
@property(nonatomic) double position;
@property(nonatomic) int type;
- (id)initWithType:(int)arg1 position:(double)arg2;

@end

