//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface MAFileSystemMetadataStorage : NSObject
{
}

+ (void)removeExtendedAttribute:(id)arg1 fromURL:(id)arg2 flags:(unsigned long long)arg3;
+ (id)readExtendedAttribute:(id)arg1 fromURL:(id)arg2 flags:(unsigned long long)arg3 bypassLocking:(_Bool)arg4;
+ (id)readExtendedAttribute:(id)arg1 fromURL:(id)arg2 flags:(unsigned long long)arg3;
+ (void)addExtendedAttributes:(id)arg1 toURL:(id)arg2 allowsOverwrite:(_Bool)arg3 flags:(unsigned long long)arg4 bypassLocking:(_Bool)arg5;
+ (void)addExtendedAttributes:(id)arg1 toURL:(id)arg2 allowsOverwrite:(_Bool)arg3 flags:(unsigned long long)arg4;
+ (id)physicalURLFromURL:(id)arg1;
+ (void)registerUbiquitousContainerURL:(id)arg1;

@end

