//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface MAImageUtilities : NSObject
{
}

+ (id)imageWithSize:(struct CGSize)arg1 andColor:(id)arg2;
+ (id)smallerPNGVersionOfImage:(id)arg1 withMaxFileSizeInByte:(long long)arg2 andMaxImageSize:(struct CGSize)arg3;
+ (id)smallerJPEGVersionOfImage:(id)arg1 withMaxFileSizeInByte:(long long)arg2;
+ (id)resizedImage:(id)arg1 toSize:(struct CGSize)arg2;
+ (id)croppedToSquareVersionOfImage:(id)arg1;
+ (id)normalizedImage:(id)arg1;
+ (id)convertImageToGrayScale:(id)arg1;
+ (struct CGImage *)newCGImageFromImage:(id)arg1;

@end

