//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface MAKitVideoTimecodeUtilities : NSObject
{
}

+ (CDStruct_198678f7)timeWithSignedVideoSubframes:(long long)arg1 andTimecodeMode:(long long)arg2 roundResult:(_Bool)arg3;
+ (long long)signedVideoSubframesWithTime:(CDStruct_198678f7)arg1 andTimecodeMode:(long long)arg2 roundResult:(_Bool)arg3;
+ (_Bool)isDropFrameForTimecodeMode:(long long)arg1;
+ (_Bool)isDurationForTimecodeMode:(long long)arg1;
+ (double)videoFrameRateForTimecodeMode:(long long)arg1;
+ (unsigned long long)minimumTickRateForMode:(long long)arg1;

@end

