//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class MAMetroResult, NSURL;

@interface MAMetroSegmentsCreator : NSObject
{
    MAMetroResult *result;
    NSURL *audioFileURL;
    int firstBeatIndexInFirstBar;
    int lastBeatIndexInLastBar;
    _Bool isBeatless;
    struct ExtendedBeatInfo *beats;
    int numBeats;
    struct ExtendedBeatInfo **bars;
    int numBars;
    int sequentialSegmentCount;
}

@property(retain, nonatomic) NSURL *audioFileURL; // @synthesize audioFileURL;
@property(nonatomic) _Bool isBeatless; // @synthesize isBeatless;
@property(nonatomic) int numBeats; // @synthesize numBeats;
@property(nonatomic) struct ExtendedBeatInfo *beats; // @synthesize beats;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)segmentsBasedOnSections;
- (id)segmentsBasedOnSuccessiveSections;
- (id)segmentsWithSameChordsSequenceAndLengthAs:(id)arg1 fromBar:(int)arg2 toBarEnd:(int)arg3;
- (id)segmentsWithSameChordsSequenceAndLengthAs:(id)arg1;
- (id)segmentsWithChordsSequence:(id)arg1 length:(int)arg2 fromBar:(int)arg3 toBarEnd:(int)arg4;
- (id)segmentsWithChordsSequence:(id)arg1 length:(int)arg2;
- (id)segmentsOfBarLength:(int)arg1 fromBar:(int)arg2 toBarEnd:(int)arg3;
- (id)segmentsOfBarLength:(int)arg1;
- (id)segmentFromStartToEnd;
- (id)segmentFromFullResultExtension;
- (int)snappedBeatIndexForTime:(double)arg1;
- (id)trivialChordStringForBeat:(struct ExtendedBeatInfo *)arg1;
- (double)relevantEndTime;
- (double)relevantStartTime;
- (int)beatDenominatorAtIndex:(int)arg1;
- (int)beatNumeratorAtIndex:(int)arg1;
- (double)beatTimeAtIndex:(int)arg1;
- (struct ExtendedBeatInfo *)beatAtIndex:(int)arg1;
- (int)lastBeatIndex;
- (int)firstBeatIndex;
- (int)lastBeatIndexForLastBar;
- (int)firstBeatIndexForFirstBar;
- (int)beatForBar:(int)arg1;
- (int)barEndAtOrBeforeBeatIndex:(int)arg1;
- (int)barStartAtOrAfterBeatIndex:(int)arg1;
- (void)updateInternalDataStructures;
- (id)relevantBeatsArrayForResult:(id)arg1;
- (void)dealloc;
- (id)initWithResult:(id)arg1 audioFileURL:(id)arg2;
@property(retain, nonatomic) MAMetroResult *result;

@end

