//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface MAMetroRingBufferRecorder : NSObject
{
    struct CMetroRingBufferRecorder<float> *_recorder;
    int _nChannels;
}

- (RbRecReadChunk_804bdac0)readFrom:(long long)arg1 length:(long long)arg2;
- (void)appendData:(const float *)arg1 length:(long long)arg2;
- (void)reset;
- (struct RbRecRange)currentRange;
- (long long)capacity;
- (void)dealloc;
- (id)initWithMinSize:(long long)arg1 channels:(int)arg2;
- (id)initWithMinSize:(long long)arg1 channels:(int)arg2 chunkSize:(long long)arg3;

@end

