//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UITouch;

@protocol MAPlgUIPedalBoardAreaActionHandler <NSObject>

@optional
- (void)areaWillStartAction;
- (void)areaItemTouched:(long long)arg1;
- (void)areaItemSelected:(long long)arg1;
- (void)areaItemReplacedAtIndex:(long long)arg1;
- (void)areaItemMovedFromIndex:(long long)arg1 toIndex:(long long)arg2;
- (void)areaItemInsertedAtIndex:(long long)arg1;
- (void)areaItemDoubleTapped:(long long)arg1;
- (void)areaItemDeletedAtIndex:(long long)arg1;
- (_Bool)areaIsItemEnabled:(long long)arg1;
- (_Bool)areaIsGapEnabled:(long long)arg1;
- (void)areaGapSelected:(long long)arg1;
- (void)areaDidFinishActions;
- (_Bool)areaCanMoveItemFrom:(long long)arg1 to:(long long)arg2;
- (_Bool)areaCanDeleteItemAtIndex:(long long)arg1;
- (_Bool)areaAllowedToHandleTouch:(UITouch *)arg1;
- (_Bool)areaAllowedToHandleTap:(UITouch *)arg1;
- (_Bool)areaActionsAllowed;
@end

