//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSUbiquitousKeyValueStore;

@interface MASharedUbiquityKVStore : NSObject
{
    NSUbiquitousKeyValueStore *_kvStore;
    _Bool _kvStoreAvailable;
}

+ (id)defaultSharedKVStore;
- (void).cxx_destruct;
- (id)mutableDictionaryForAppID:(long long)arg1;
- (id)dictionaryForAppID:(long long)arg1;
- (void)setDictionary:(id)arg1 forAppID:(long long)arg2;
- (_Bool)sharedKVStoreIsAvailable;
- (id)_keyForAppID:(long long)arg1;
- (void)_handleExternalKVStoreChanges:(id)arg1;
- (id)init;

@end

