//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class MASKCategory, NSSet, NSString;

@interface MASKTag : NSManagedObject
{
}

+ (id)findOrCreateWithIdentifier:(id)arg1 inContext:(id)arg2;
+ (id)entityName;
@property(readonly, nonatomic) _Bool allowsRangeFilter; // @dynamic allowsRangeFilter;
- (void)setLocalizedLabel:(id)arg1;
@property(readonly, nonatomic) __weak NSString *localizedLabel; // @dynamic localizedLabel;

// Remaining properties
@property(retain, nonatomic) MASKCategory *category; // @dynamic category;
@property(retain, nonatomic) NSString *label; // @dynamic label;
@property(retain, nonatomic) NSSet *taggings; // @dynamic taggings;

@end

