//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSSet, NSString;

@interface MASKCategory : NSManagedObject
{
}

+ (id)findOrCreateWithIdentifier:(id)arg1 inContext:(id)arg2;
+ (id)entityName;
- (void)setLocalizedName:(id)arg1;
@property(readonly, nonatomic) __weak NSString *localizedName; // @dynamic localizedName;

// Remaining properties
@property(retain, nonatomic) NSSet *children; // @dynamic children;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) MASKCategory *parent; // @dynamic parent;
@property(retain, nonatomic) NSSet *tags; // @dynamic tags;

@end

