//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MAUIScrollView, UILongPressGestureRecognizer;
@protocol MAUIRubberBandViewDelegate;

@interface MAUIRubberBandView : UIView
{
    MAUIScrollView *_scrollView;
    struct CGPoint _startPoint;
    UILongPressGestureRecognizer *_longPressRecognizer;
    _Bool _isInRubberBandMode;
    UIView *_indicationView;
    double _fixedY;
    double _fixedHeight;
    id _target;
    SEL _action;
    id _userInfo;
    id <MAUIRubberBandViewDelegate> _delegate;
}

@property(nonatomic) id <MAUIRubberBandViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) id target; // @synthesize target=_target;
- (void).cxx_destruct;
- (void)didMoveToSuperview;
- (void)_handleScrollViewDidScrollNotification:(id)arg1;
- (void)externalLongPressRecognizerAction:(id)arg1;
- (void)_gestureAction:(id)arg1 isAutoScroll:(_Bool)arg2;
- (void)_switchToRubberBandMode;
- (void)_startAnimatedIndicationMode;
- (id)initWithFrame:(struct CGRect)arg1;

@end

