//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAUITransitionView.h"

#import "CAAnimationDelegate-Protocol.h"

@class CALayer, NSString, UIColor, UIImage;

@interface MAUISimpleDrawerTransitionView : MAUITransitionView <CAAnimationDelegate>
{
    double _startY;
    CALayer *_perspectiveLayer;
    CALayer *_backgroundLayer;
    CALayer *_sourceLayer;
    CALayer *_targetLayer;
    UIColor *_fadeInOutBackgroundColor;
    UIImage *_backgroundImage;
    long long _animationIndex;
    UIColor *_drawerBigViewDimLayerColor;
}

@property(retain, nonatomic) UIColor *drawerBigViewDimLayerColor; // @synthesize drawerBigViewDimLayerColor=_drawerBigViewDimLayerColor;
@property(nonatomic) long long animationIndex; // @synthesize animationIndex=_animationIndex;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) UIColor *fadeInOutBackgroundColor; // @synthesize fadeInOutBackgroundColor=_fadeInOutBackgroundColor;
- (void).cxx_destruct;
- (void)_startAnimation;
- (void)_darkAnimation:(id)arg1:(double *)arg2;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)animationDidStart:(id)arg1;
- (_Bool)_deferNewViewAddingAfterAnimation;
- (_Bool)_deferOldViewRemovalAfterAnimation;
- (void)_resetAnimationHelpers;
- (void)_transformPerspectiveWithDuration:(double)arg1 zPos:(double)arg2 yRot:(double)arg3 xRot:(double)arg4 yPos:(double)arg5;
- (void)_transformDrawerWithDuration:(double)arg1 YPos:(double)arg2 zPos:(double)arg3 rot1:(double)arg4 rot2:(double)arg5;
- (void)_transformDrawerWithDuration:(double)arg1 YPos:(double)arg2 zPos:(double)arg3 rot1:(double)arg4 rot2:(double)arg5 timingName:(id)arg6;
- (void)_pauseAnimationWithDuration:(double)arg1;
- (void)_destroyAnimationHelperViewsAndLayers;
- (void)_initialize3DTransformsAndLayersForPushIn;
- (void)_initialize3DTransformsAndLayersForPullOut;
- (id)_addDimLayerToLayerIfNeeded:(id)arg1 color:(id)arg2;
- (struct CATransform3D)_transformPerspectiveWithZPos:(double)arg1 yRot:(double)arg2 xRot:(double)arg3 yPos:(double)arg4;
- (void)_transformWithYPos:(double)arg1 zPos:(double)arg2 rot1:(double)arg3 rot2:(double)arg4;
- (struct CATransform3D)_transformSourceLayerWithYPos:(double)arg1 zPos:(double)arg2 rot1:(double)arg3 rot2:(double)arg4;
- (struct CATransform3D)_transformTargetLayerWithYPos:(double)arg1 zPos:(double)arg2 rot1:(double)arg3 rot2:(double)arg4;
- (id)_getSurfaceLayer:(struct CATransform3D)arg1 forView:(id)arg2 anchorPoint:(struct CGPoint)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

