//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString;
@protocol MAUITransitionViewDelegate;

@interface MAUITransitionView : UIView
{
    _Bool _userInteractionWasEnabled;
    _Bool _globalUserInteractionNeedsEndIgnoring;
    _Bool _animating;
    _Bool _viewsOnlyUsedForTransition;
    _Bool _isSingleViewAnimation;
    _Bool _dimContent;
    int _direction;
    UIView *_currentView;
    UIView *_theNewView;
    id <MAUITransitionViewDelegate> _delegate;
    NSString *_animationID;
    void *_context;
    double _duration;
}

@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) int direction; // @synthesize direction=_direction;
@property(nonatomic) _Bool dimContent; // @synthesize dimContent=_dimContent;
@property(nonatomic) _Bool isSingleViewAnimation; // @synthesize isSingleViewAnimation=_isSingleViewAnimation;
@property(nonatomic) _Bool viewsOnlyUsedForTransition; // @synthesize viewsOnlyUsedForTransition=_viewsOnlyUsedForTransition;
@property(nonatomic) void *context; // @synthesize context=_context;
@property(readonly, nonatomic) NSString *animationID; // @synthesize animationID=_animationID;
@property(readonly, nonatomic, getter=isAnimating) _Bool animating; // @synthesize animating=_animating;
@property(nonatomic) __weak id <MAUITransitionViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *theNewView; // @synthesize theNewView=_theNewView;
@property(retain, nonatomic) UIView *currentView; // @synthesize currentView=_currentView;
- (void).cxx_destruct;
- (_Bool)_hackForceToKeepView;
- (void)cancelTransition;
- (void)replaceSubviewWithView:(id)arg1 direction:(int)arg2 duration:(double)arg3 dimmContent:(_Bool)arg4 animationID:(id)arg5 context:(void *)arg6;
- (void)_startAnimation;
- (void)_animationDidStop:(_Bool)arg1;
- (void)_animationDidStart;
- (void)_animationWillStart;
- (_Bool)_deferNewViewAddingAfterAnimation;
- (_Bool)_deferOldViewRemovalAfterAnimation;
- (id)_internalAnimationKey;
- (void)_destroyAnimationHelperViewsAndLayers;
- (void)_originalAddSubview:(id)arg1;
- (void)addSubview:(id)arg1;
- (void)removeFromSuperview;
- (void)dealloc;

@end

