//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class EcTimer, UILabel, UIView;

@interface MAUIInfoOverlayViewController : UIViewController
{
    EcTimer *_timer;
    _Bool _visible;
    UIViewController *_overlayParentViewController;
    UILabel *_label;
    UIView *_anchorPointView;
}

@property(readonly, nonatomic, getter=isVisible) _Bool visible; // @synthesize visible=_visible;
@property(retain, nonatomic) UIView *anchorPointView; // @synthesize anchorPointView=_anchorPointView;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(nonatomic) __weak UIViewController *overlayParentViewController; // @synthesize overlayParentViewController=_overlayParentViewController;
- (void).cxx_destruct;
- (void)setText:(id)arg1;
- (void)autoShowForRect:(struct CGRect)arg1 inView:(id)arg2;
- (void)showForRect:(struct CGRect)arg1 inView:(id)arg2;
- (void)_setViewRectForRect:(struct CGRect)arg1 inView:(id)arg2;
- (void)closeImmediately;
- (void)close;
- (void)show;
- (void)autoShow;
- (void)dealloc;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)cleanUp;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 overlayParentViewController:(id)arg3;

@end

