//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "MAAssetManagerMixInParentProtocol-Protocol.h"

@class MAAssetManagerMixIn, NSDate, NSDictionary, NSString;

@interface MAUILevelMeterView : UIView <MAAssetManagerMixInParentProtocol>
{
    unsigned int _displayLEDLevel;
    unsigned int _maxDisplayLEDLevel;
    unsigned int _fallBackReferenceLEDLevel;
    MAAssetManagerMixIn *_assetManagerMixIn;
    _Bool _peak;
    unsigned int _LEDCount;
    double _fallBackTime;
    double _maxLevelHoldTime;
    double _onStateLEDInset;
    NSDate *_lastUpdateDate;
    NSDate *_lastMaxUpdateDate;
    NSDictionary *_assetSet;
}

+ (id)assetSetFamily;
@property(retain, nonatomic) NSDictionary *assetSet; // @synthesize assetSet=_assetSet;
@property(retain, nonatomic) NSDate *lastMaxUpdateDate; // @synthesize lastMaxUpdateDate=_lastMaxUpdateDate;
@property(retain, nonatomic) NSDate *lastUpdateDate; // @synthesize lastUpdateDate=_lastUpdateDate;
@property(nonatomic) double onStateLEDInset; // @synthesize onStateLEDInset=_onStateLEDInset;
@property double maxLevelHoldTime; // @synthesize maxLevelHoldTime=_maxLevelHoldTime;
@property double fallBackTime; // @synthesize fallBackTime=_fallBackTime;
@property(nonatomic) unsigned int LEDCount; // @synthesize LEDCount=_LEDCount;
@property(nonatomic) _Bool peak; // @synthesize peak=_peak;
- (void).cxx_destruct;
- (id)assetSetFamily;
- (_Bool)tryInitializationOnAssetChange;
@property(retain, nonatomic) MAAssetManagerMixIn *assetManagerMixIn; // @synthesize assetManagerMixIn=_assetManagerMixIn;
- (void)setLevel:(float)arg1;
- (id)resourceBundleID;
- (void)setResourceBundleID:(id)arg1;
- (id)assetSetPath;
- (void)setAssetSetPath:(id)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)setHidden:(_Bool)arg1;
- (_Bool)needsAnimationTrigger;
- (void)drawRect:(struct CGRect)arg1;
- (id)peakOffImage;
- (id)peakOnImage;
- (id)levelMeterOnImage;
- (id)levelMeterOffImage;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)testInitialization;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

