//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSArray, UIImageView;

@interface MAUIImageSlider : UIControl
{
    double _value;
    double _valueAtGestureBeginning;
    struct CGPoint _locationAtGestureBeginning;
    NSArray *_images;
    UIImageView *_imageView;
}

@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)_handlePanGesture:(id)arg1;
- (void)updateImage;
@property(nonatomic) double value;
@property(retain, nonatomic) NSArray *images;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)layoutSubviews;
- (void)_initSelf;

@end

