//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAUISliderAccessibility_super.h"

@interface MAUISliderAccessibility : MAUISliderAccessibility_super
{
}

+ (void)_initializeSafeCategory;
- (void)accessibilityDecrement;
- (void)accessibilityIncrement;
- (id)_accessibilityCurrentTick;
- (double)_accessibilityTickStep;
- (long long)_accessibilitySliderNumTicks;
- (_Bool)_accessibilitySliderIsContinuous;
- (double)_accessibilityMaxSliderValue;
- (double)_accessibilityMinSliderValue;
- (unsigned long long)accessibilityTraits;
- (_Bool)isAccessibilityElement;

@end

