//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CALayer, NSString;

@protocol MAVeDrawingProtocol <NSObject>
@property(nonatomic) _Bool isLiveResize;
@property(nonatomic) _Bool displayDefaultDisabled;
@property(readonly, nonatomic) CALayer *contentLayer;
@property(copy, nonatomic) NSString *resourceBundleID;
@property(copy, nonatomic) NSString *assetSetPath;
@property(nonatomic) __weak CALayer *rootLayer;
- (void)setNeedsLayout;
- (void)setupLayersWithRootLayer:(CALayer *)arg1;
- (void)updateLayers;
@end

