//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MAVeValue, NSDictionary, NSString;
@protocol MAVeValueClient;

@protocol MAVeValueHostProtocol <NSObject>
@property(readonly, nonatomic) NSDictionary *dirtyValues;
@property(readonly, nonatomic) NSDictionary *allValues;
@property(nonatomic) _Bool snapsToIntegerValues;
@property(nonatomic) id <MAVeValueClient> valueClient;
- (void)abortValueChange:(NSString *)arg1;
- (void)endValueChange:(NSString *)arg1;
- (void)valueChange:(NSString *)arg1;
- (void)beginValueChange:(NSString *)arg1;
- (MAVeValue *)valueWithID:(NSString *)arg1;

@optional
- (void)resetValueAtPosition:(struct CGPoint)arg1;
- (void)stringValueChange:(NSString *)arg1;
@end

