//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAVeGraphShPoint.h"

@class CALayer, NSDictionary;

@interface MAVeGraphShPointAndLine : MAVeGraphShPoint
{
    _Bool _vertical;
    double _lineAnchor;
    double _lineWidth;
    NSDictionary *_lineColors;
    CALayer *_lineLayer;
}

+ (id)graphPointWithCoPosition:(id)arg1;
@property(retain, nonatomic) CALayer *lineLayer; // @synthesize lineLayer=_lineLayer;
@property(retain, nonatomic) NSDictionary *lineColors; // @synthesize lineColors=_lineColors;
@property(nonatomic) double lineWidth; // @synthesize lineWidth=_lineWidth;
@property(nonatomic) double lineAnchor; // @synthesize lineAnchor=_lineAnchor;
@property(nonatomic) _Bool vertical; // @synthesize vertical=_vertical;
- (void).cxx_destruct;
- (void)updateLineLayer;
- (void)updateLayers;
- (void)setLayerVisible:(_Bool)arg1;
- (void)setNeedsLayout;
- (void)tearDownLayers;
- (void)setupLayersWithSuperlayer:(id)arg1;
- (void)layoutSublayersOfLayer:(id)arg1;
- (id)actionForLayer:(id)arg1 forKey:(id)arg2;
@property(nonatomic) double design_lineLength;
@property(readonly, nonatomic) double lineLength;
@property(readonly, nonatomic) struct CGColor *lineColor;

@end

