//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAVeElementBase.h"

@class NSMutableArray;
@protocol MAVeRemixerResizeHandleDelegate;

@interface MAVeRemixerResizeHandle : MAVeElementBase
{
    id _backgroundColor;
    id _lineColor;
    unsigned long long _numLines;
    id <MAVeRemixerResizeHandleDelegate> _delegate;
    NSMutableArray *_lineLayers;
    double _vector;
}

@property(nonatomic) double vector; // @synthesize vector=_vector;
@property(retain, nonatomic) NSMutableArray *lineLayers; // @synthesize lineLayers=_lineLayers;
@property(nonatomic) id <MAVeRemixerResizeHandleDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long numLines; // @synthesize numLines=_numLines;
@property(retain, nonatomic) id lineColor; // @synthesize lineColor=_lineColor;
@property(retain, nonatomic) id backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void).cxx_destruct;
- (void)upEvent:(id)arg1;
- (void)draggedEvent:(id)arg1;
- (void)downEvent:(id)arg1;
- (void)updateLayers;
- (void)tearDownLayers;
- (void)setupLayersWithRootLayer:(id)arg1;
@property(nonatomic) double design_lineWidth;
@property(readonly, nonatomic) double lineWidth;
@property(nonatomic) double design_lineLength;
@property(readonly, nonatomic) double lineLength;
@property(readonly, nonatomic) double pixelAccurateLineWidth;
@property(readonly, nonatomic) double pixelAccurateLineLength;
@property(readonly, nonatomic) struct CGRect pixelAccurateLineFrame;
- (double)pixelAccurateCoordinate:(double)arg1;
- (void)assetSetHasChanged;
- (id)init;

@end

