//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAVeContinuousControl.h"

@class CAGradientLayer, CALayer, NSDictionary;

@interface MAVeRoundSlider : MAVeContinuousControl
{
    _Bool _bipolar;
    _Bool _clockwise;
    _Bool _forceExact90DegreeAngles;
    _Bool _halfPixelMode;
    NSDictionary *_appearance;
    double _bipolarCenterValue;
    double _maxAngle;
    double _minAngle;
    double _actionStartValue;
    CALayer *_bodyLayer;
    CALayer *_bodyTopEdgeLayer;
    CAGradientLayer *_bodyGradientLayer;
    CALayer *_markerLayer;
    CALayer *_trackLayer;
    CALayer *_trackFillLayer;
    struct CGPoint _design_rotationCenter;
    struct CGPoint _actionStartPoint;
}

@property(nonatomic) _Bool halfPixelMode; // @synthesize halfPixelMode=_halfPixelMode;
@property(retain, nonatomic) CALayer *trackFillLayer; // @synthesize trackFillLayer=_trackFillLayer;
@property(retain, nonatomic) CALayer *trackLayer; // @synthesize trackLayer=_trackLayer;
@property(retain, nonatomic) CALayer *markerLayer; // @synthesize markerLayer=_markerLayer;
@property(retain, nonatomic) CAGradientLayer *bodyGradientLayer; // @synthesize bodyGradientLayer=_bodyGradientLayer;
@property(retain, nonatomic) CALayer *bodyTopEdgeLayer; // @synthesize bodyTopEdgeLayer=_bodyTopEdgeLayer;
@property(retain, nonatomic) CALayer *bodyLayer; // @synthesize bodyLayer=_bodyLayer;
@property(nonatomic) double actionStartValue; // @synthesize actionStartValue=_actionStartValue;
@property(nonatomic) struct CGPoint actionStartPoint; // @synthesize actionStartPoint=_actionStartPoint;
@property(nonatomic) struct CGPoint design_rotationCenter; // @synthesize design_rotationCenter=_design_rotationCenter;
@property(nonatomic) _Bool forceExact90DegreeAngles; // @synthesize forceExact90DegreeAngles=_forceExact90DegreeAngles;
@property(nonatomic) double minAngle; // @synthesize minAngle=_minAngle;
@property(nonatomic) double maxAngle; // @synthesize maxAngle=_maxAngle;
@property(nonatomic) _Bool clockwise; // @synthesize clockwise=_clockwise;
@property(nonatomic) double bipolarCenterValue; // @synthesize bipolarCenterValue=_bipolarCenterValue;
@property(nonatomic) _Bool bipolar; // @synthesize bipolar=_bipolar;
@property(retain, nonatomic) NSDictionary *appearance; // @synthesize appearance=_appearance;
- (void).cxx_destruct;
- (void)scrollEvent:(id)arg1;
- (void)gestureDetected:(id)arg1;
- (_Bool)onUpEvent:(id)arg1;
- (_Bool)onDraggedEvent:(id)arg1;
- (_Bool)onDownEvent:(id)arg1;
- (void)updateMarkerLayer;
- (void)updateBodyLayer;
- (void)updateTrackFillLayer;
- (void)updateTrackLayer;
- (void)updateLayers;
- (void)trackLayer:(id)arg1 updateMaskWithStartAngle:(double)arg2 endAngle:(double)arg3 radius:(double)arg4 clockwise:(_Bool)arg5;
- (void)tearDownLayers;
- (void)setupLayers;
- (double)valueFromAngle:(double)arg1;
- (struct CGPoint)pointFromAngle:(double)arg1 radius:(double)arg2;
- (double)moduloAngle:(double)arg1;
- (double)exact90DegAngle:(double)arg1;
- (double)differenceOfAngle:(double)arg1 andAngle:(double)arg2 clockwise:(_Bool)arg3;
- (double)bipolarCenterAngle;
- (double)angleFromValue:(double)arg1;
- (double)angleFromPoint:(struct CGPoint)arg1;
- (double)angleFromAngleDifference:(double)arg1 baseAngle:(double)arg2;
- (void)resetValueAtPosition:(struct CGPoint)arg1;
- (void)setScaleFactor:(double)arg1;
@property(readonly, nonatomic) struct CGPoint rotationCenter;
@property(readonly, nonatomic) double pixelAccurateTrackFillWidth;
@property(readonly, nonatomic) double pixelAccurateTrackWidth;
@property(readonly, nonatomic) struct CGPoint pixelAccurateRotationCenter;
@property(readonly, nonatomic) struct CGSize pixelAccurateMarkerSize;
@property(readonly, nonatomic) double pixelAccurateMarkerRadius;
@property(readonly, nonatomic) struct CGPoint pixelAccurateMarkerAnchorPoint;
@property(readonly, nonatomic) double pixelAccurateBodyTopEdgeBorderWidth;
@property(readonly, nonatomic) double pixelAccurateBodyRadius;
@property(readonly, nonatomic) _Bool fullCircle;
@property(nonatomic, setter=set_mainValueDefault:) double mainValueDefault;
@property(nonatomic, setter=set_mainValueMax:) double mainValueMax;
@property(nonatomic, setter=set_mainValueMin:) double mainValueMin;
@property(nonatomic, setter=set_mainValueNormed:) double mainValueNormed;
@property(nonatomic, setter=set_mainValue:) double mainValue;
@property(nonatomic) double design_valueRangeLength;
@property(readonly, nonatomic) double valueRangeLength;
@property(nonatomic) double design_trackFillWidth;
@property(readonly, nonatomic) double trackFillWidth;
@property(nonatomic) double design_trackWidth;
@property(readonly, nonatomic) double trackWidth;
@property(nonatomic) struct CGSize design_markerSize;
@property(readonly, nonatomic) struct CGSize markerSize;
@property(nonatomic) double design_markerRadius;
@property(readonly, nonatomic) double markerRadius;
@property(nonatomic) double design_bodyTopEdgeBorderWidth;
@property(readonly, nonatomic) double bodyTopEdgeBorderWidth;
@property(nonatomic) double design_bodyRadius;
@property(readonly, nonatomic) double bodyRadius;
- (void)setupLayersWithRootLayer:(id)arg1;
- (id)init;

@end

