//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSMutableDictionary, NSString;

@protocol MAVeScalablePropertyProtocol <NSObject>
@property(retain, nonatomic) NSMutableDictionary *scaledValues;
@property(retain, nonatomic) NSMutableDictionary *scalingRules;
@property(retain, nonatomic) NSMutableDictionary *designParameters;
@property(nonatomic) double scaleFactor;
@property(nonatomic) struct CGSize design_Size;
@property(nonatomic) struct CGPoint design_Origin;
- (struct CGRect)scaleRectWithName:(NSString *)arg1;
- (struct CGSize)scaleSizeWithName:(NSString *)arg1;
- (struct CGPoint)scalePointWithName:(NSString *)arg1;
- (double)scaleFloatWithName:(NSString *)arg1;
@end

