//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAVeUIViewAdapter.h"

@interface MAVeUISeparatorLineView : MAVeUIViewAdapter
{
}

+ (Class)drawableClass;

// Remaining properties
@property(nonatomic) double design_leftCapWidth; // @dynamic design_leftCapWidth;
@property(nonatomic) double design_lineWidth; // @dynamic design_lineWidth;
@property(nonatomic) double design_rightCapWidth; // @dynamic design_rightCapWidth;
@property(nonatomic) long long orientation; // @dynamic orientation;

@end

