//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAVeGraphShape.h"

#import "CALayerDelegate-Protocol.h"
#import "MAVeGraphLayerHostProtocol-Protocol.h"

@class CALayer, MAVeValueNumber, MAVeValuePoint, NSDictionary, NSString;

@interface MAVeGraphShRect : MAVeGraphShape <MAVeGraphLayerHostProtocol, CALayerDelegate>
{
    CALayer *_bodyLayer;
    MAVeValuePoint *_coPosition;
    MAVeValueNumber *_coWidth;
    MAVeValueNumber *_coHeight;
    MAVeValueNumber *_coLeft;
    MAVeValueNumber *_coTop;
    MAVeValueNumber *_coRight;
    MAVeValueNumber *_coBottom;
    CDUnknownBlockType _customSetupLayers;
    CDUnknownBlockType _customUpdateLayers;
    NSDictionary *_bodyFillColors;
    struct CGPoint _coActionOffset;
}

+ (id)graphRectWithCoLeft:(id)arg1 coTop:(id)arg2 coRight:(id)arg3 coBottom:(id)arg4;
+ (id)graphRectWithCoPosition:(id)arg1 coWidth:(id)arg2 coHeight:(id)arg3;
@property(retain, nonatomic) NSDictionary *bodyFillColors; // @synthesize bodyFillColors=_bodyFillColors;
@property(copy, nonatomic) CDUnknownBlockType customUpdateLayers; // @synthesize customUpdateLayers=_customUpdateLayers;
@property(copy, nonatomic) CDUnknownBlockType customSetupLayers; // @synthesize customSetupLayers=_customSetupLayers;
@property(nonatomic) struct CGPoint coActionOffset; // @synthesize coActionOffset=_coActionOffset;
@property(retain, nonatomic) MAVeValueNumber *coBottom; // @synthesize coBottom=_coBottom;
@property(retain, nonatomic) MAVeValueNumber *coRight; // @synthesize coRight=_coRight;
@property(retain, nonatomic) MAVeValueNumber *coTop; // @synthesize coTop=_coTop;
@property(retain, nonatomic) MAVeValueNumber *coLeft; // @synthesize coLeft=_coLeft;
@property(retain, nonatomic) CALayer *bodyLayer; // @synthesize bodyLayer=_bodyLayer;
- (void).cxx_destruct;
- (void)updateLayers;
- (void)setLayerVisible:(_Bool)arg1;
- (void)setNeedsLayout;
- (void)tearDownLayers;
- (void)setupLayersWithSuperlayer:(id)arg1;
- (void)layoutSublayersOfLayer:(id)arg1;
- (id)actionForLayer:(id)arg1 forKey:(id)arg2;
@property(readonly, nonatomic) struct CGColor *bodyFillColor;
@property(readonly, nonatomic) _Bool valid;
@property(retain, nonatomic) MAVeValueNumber *coHeight; // @synthesize coHeight=_coHeight;
@property(retain, nonatomic) MAVeValueNumber *coWidth; // @synthesize coWidth=_coWidth;
@property(retain, nonatomic) MAVeValuePoint *coPosition; // @synthesize coPosition=_coPosition;
- (id)coSize;
- (void)dealloc;
- (id)initWithCoLeft:(id)arg1 coTop:(id)arg2 coRight:(id)arg3 coBottom:(id)arg4;
- (id)initWithCoPosition:(id)arg1 coWidth:(id)arg2 coHeight:(id)arg3;

// Remaining properties
@property(copy, nonatomic) CDUnknownBlockType customTearDownLayers;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

