//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAVeLinearSlider.h"

@interface MAVeDoubleLinearSlider : MAVeLinearSlider
{
    _Bool _pushingValues;
    _Bool _pushingAction;
    double _middleDragValueDelta;
}

@property(nonatomic) _Bool pushingAction; // @synthesize pushingAction=_pushingAction;
@property(nonatomic) double middleDragValueDelta; // @synthesize middleDragValueDelta=_middleDragValueDelta;
@property(nonatomic) _Bool pushingValues; // @synthesize pushingValues=_pushingValues;
- (void)decrementValue;
- (void)incrementValue;
- (_Bool)onUpEvent:(id)arg1;
- (_Bool)onDraggedEvent:(id)arg1;
- (_Bool)onDownEvent:(id)arg1;
- (void)resetValueAtPosition:(struct CGPoint)arg1;
@property(nonatomic, setter=set_secondValueDefault:) double secondValueDefault;
@property(nonatomic, setter=set_secondValueMax:) double secondValueMax;
@property(nonatomic, setter=set_secondValueMin:) double secondValueMin;
@property(nonatomic, setter=set_secondValueNormed:) double secondValueNormed;
@property(nonatomic, setter=set_secondValue:) double secondValue;
@property(nonatomic, setter=set_firstValueDefault:) double firstValueDefault;
@property(nonatomic, setter=set_firstValueMax:) double firstValueMax;
@property(nonatomic, setter=set_firstValueMin:) double firstValueMin;
@property(nonatomic, setter=set_firstValueNormed:) double firstValueNormed;
@property(nonatomic, setter=set_firstValue:) double firstValue;
- (_Bool)bipolar;
- (id)init;

@end

