//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAVeUIViewAdapter.h"

@interface MAVeEqUILinearSliderView : MAVeUIViewAdapter
{
    _Bool _inverse;
    _Bool _snapsToIntegerValues;
}

+ (Class)drawableClass;
@property(nonatomic) _Bool snapsToIntegerValues; // @synthesize snapsToIntegerValues=_snapsToIntegerValues;
@property(nonatomic) _Bool inverse; // @synthesize inverse=_inverse;
- (_Bool)doubleTabGestureEnabled;

// Remaining properties
@property(nonatomic) _Bool bipolar; // @dynamic bipolar;
@property(nonatomic) double bipolarCenterValue; // @dynamic bipolarCenterValue;
@property(nonatomic, setter=set_mainValue:) double mainValue; // @dynamic mainValue;
@property(nonatomic, setter=set_mainValueDefault:) double mainValueDefault; // @dynamic mainValueDefault;
@property(nonatomic, setter=set_mainValueMax:) double mainValueMax; // @dynamic mainValueMax;
@property(nonatomic, setter=set_mainValueMin:) double mainValueMin; // @dynamic mainValueMin;

@end

