//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAVeElementBase.h"

@class CALayer;

@interface MAVeBalanceCorrelationMeter : MAVeElementBase
{
    _Bool _holdEnabled;
    CALayer *_backgroundLayer;
    CALayer *_balanceLayer;
    CALayer *_correlationLayer;
    CALayer *_negativeCorrelationLayer;
    CALayer *_correlationHoldLayer;
}

@property(retain, nonatomic) CALayer *correlationHoldLayer; // @synthesize correlationHoldLayer=_correlationHoldLayer;
@property(retain, nonatomic) CALayer *negativeCorrelationLayer; // @synthesize negativeCorrelationLayer=_negativeCorrelationLayer;
@property(retain, nonatomic) CALayer *correlationLayer; // @synthesize correlationLayer=_correlationLayer;
@property(retain, nonatomic) CALayer *balanceLayer; // @synthesize balanceLayer=_balanceLayer;
@property(retain, nonatomic) CALayer *backgroundLayer; // @synthesize backgroundLayer=_backgroundLayer;
@property(nonatomic) _Bool holdEnabled; // @synthesize holdEnabled=_holdEnabled;
- (void).cxx_destruct;
- (void)downEvent:(id)arg1;
- (void)updateLayers;
- (void)setupLayersWithRootLayer:(id)arg1;
@property(nonatomic) double balanceValue;
@property(nonatomic) double holdValue;
@property(nonatomic) double correlationValue;
- (id)init;

@end

