//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAVeElementBase.h"

@class NSMutableArray;

@interface MAVeCtrlClickMenu : MAVeElementBase
{
    NSMutableArray *_itemArray;
}

@property(retain, nonatomic) NSMutableArray *itemArray; // @synthesize itemArray=_itemArray;
- (void).cxx_destruct;
- (long long)indexOfItem:(id)arg1;
- (long long)indexOfSelectedItem;
- (id)selectedItem;
- (void)menuItemSelectedAtIndex:(long long)arg1;
- (void)selectItemWithTitle:(id)arg1;
- (void)selectItemAtIndex:(long long)arg1;
- (void)removeAllItems;
- (void)addItemWithTitle:(id)arg1 isSeparator:(_Bool)arg2 enabled:(_Bool)arg3;
- (void)addItemWithTitle:(id)arg1;
- (long long)numberOfItems;
@property(nonatomic) long long selectedIndex;
- (void)updateLayers;
- (void)setupLayersWithRootLayer:(id)arg1;
- (void)dealloc;
- (id)init;

@end

