//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAVeUIViewAdapter.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, UITableViewController;

@interface MAVeUIPopupButtonView : MAVeUIViewAdapter <UITableViewDataSource, UITableViewDelegate>
{
    double _maxWidth;
    double _baselinePosition;
    UITableViewController *_popoverMenuController;
}

+ (Class)drawableClass;
@property(retain, nonatomic) UITableViewController *popoverMenuController; // @synthesize popoverMenuController=_popoverMenuController;
@property(nonatomic) double baselinePosition; // @synthesize baselinePosition=_baselinePosition;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (long long)indexOfItemWithTitle:(id)arg1;
- (long long)indexOfSelectedItem;
- (id)selectedItemTitle;
- (void)menuItemSelectedAtIndex:(long long)arg1;
- (void)selectItemWithTitle:(id)arg1;
- (void)selectItemAtIndex:(long long)arg1;
- (void)removeAllItems;
- (void)addItemWithTitle:(id)arg1 shortTitle:(id)arg2 enabled:(_Bool)arg3;
- (void)addItemWithTitle:(id)arg1 shortTitle:(id)arg2;
- (void)addItemWithTitle:(id)arg1;
- (long long)numberOfItems;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)initializeAdapter;

// Remaining properties
@property(nonatomic) _Bool abbreviate; // @dynamic abbreviate;
@property(nonatomic) unsigned long long abbreviationLength; // @dynamic abbreviationLength;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool stickyGlyph; // @dynamic stickyGlyph;
@property(readonly) Class superclass;
@property(nonatomic) int textAlignment; // @dynamic textAlignment;
@property(retain, nonatomic) NSString *title; // @dynamic title;
@property(nonatomic) _Bool titleIsFixed; // @dynamic titleIsFixed;
@property(copy, nonatomic) NSString *truncationMode; // @dynamic truncationMode;

@end

