//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@class MSKeyboardView, NSMutableDictionary, UIImage;

@interface MSKeyboardContainerView : UIImageView
{
    MSKeyboardView *keyboardView;
    UIImageView *scaledBackgroundView;
    _Bool doubleKeyboard;
    _Bool scaled;
    UIImage *normalBackground;
    UIImage *doubleBackground;
    UIImage *normalScaledBackground;
    UIImage *doubleScaledBackground;
    UIImage *backgroundAnimationImage;
    struct CGRect controlsFrame;
    NSMutableDictionary *touchTranslation;
    struct CGRect normalKeyboardModelBounds;
    struct CGRect auxKeyboardModelBounds;
}

@property(retain, nonatomic) UIImage *backgroundAnimationImage; // @synthesize backgroundAnimationImage;
@property(nonatomic) struct CGRect controlsFrame; // @synthesize controlsFrame;
@property(nonatomic) _Bool scaled; // @synthesize scaled;
@property(nonatomic) _Bool doubleKeyboard; // @synthesize doubleKeyboard;
@property(retain, nonatomic) UIImage *doubleScaledBackground; // @synthesize doubleScaledBackground;
@property(retain, nonatomic) UIImage *normalScaledBackground; // @synthesize normalScaledBackground;
@property(retain, nonatomic) UIImage *doubleBackground; // @synthesize doubleBackground;
@property(retain, nonatomic) UIImage *normalBackground; // @synthesize normalBackground;
@property(retain, nonatomic) UIImageView *scaledBackgroundView; // @synthesize scaledBackgroundView;
@property(retain, nonatomic) MSKeyboardView *keyboardView; // @synthesize keyboardView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setAssetSet:(id)arg1;
- (void)renderBackgroundAnimationImage;

@end

