//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface MSKeyboardNoteView : UIView
{
    UILabel *noteLabel;
}

- (void).cxx_destruct;
- (void)setText:(id)arg1;
- (id)text;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_commonInit;

@end

