//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CAAnimationDelegate-Protocol.h"
#import "MAUIForwardTouchGestureRecognizerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class CbVelocityAnalyzer, MAUIForwardTouchGestureRecognizer, MSKeyboardInteraction, MSMIDIStack, NSDictionary, NSMutableDictionary, NSMutableSet, NSString, NSTimer;
@protocol NSObject><CbMidiInputProtocol;

@interface MSKeyboardInteractionView : UIView <UIGestureRecognizerDelegate, MAUIForwardTouchGestureRecognizerDelegate, CAAnimationDelegate>
{
    int interactionType;
    NSMutableDictionary *interactions;
    NSMutableSet *orphanedInteractions;
    NSMutableSet *quantizedInteractions;
    NSMutableDictionary *tileViews;
    NSMutableDictionary *blockedTiles;
    long long transpose;
    MSMIDIStack *midiStack;
    NSTimer *scrollingTimer;
    MSKeyboardInteraction *scrollingInteraction;
    _Bool scrollingLock;
    double quantizeTime;
    long long quantizeSteps;
    double vibratoTime;
    long long vibratoSteps;
    double eventTime;
    struct CGRect windowRect;
    id <NSObject><CbMidiInputProtocol> midiDelegate;
    _Bool reduceGlissandoVelocity;
    _Bool coalesceDeltasForBounce;
    double coalescedDeltas;
    struct CGPoint bouncePoint;
    CbVelocityAnalyzer *velocityAnalyzer;
    _Bool paramEditModeActive;
    struct CGImage *pitchDotImage;
    _Bool _useMidiStackInNormalMode;
    _Bool _useMidiStackInPitchMode;
    _Bool _canControlSustain;
    _Bool _preventSendingModWheelEvents;
    MAUIForwardTouchGestureRecognizer *_forwardTouchGestureRecogizer;
}

@property(retain, nonatomic) MAUIForwardTouchGestureRecognizer *forwardTouchGestureRecogizer; // @synthesize forwardTouchGestureRecogizer=_forwardTouchGestureRecogizer;
@property(nonatomic) _Bool preventSendingModWheelEvents; // @synthesize preventSendingModWheelEvents=_preventSendingModWheelEvents;
@property(nonatomic) _Bool canControlSustain; // @synthesize canControlSustain=_canControlSustain;
@property(nonatomic) _Bool useMidiStackInPitchMode; // @synthesize useMidiStackInPitchMode=_useMidiStackInPitchMode;
@property(nonatomic) _Bool useMidiStackInNormalMode; // @synthesize useMidiStackInNormalMode=_useMidiStackInNormalMode;
@property(nonatomic) _Bool paramEditModeActive; // @synthesize paramEditModeActive;
@property(retain, nonatomic) MSMIDIStack *midiStack; // @synthesize midiStack;
@property(nonatomic) id <NSObject><CbMidiInputProtocol> midiDelegate; // @synthesize midiDelegate;
@property(nonatomic) double eventTime; // @synthesize eventTime;
@property(nonatomic) long long vibratoSteps; // @synthesize vibratoSteps;
@property(nonatomic) double vibratoTime; // @synthesize vibratoTime;
@property(nonatomic) long long quantizeSteps; // @synthesize quantizeSteps;
@property(nonatomic) double quantizeTime; // @synthesize quantizeTime;
@property(nonatomic) _Bool reduceGlissandoVelocity; // @synthesize reduceGlissandoVelocity;
@property(readonly, nonatomic) NSDictionary *interactions; // @synthesize interactions;
@property(readonly, nonatomic) NSMutableDictionary *blockedTiles; // @synthesize blockedTiles;
@property(nonatomic) long long transpose; // @synthesize transpose;
@property(nonatomic) int interactionType; // @synthesize interactionType;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)_internalTouchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)mauiTouchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)mauiTouchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)mauiTouchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)mauiTouchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)removeAllAnimations;
- (void)resetOriginalKeyForAllInteractions;
- (void)endAllInteractions:(_Bool)arg1;
- (void)endAllInteractions;
- (void)resetPitchBend;
- (void)endInteraction:(id)arg1;
- (void)clearScrollingInteraction:(id)arg1;
- (void)scrollingInteractionEndedWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)scrollingInteractionMovedWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)scrollingInteractionBeganWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)setVelocityAnalyzerEnabled:(_Bool)arg1;
- (void)quantizeTimer:(id)arg1;
- (void)quantize:(id)arg1;
- (void)eventTimer:(id)arg1;
- (unsigned long long)velocityForTouch:(id)arg1;
- (void)pitchbendInteractionEndedWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)pitchbendInteractionMovedWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)sendYAxisModulationForInteraction:(id)arg1 hitKey:(id)arg2 currentLocation:(struct CGPoint)arg3;
- (long long)pitchBendPerNote;
- (double)pitchBendRangeForTile:(id)arg1;
- (void)pitchbendInteractionBeganWithTouch:(id)arg1 withEvent:(id)arg2;
- (int)pitchBendModeYAxisMessageTypeForInteraction:(id)arg1;
- (void)sendValue:(int)arg1 withStatus:(int)arg2 forInteraction:(id)arg3;
- (void)sendValue:(int)arg1 withStatus:(int)arg2 forInteraction:(id)arg3 orTouch:(id)arg4;
- (id)possibleChannelsForInteraction:(id)arg1;
- (void)normalInteractionEndedWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)normalInteractionMovedWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)normalInteractionBeganWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)garbageCollectInvalidInteractionsWithEvent:(id)arg1;
- (_Bool)validateInteraction:(id)arg1 withCurrentDeltaX:(double)arg2 andBuffer:(long long)arg3;
- (_Bool)validateInteraction:(id)arg1 withCurrentDeltaX:(double)arg2;
- (id)movementLayer;
- (void)adoptInteraction:(id)arg1 forTouch:(id)arg2 withHitKey:(id)arg3 inTile:(id)arg4;
- (void)setupInteraction:(id)arg1 forTouch:(id)arg2 withHitKey:(id)arg3 inTile:(id)arg4;
- (void)recacheTileViews;
- (id)_keyForTile:(id)arg1 touch:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_commonInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

