//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSAttributedString.h>

@interface NSAttributedString (OHCommodityConstructors)
+ (id)attributedStringWithAttributedString:(id)arg1;
+ (id)attributedStringWithString:(id)arg1;
- (id)linkAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (id)paragraphStyleAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (unsigned char)lineBreakModeAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (unsigned char)textAlignmentAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (_Bool)textIsBoldAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (int)textUnderlineStyleAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (_Bool)textIsUnderlinedAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (id)textColorAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (struct __CTFont *)fontAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (struct CGSize)sizeConstrainedToSize:(struct CGSize)arg1 fitRange:(struct _NSRange *)arg2;
- (struct CGSize)sizeConstrainedToSize:(struct CGSize)arg1;
@end

