//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface NSObject (AXCategory)
- (id)cbAccessibilityViewController;
- (_Bool)cbAccessibilityElementIsEffectivelyOffscreen;
- (id)cbAccessibilitySearchAncestorsWithCondition:(CDUnknownBlockType)arg1;
- (id)cbAccessibilityDescendentsPassingTest:(CDUnknownBlockType)arg1;
- (id)cbAccessibilitySearchChildrenWithCondition:(CDUnknownBlockType)arg1;
- (id)cbAccessibilityValueForKey:(id)arg1;
- (void)cbAccessibilitySetValue:(id)arg1 forKey:(id)arg2 retain:(_Bool)arg3;
- (void)accessibilityAddUIAccessibilityTrait:(unsigned long long)arg1;
- (void)accessibilityRemoveUIAccessibilityTrait:(unsigned long long)arg1;
- (id)accessibilitySubviewsOfType:(Class)arg1;
- (id)accessibilityAncestorOfType:(Class)arg1;
- (id)safeValueForKey:(id)arg1;
@end

