//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NXOAuth2ConnectionDelegate-Protocol.h"

@class NSMutableArray, NSSet, NSString, NSURL, NXOAuth2AccessToken, NXOAuth2Connection;
@protocol NXOAuth2ClientDelegate;

@interface NXOAuth2Client : NSObject <NXOAuth2ConnectionDelegate>
{
    _Bool authenticating;
    _Bool persistent;
    NSString *clientId;
    NSString *clientSecret;
    NSSet *desiredScope;
    NSString *userAgent;
    NSURL *authorizeURL;
    NSURL *tokenURL;
    NXOAuth2Connection *authConnection;
    NXOAuth2AccessToken *accessToken;
    NSMutableArray *waitingConnections;
    long long refreshConnectionDidRetryCount;
    NSObject<NXOAuth2ClientDelegate> *delegate;
}

@property(nonatomic, getter=isAuthenticating) _Bool authenticating; // @synthesize authenticating;
@property(nonatomic, getter=isPersistent) _Bool persistent; // @synthesize persistent;
@property(nonatomic) NSObject<NXOAuth2ClientDelegate> *delegate; // @synthesize delegate;
@property(copy, nonatomic) NSString *userAgent; // @synthesize userAgent;
@property(copy, nonatomic) NSSet *desiredScope; // @synthesize desiredScope;
@property(readonly, copy, nonatomic) NSString *clientSecret; // @synthesize clientSecret;
@property(readonly, copy, nonatomic) NSString *clientId; // @synthesize clientId;
- (void)oauthConnection:(id)arg1 didFailWithError:(id)arg2;
- (void)oauthConnection:(id)arg1 didFinishWithData:(id)arg2;
- (void)removeConnectionFromWaitingQueue:(id)arg1;
- (void)refreshAccessTokenAndRetryConnection:(id)arg1;
- (void)refreshAccessToken;
- (void)authenticateWithUsername:(id)arg1 password:(id)arg2;
- (void)requestTokenWithAuthGrant:(id)arg1 redirectURL:(id)arg2;
- (_Bool)openRedirectURL:(id)arg1;
- (id)authorizationURLWithRedirectURL:(id)arg1;
- (void)requestAccess;
@property(retain, nonatomic) NXOAuth2AccessToken *accessToken; // @synthesize accessToken;
- (void)dealloc;
- (id)initWithClientID:(id)arg1 clientSecret:(id)arg2 authorizeURL:(id)arg3 tokenURL:(id)arg4 accessToken:(id)arg5 persistent:(_Bool)arg6 delegate:(id)arg7;
- (id)initWithClientID:(id)arg1 clientSecret:(id)arg2 authorizeURL:(id)arg3 tokenURL:(id)arg4 delegate:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

