//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSInputStream, NSString;

@interface NXOAuth2FileStreamWrapper : NSObject
{
    NSInputStream *stream;
    unsigned long long contentLength;
    NSString *fileName;
}

+ (id)wrapperWithStream:(id)arg1 contentLength:(unsigned long long)arg2 fileName:(id)arg3;
+ (id)wrapperWithStream:(id)arg1 contentLength:(unsigned long long)arg2;
@property(readonly, copy, nonatomic) NSString *fileName; // @synthesize fileName;
@property(readonly, nonatomic) unsigned long long contentLength; // @synthesize contentLength;
@property(readonly, nonatomic) NSInputStream *stream; // @synthesize stream;
- (void)dealloc;
- (id)initWithStream:(id)arg1 contentLength:(unsigned long long)arg2 fileName:(id)arg3;
- (id)initWithStream:(id)arg1 contentLength:(unsigned long long)arg2;
- (id)init;

@end

