//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIBarButtonItem.h>

@interface UIBarButtonItem (CustomUI)
+ (id)doneItemWithOffset:(struct CGPoint)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)editItemWithOffset:(struct CGPoint)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)itemWithTitle:(id)arg1 font:(id)arg2 offset:(struct CGPoint)arg3 target:(id)arg4 action:(SEL)arg5;
@end

