//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface UIButton (MAUIButton_Extensions)
- (double)maSizeToSuggestedWidth;
- (double)maSizeToSuggestedWidthWithMinWidth:(double)arg1;
- (double)maSuggestedWidth;
- (void)setAssetSet:(id)arg1;
- (void)setAssetSetPath:(id)arg1;
- (void)MAUIButton_Extensions_ParseAssetSet:(id)arg1;
- (void)MAUIButton_Extensions_ParseKey:(id)arg1 withPostfix:(id)arg2 forAssetSet:(id)arg3;
- (unsigned long long)MAUIButton_Extensions_ControlStateForPrefix:(id)arg1;
- (id)MAUIButton_Extensions_KnownPostfixes;
- (id)MAUIButton_Extensions_KnownPrefixes;
- (id)MAUIButton_Extensions_PrefixDictionary;
@end

