//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (CbStepSequencerImages)
+ (id)stepSequencerDeletePatternImage;
+ (id)stepSequencerDiceImage:(unsigned long long)arg1;
+ (id)stepSequencerKitPiecePreviewImage:(_Bool)arg1;
+ (id)stepSequencerCompactEditModeDisclosureImage:(_Bool)arg1;
+ (id)stepSequencerRowHeaderDragHandleImage;
+ (id)stepSequencerProbabilityPatternImage:(id)arg1;
+ (id)stepSequencerPopoverChevronImage:(_Bool)arg1;
+ (id)stepSequencerNextStepModeRandomImage;
+ (id)stepSequencerNextStepModePingPongImage;
+ (id)stepSequencerNextStepModePreviousImage;
+ (id)stepSequencerRowHeaderSoloImage:(_Bool)arg1;
+ (id)stepSequencerRowHeaderMuteImage:(_Bool)arg1;
+ (id)stepSequencerAddRowImage;
+ (id)stepSequencerGlobalMenuImage:(_Bool)arg1;
+ (id)stepSequencerLibraryImage:(_Bool)arg1;
+ (id)stepSequencerPlayImage:(_Bool)arg1;
+ (id)stepSequenceRowIcon:(unsigned long long)arg1;
@end

