//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface ZipWriteStream : NSObject
{
    NSString *_fileNameInZip;
    void *_zipFile;
}

- (void)finishedWriting;
- (void)writeData:(id)arg1;
- (id)initWithZipFileStruct:(void *)arg1 fileNameInZip:(id)arg2;

@end

