@interface CbExportDialogController: UIViewController <CbCheckSongOpenAlertDelegate> 
{
	UIScrollView *_scrollView;
	UIView *_scrollViewContentView;
	UILabel *_sendSongLabelPart1;
	UILabel *_sendSongLabelName;
	UILabel *_sendSongLabelPart2;
	UILabel *_infoLabelLeft;
	UILabel *_infoLabelRight;
	BOOL _cancelled;
	CbLocalPublishers *_publishExporter;
	BOOL _canExportProjectFile;
	int _exportMode;
	UILabel *_infoLabelCenter;
	UILabel *_infoLabelBottom;
	UIButton *_audioFileBtn;
	UIButton *_audioFileImageBtn;
	UIButton *_ringtoneFileBtn;
	UIButton *_ringtoneFileImageBtn;
	UIButton *_projectFileBtn;
	UIButton *_projectFileImageBtn;
	UIView *_audioContainer;
	UIView *_ringtoneContainer;
	UIView *_projectContainer;
	NSURL *_songPathURL;
}

@property (retain, non-atomic) UIScrollView * scrollView;
@property (retain, non-atomic) UIView * scrollViewContentView;
@property (retain, non-atomic) UILabel * sendSongLabelPart1;
@property (retain, non-atomic) UILabel * sendSongLabelPart2;
@property (retain, non-atomic) UILabel * sendSongLabelName;
@property (retain, non-atomic) UILabel * infoLabelLeft;
@property (retain, non-atomic) UILabel * infoLabelCenter;
@property (retain, non-atomic) UILabel * infoLabelRight;
@property (retain, non-atomic) UILabel * infoLabelBottom;
@property (retain, non-atomic) CbLocalPublishers * publishExporter;
@property (non-atomic) int exportMode;
@property (retain, non-atomic) UIButton * audioFileBtn;
@property (retain, non-atomic) UIButton * audioFileImageBtn;
@property (retain, non-atomic) UIButton * ringtoneFileBtn;
@property (retain, non-atomic) UIButton * ringtoneFileImageBtn;
@property (retain, non-atomic) UIButton * projectFileBtn;
@property (retain, non-atomic) UIButton * projectFileImageBtn;
@property (retain, non-atomic) UIView * audioContainer;
@property (retain, non-atomic) UIView * ringtoneContainer;
@property (retain, non-atomic) UIView * projectContainer;
@property (retain, non-atomic) NSURL * songPathURL;
@property (readonly) unsigned long long hash;
@property (readonly) class superclass;
@property (readonly, copy) NSString * description;
@property (readonly, copy) NSString * debugDescription;
@end
 -(void)checkSongOpenAlertDidFinishWithButtonIndex:(long long)arg1 alertInfo:(id)arg2 alertTag:(long long)arg3;
 -(void)setExportMode:(int)arg1;
 -(void)setSongPathURL:(id)arg1;
 -(void)handleInAppPurchaseWillShow:(id)arg1;
 -(id)songPathURL;
 -(id)ringtoneFileImageBtn;
 -(id)ringtoneFileBtn;
 -(id)audioContainer;
 -(id)ringtoneContainer;
 -(id)projectContainer;
 -(id)audioFileBtn;
 -(id)projectFileBtn;
 -(void)mp4Export;
 -(void)mp4ButtonAction:(id)arg1;
 -(void)rgtButtonAction:(id)arg1;
 -(void)cbButtonAction:(id)arg1;
 -(id)scrollViewContentView;
 -(void)setScrollViewContentView:(id)arg1;
 -(id)sendSongLabelPart1;
 -(void)setSendSongLabelPart1:(id)arg1;
 -(id)sendSongLabelPart2;
 -(void)setSendSongLabelPart2:(id)arg1;
 -(id)sendSongLabelName;
 -(void)setSendSongLabelName:(id)arg1;
 -(id)infoLabelLeft;
 -(void)setInfoLabelLeft:(id)arg1;
 -(id)infoLabelCenter;
 -(void)setInfoLabelCenter:(id)arg1;
 -(id)infoLabelRight;
 -(void)setInfoLabelRight:(id)arg1;
 -(id)infoLabelBottom;
 -(void)setInfoLabelBottom:(id)arg1;
 -(id)publishExporter;
 -(void)setPublishExporter:(id)arg1;
 -(int)exportMode;
 -(void)setAudioFileBtn:(id)arg1;
 -(id)audioFileImageBtn;
 -(void)setAudioFileImageBtn:(id)arg1;
 -(void)setRingtoneFileBtn:(id)arg1;
 -(void)setRingtoneFileImageBtn:(id)arg1;
 -(void)setProjectFileBtn:(id)arg1;
 -(id)projectFileImageBtn;
 -(void)setProjectFileImageBtn:(id)arg1;
 -(void)setAudioContainer:(id)arg1;
 -(void)setRingtoneContainer:(id)arg1;
 -(void)setProjectContainer:(id)arg1;
 -(void).cxx_destruct;
 -(void)dealloc;
 -(unsigned long long)supportedInterfaceOrientations;
 -(id)scrollView;
 -(void)setScrollView:(id)arg1;
 -(void)viewDidLoad;
 -(void)viewDidUnload;
 -(void)viewWillAppear:(BOOL)arg1;
 -(void)cleanup;
 -(void)cancelAction:(id)arg1;