//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSLayoutConstraint, UIButton, UITextField;
@protocol _TtP19AudikoRingtonesFree32AddContentViewControllerDelegate_;

@interface _TtC19AudikoRingtonesFree24AddContentViewController : UIViewController
{
    // Error parsing type: , name: textField
    // Error parsing type: , name: textFieldBottomConstraint
    // Error parsing type: , name: continueButton
    // Error parsing type: , name: delegate
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)cancelButtonTapped;
- (void)continueButtonTapped;
- (void)keyboardWillShowWithNotification:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak id <_TtP19AudikoRingtonesFree32AddContentViewControllerDelegate_> delegate; // @synthesize delegate;
@property(nonatomic) __weak UIButton *continueButton; // @synthesize continueButton;
@property(nonatomic) __weak NSLayoutConstraint *textFieldBottomConstraint; // @synthesize textFieldBottomConstraint;
@property(nonatomic) __weak UITextField *textField; // @synthesize textField;

@end

