//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GSDK_PBGeneratedMessage.h"

@class GSDK_PBMutableArray, NSString;

@interface ACPEvent : GSDK_PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int count; // @dynamic count;
@property(nonatomic) _Bool hasCount; // @dynamic hasCount;
@property(nonatomic) _Bool hasName; // @dynamic hasName;
@property(nonatomic) _Bool hasParamsArray; // @dynamic hasParamsArray;
@property(nonatomic) _Bool hasPreviousTimestampMillis; // @dynamic hasPreviousTimestampMillis;
@property(nonatomic) _Bool hasTimestampMillis; // @dynamic hasTimestampMillis;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) GSDK_PBMutableArray *paramsArray; // @dynamic paramsArray;
@property(nonatomic) long long previousTimestampMillis; // @dynamic previousTimestampMillis;
@property(nonatomic) long long timestampMillis; // @dynamic timestampMillis;

@end

