//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIActivity.h>

@class NSString, NSURL;

@interface AUActivity : UIActivity
{
    NSString *_sharingText;
    NSURL *_sharingURL;
}

@property(retain, nonatomic) NSURL *sharingURL; // @synthesize sharingURL=_sharingURL;
@property(retain, nonatomic) NSString *sharingText; // @synthesize sharingText=_sharingText;
- (void).cxx_destruct;
- (_Bool)canPerformWithActivityItems:(id)arg1;

@end

