//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface AUAppTracker : NSObject
{
}

+ (void)trackAudikoSearchSongSelected;
+ (void)trackLibrarySongSelected;
+ (void)trackGD78SongSelected;
+ (void)trackLibraryScreenShown;
+ (void)trackGD78ScreenShown;
+ (void)trackPurchaseAlertShown;
+ (void)trackIOSPurchaseShown;
+ (void)trackIOSPurchaseFailed;
+ (void)trackIOSPurchaseCancel;
+ (void)trackPurchaseSucceed;
+ (void)addGoogleAnalytics;
+ (void)trackDeviceModel;
+ (id)getParametersForLoginMethod:(unsigned long long)arg1;
+ (void)trackRingtoneDownloadSuceed:(_Bool)arg1;
+ (void)trackResumeTrimming;
+ (void)trackPauseTrimming;
+ (void)trackExitTrimming;
+ (void)trackTrimmingDone;
+ (void)trackRestartPlaying;
+ (void)trackSendFeedback;
+ (void)trackRateSkipped;
+ (void)trackRateTapped;
+ (void)trackEmailSignSuccess;
+ (void)trackEmailSign;
+ (void)trackEmailLoginFail;
+ (void)trackEmailLogin;
+ (void)trackFacebookLoginSuccess;
+ (void)trackFacebookLoginFail;
+ (void)trackDeleteRingtone;
+ (void)trackMyRingtonesShow;
+ (void)trackShowTrimmer;
+ (void)trackWallpaperDislike;
+ (void)trackWallpaperDownloadForCategory:(id)arg1;
+ (void)trackWallpaperViewForCategoryName:(id)arg1;
+ (void)trackWallpapersViewForCategoryName:(id)arg1;
+ (void)trackWallpapersCategoriesView;
+ (void)trackForgotPasswordSubmit;
+ (void)trackForgotPasswordClick;
+ (void)trackCollectionRingtonesView;
+ (void)trackCollectionsView;
+ (void)trackShareRingtone;
+ (void)trackOpenAudikoWeb;
+ (void)trackInstructionsView;
+ (void)trackFailedRingtoneCreation;
+ (void)trackSuccessRingtoneCreation;
+ (void)trackCreateRingtoneClick;
+ (void)trackLoginSuccessWithMethod:(unsigned long long)arg1;
+ (void)trackLoginAttemptWithMethod:(unsigned long long)arg1;
+ (void)trackLoginView;
+ (void)trackUploadingRingtoneFailWithReason:(id)arg1;
+ (void)trackSendToMessengerFail;
+ (void)trackSendToMessengerSuccess;
+ (void)trackSendToMessengerClick;
+ (void)trackAddingRingtoneAttempt;
+ (void)trackAppLaunch;
+ (void)initializeAppTracker;

@end

