//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class AVPlayerLayer, FFCircularProgressView, MMMaterialDesignSpinner, UIButton, UIImageView, UILabel, UIView;

@interface AUGiffRingtoneHeaderView : UICollectionReusableView
{
    _Bool _giffPlayingMode;
    _Bool _showSpinner;
    UIImageView *_ringtoneCoverImageView;
    UIButton *_playerControlButton;
    UILabel *_titleLabel;
    UILabel *_artistLabel;
    UIButton *_instructionsButton;
    UIButton *_shareButon;
    UIView *_controlsView;
    UIButton *_screenButton;
    FFCircularProgressView *_circularPlaybackPV;
    MMMaterialDesignSpinner *_spinner;
    UIButton *_sendToMessengerButton;
    UIView *_gradiendView;
    AVPlayerLayer *_moviePlayerLayer;
}

@property(retain, nonatomic) AVPlayerLayer *moviePlayerLayer; // @synthesize moviePlayerLayer=_moviePlayerLayer;
@property(retain, nonatomic) UIView *gradiendView; // @synthesize gradiendView=_gradiendView;
@property(nonatomic) _Bool showSpinner; // @synthesize showSpinner=_showSpinner;
@property(nonatomic) _Bool giffPlayingMode; // @synthesize giffPlayingMode=_giffPlayingMode;
@property(retain, nonatomic) UIButton *sendToMessengerButton; // @synthesize sendToMessengerButton=_sendToMessengerButton;
@property(retain, nonatomic) MMMaterialDesignSpinner *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) FFCircularProgressView *circularPlaybackPV; // @synthesize circularPlaybackPV=_circularPlaybackPV;
@property(nonatomic) __weak UIButton *screenButton; // @synthesize screenButton=_screenButton;
@property(nonatomic) __weak UIView *controlsView; // @synthesize controlsView=_controlsView;
@property(nonatomic) __weak UIButton *shareButon; // @synthesize shareButon=_shareButon;
@property(nonatomic) __weak UIButton *instructionsButton; // @synthesize instructionsButton=_instructionsButton;
@property(nonatomic) __weak UILabel *artistLabel; // @synthesize artistLabel=_artistLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIButton *playerControlButton; // @synthesize playerControlButton=_playerControlButton;
@property(nonatomic) __weak UIImageView *ringtoneCoverImageView; // @synthesize ringtoneCoverImageView=_ringtoneCoverImageView;
- (void).cxx_destruct;
- (void)addGradientView;
- (void)enableControlPanel;
- (void)disableControlPanel;
- (void)hideControlButton:(_Bool)arg1;
- (void)setRingtoneCoverImageFromURL:(id)arg1;
- (void)giffPlayingModeOn;
- (void)setPlayer:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;

@end

