//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface AUMuteModeView : UIView
{
    double _animationDuration;
    UILabel *_textLabel;
}

@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;
- (void).cxx_destruct;
- (void)setText:(id)arg1;
- (void)hide;
- (void)show;
- (void)configureTextWithIconFrame:(struct CGRect)arg1;
- (void)configureIcon;
- (id)initWithFrame:(struct CGRect)arg1;

@end

