//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, NSTimer, UILabel;

@interface AUSinusoidPreloader : UIView
{
    UILabel *_processlabel;
    NSTimer *_animTimer;
    NSMutableArray *_arrayWithSins;
}

@property(retain, nonatomic) NSMutableArray *arrayWithSins; // @synthesize arrayWithSins=_arrayWithSins;
@property(retain, nonatomic) NSTimer *animTimer; // @synthesize animTimer=_animTimer;
@property(retain, nonatomic) UILabel *processlabel; // @synthesize processlabel=_processlabel;
- (void).cxx_destruct;
- (void)hide;
- (void)show;
- (void)hideAnimatedWithTimeInterval:(double)arg1;
- (void)showAnimatedWithTimeInterval:(double)arg1;
- (void)hidePersentsAnimatedWithTimeInterval:(double)arg1;
- (void)setProgress:(int)arg1;
- (void)preparProcessLabel;
- (void)addAnimationToImage:(id)arg1 withStartPoint:(struct CGPoint)arg2 endPoint:(struct CGPoint)arg3 position:(struct CGPoint)arg4 animationDuration:(double)arg5;
- (void)startTimer;
- (void)animateSin;
- (void)addGroupSinsWithPositionY:(float)arg1 velocity:(float)arg2 imageName:(id)arg3;
- (void)prepareSinusoids;
- (id)initWithView:(id)arg1;

@end

