//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FBAdContentContainer.h"

@class FBHTMLAdDataModel, NSString, NSURL, UIWebView;

@interface FBAdWebContentContainer : FBAdContentContainer
{
    _Bool _isJavascriptAdControlInitialized;
    _Bool _isInterstitial;
    UIWebView *_webView;
    NSString *_activationCommand;
    NSURL *_requestURL;
}

@property(nonatomic) _Bool isInterstitial; // @synthesize isInterstitial=_isInterstitial;
@property(copy, nonatomic) NSURL *requestURL; // @synthesize requestURL=_requestURL;
@property(nonatomic) _Bool isJavascriptAdControlInitialized; // @synthesize isJavascriptAdControlInitialized=_isJavascriptAdControlInitialized;
@property(copy, nonatomic) NSString *activationCommand; // @synthesize activationCommand=_activationCommand;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)webViewDidFinishLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (_Bool)logClickWithExtraData:(id)arg1;
- (_Bool)logImpression;
- (void)initializeJavascriptAdControl;
- (_Bool)loadAdMarkup:(id)arg1 activationCommand:(id)arg2;
- (_Bool)loadAdData:(id)arg1 minViewability:(int)arg2;
- (id)getView;
- (void)setFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithAdView:(id)arg1 actualAdSize:(struct CGSize)arg2 adSizeType:(struct FBAdSize)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) FBHTMLAdDataModel *offsiteAd; // @dynamic offsiteAd;
@property(readonly) Class superclass;

@end

