//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSNumber, UIColor, UIFont;

@interface FBNativeAdViewAttributes : NSObject <NSCopying>
{
    _Bool _autoplayEnabled;
    UIColor *_backgroundColor;
    UIColor *_titleColor;
    UIFont *_titleFont;
    UIColor *_descriptionColor;
    UIFont *_descriptionFont;
    UIColor *_buttonColor;
    UIColor *_buttonTitleColor;
    UIFont *_buttonTitleFont;
    UIColor *_buttonBorderColor;
    NSNumber *_bypassAdLoad;
    NSNumber *_skipRegistration;
    NSNumber *_shouldClip;
    NSNumber *_borderRadius;
    NSNumber *_buttonBorderRadius;
    NSNumber *_iconBorderRadius;
    NSNumber *_adChoicesBackgroundShown;
    UIColor *_adChoicesTitleColor;
    UIColor *_starRatingPrimaryColor;
    UIColor *_starRatingSecondaryColor;
    NSNumber *_ratingEnabled;
    NSNumber *_socialContextEnabled;
}

+ (id)internalAttributesForAttributes:(id)arg1;
+ (id)internalAttributesForType:(long long)arg1;
+ (id)defaultAttributesForType:(long long)arg1;
@property(retain, nonatomic) NSNumber *socialContextEnabled; // @synthesize socialContextEnabled=_socialContextEnabled;
@property(retain, nonatomic) NSNumber *ratingEnabled; // @synthesize ratingEnabled=_ratingEnabled;
@property(retain, nonatomic) UIColor *starRatingSecondaryColor; // @synthesize starRatingSecondaryColor=_starRatingSecondaryColor;
@property(retain, nonatomic) UIColor *starRatingPrimaryColor; // @synthesize starRatingPrimaryColor=_starRatingPrimaryColor;
@property(retain, nonatomic) UIColor *adChoicesTitleColor; // @synthesize adChoicesTitleColor=_adChoicesTitleColor;
@property(retain, nonatomic) NSNumber *adChoicesBackgroundShown; // @synthesize adChoicesBackgroundShown=_adChoicesBackgroundShown;
@property(retain, nonatomic) NSNumber *iconBorderRadius; // @synthesize iconBorderRadius=_iconBorderRadius;
@property(retain, nonatomic) NSNumber *buttonBorderRadius; // @synthesize buttonBorderRadius=_buttonBorderRadius;
@property(retain, nonatomic) NSNumber *borderRadius; // @synthesize borderRadius=_borderRadius;
@property(retain, nonatomic) NSNumber *shouldClip; // @synthesize shouldClip=_shouldClip;
@property(retain, nonatomic) NSNumber *skipRegistration; // @synthesize skipRegistration=_skipRegistration;
@property(retain, nonatomic) NSNumber *bypassAdLoad; // @synthesize bypassAdLoad=_bypassAdLoad;
@property(nonatomic, getter=isAutoplayEnabled) _Bool autoplayEnabled; // @synthesize autoplayEnabled=_autoplayEnabled;
@property(copy, nonatomic) UIColor *buttonBorderColor; // @synthesize buttonBorderColor=_buttonBorderColor;
@property(copy, nonatomic) UIFont *buttonTitleFont; // @synthesize buttonTitleFont=_buttonTitleFont;
@property(copy, nonatomic) UIColor *buttonTitleColor; // @synthesize buttonTitleColor=_buttonTitleColor;
@property(copy, nonatomic) UIColor *buttonColor; // @synthesize buttonColor=_buttonColor;
@property(copy, nonatomic) UIFont *descriptionFont; // @synthesize descriptionFont=_descriptionFont;
@property(copy, nonatomic) UIColor *descriptionColor; // @synthesize descriptionColor=_descriptionColor;
@property(copy, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;
@property(copy, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

