//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FBCache, NSURL;
@protocol OS_dispatch_queue;

@interface FBPlaceholderObject : NSObject
{
    NSObject<OS_dispatch_queue> *_underlyingQueue;
    id _key;
    NSURL *_url;
    FBCache *_cache;
    long long _fetchType;
}

@property(nonatomic) long long fetchType; // @synthesize fetchType=_fetchType;
@property(nonatomic) __weak FBCache *cache; // @synthesize cache=_cache;
@property(copy, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) id key; // @synthesize key=_key;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *underlyingQueue; // @synthesize underlyingQueue=_underlyingQueue;
- (void).cxx_destruct;
- (void)dealloc;
- (void)fetchResource;
- (void)addCallback:(CDUnknownBlockType)arg1;
- (id)initWithKey:(id)arg1 withURL:(id)arg2 withFetchType:(long long)arg3 withCache:(id)arg4;

@end

