//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GSDK_PBGeneratedMessage.h"

@class FIR_ICOREErrorInfo, GSDK_PBMutableArray, NSString;

@interface FIR_ICOREICoreConfiguration : GSDK_PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int appCount; // @dynamic appCount;
@property(retain, nonatomic) NSString *appId; // @dynamic appId;
@property(nonatomic) long long buildNumber; // @dynamic buildNumber;
@property(nonatomic) int buildType; // @dynamic buildType;
@property(retain, nonatomic) NSString *bundleId; // @dynamic bundleId;
@property(retain, nonatomic) NSString *clientId; // @dynamic clientId;
@property(nonatomic) int configurationType; // @dynamic configurationType;
@property(retain, nonatomic) NSString *deviceModel; // @dynamic deviceModel;
@property(retain, nonatomic) FIR_ICOREErrorInfo *errorInfo; // @dynamic errorInfo;
@property(nonatomic) _Bool hasAppCount; // @dynamic hasAppCount;
@property(nonatomic) _Bool hasAppId; // @dynamic hasAppId;
@property(nonatomic) _Bool hasBuildNumber; // @dynamic hasBuildNumber;
@property(nonatomic) _Bool hasBuildType; // @dynamic hasBuildType;
@property(nonatomic) _Bool hasBundleId; // @dynamic hasBundleId;
@property(nonatomic) _Bool hasClientId; // @dynamic hasClientId;
@property(nonatomic) _Bool hasConfigurationType; // @dynamic hasConfigurationType;
@property(nonatomic) _Bool hasDeviceModel; // @dynamic hasDeviceModel;
@property(nonatomic) _Bool hasErrorInfo; // @dynamic hasErrorInfo;
@property(nonatomic) _Bool hasIcoreVersion; // @dynamic hasIcoreVersion;
@property(nonatomic) _Bool hasInstall; // @dynamic hasInstall;
@property(nonatomic) _Bool hasItunesId; // @dynamic hasItunesId;
@property(nonatomic) _Bool hasMinSupportedIosVersion; // @dynamic hasMinSupportedIosVersion;
@property(nonatomic) _Bool hasOsVersion; // @dynamic hasOsVersion;
@property(nonatomic) _Bool hasPlistVersion; // @dynamic hasPlistVersion;
@property(nonatomic) _Bool hasPodName; // @dynamic hasPodName;
@property(nonatomic) _Bool hasProjectNumber; // @dynamic hasProjectNumber;
@property(nonatomic) _Bool hasSdkName; // @dynamic hasSdkName;
@property(nonatomic) _Bool hasSdkServiceEnabledArray; // @dynamic hasSdkServiceEnabledArray;
@property(nonatomic) _Bool hasSdkServiceInstalledArray; // @dynamic hasSdkServiceInstalledArray;
@property(nonatomic) _Bool hasSdkVersion; // @dynamic hasSdkVersion;
@property(nonatomic) _Bool hasSubspecErrorInfoArray; // @dynamic hasSubspecErrorInfoArray;
@property(nonatomic) _Bool hasUseDefaultApp; // @dynamic hasUseDefaultApp;
@property(nonatomic) _Bool hasVersionName; // @dynamic hasVersionName;
@property(retain, nonatomic) NSString *icoreVersion; // @dynamic icoreVersion;
@property(retain, nonatomic) NSString *install; // @dynamic install;
@property(retain, nonatomic) NSString *itunesId; // @dynamic itunesId;
@property(retain, nonatomic) NSString *minSupportedIosVersion; // @dynamic minSupportedIosVersion;
@property(retain, nonatomic) NSString *osVersion; // @dynamic osVersion;
@property(retain, nonatomic) NSString *plistVersion; // @dynamic plistVersion;
@property(nonatomic) int podName; // @dynamic podName;
@property(nonatomic) long long projectNumber; // @dynamic projectNumber;
@property(nonatomic) int sdkName; // @dynamic sdkName;
@property(retain, nonatomic) GSDK_PBMutableArray *sdkServiceEnabledArray; // @dynamic sdkServiceEnabledArray;
@property(retain, nonatomic) GSDK_PBMutableArray *sdkServiceInstalledArray; // @dynamic sdkServiceInstalledArray;
@property(retain, nonatomic) NSString *sdkVersion; // @dynamic sdkVersion;
@property(retain, nonatomic) GSDK_PBMutableArray *subspecErrorInfoArray; // @dynamic subspecErrorInfoArray;
@property(nonatomic) _Bool useDefaultApp; // @dynamic useDefaultApp;
@property(retain, nonatomic) NSString *versionName; // @dynamic versionName;

@end

