//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FIROptions, NSString;

@interface GGLConfiguration : NSObject
{
    FIROptions *_options;
}

@property(retain, nonatomic) FIROptions *options; // @synthesize options=_options;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *libraryVersionID;
@property(readonly, nonatomic) _Bool isSignInEnabled;
@property(readonly, nonatomic) _Bool isMeasurementEnabled;
@property(readonly, nonatomic) _Bool isAnalyticsEnabled;
@property(readonly, copy, nonatomic) NSString *googleAppID;
@property(readonly, copy, nonatomic) NSString *trackingID;
@property(readonly, copy, nonatomic) NSString *clientID;
- (id)initWithFIROptions:(id)arg1;

@end

