//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AUSpinnerTableViewController.h"

#import "AUAudikoAppManagerDelegate-Protocol.h"
#import "AUEntityServiceObserver-Protocol.h"
#import "AULoginViewControllerDelegate-Protocol.h"
#import "MPInterstitialAdControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class AUAudikoAppManager, AUAudikoRingtone, AURingtoneEntityService, MPInterstitialAdController, NSString, NoInternetView, UIButton, UIView;

@interface MyRingtonesViewController : AUSpinnerTableViewController <MPInterstitialAdControllerDelegate, UISearchBarDelegate, AUAudikoAppManagerDelegate, AUEntityServiceObserver, AULoginViewControllerDelegate, UITableViewDataSource, UITableViewDelegate, UIGestureRecognizerDelegate>
{
    _Bool _searching;
    _Bool _updaterAlertShown;
    AUAudikoRingtone *_currentPlayingRingtone;
    UIView *_headerForSectionView;
    UIView *_line;
    UIButton *_createRingtoneButton;
    AUAudikoAppManager *_sharedManager;
    MPInterstitialAdController *_adView;
    NoInternetView *_noInternetConnectionView;
}

@property(nonatomic) _Bool updaterAlertShown; // @synthesize updaterAlertShown=_updaterAlertShown;
@property(retain, nonatomic) NoInternetView *noInternetConnectionView; // @synthesize noInternetConnectionView=_noInternetConnectionView;
@property(nonatomic) _Bool searching; // @synthesize searching=_searching;
@property(retain, nonatomic) MPInterstitialAdController *adView; // @synthesize adView=_adView;
@property(retain, nonatomic) AUAudikoAppManager *sharedManager; // @synthesize sharedManager=_sharedManager;
@property(nonatomic) __weak UIButton *createRingtoneButton; // @synthesize createRingtoneButton=_createRingtoneButton;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) UIView *headerForSectionView; // @synthesize headerForSectionView=_headerForSectionView;
@property(retain, nonatomic) AUAudikoRingtone *currentPlayingRingtone; // @synthesize currentPlayingRingtone=_currentPlayingRingtone;
- (void).cxx_destruct;
- (_Bool)hidesBottomBarWhenPushed;
- (void)internetAppearsOffline;
- (void)wifiConnectionAppears;
- (void)internetAppearsOnline;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)interstitialDidLoadAd:(id)arg1;
- (id)viewControllerForPresentingModalView;
- (void)showBannerWithAd;
- (void)loadInterstitial;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)downloadRingtone:(id)arg1;
- (void)showLoginViewController;
- (void)showCreateRingtoneViewController;
- (void)createRingtone:(id)arg1;
- (void)reloadPlayingCell;
- (void)pauseRingtone;
- (void)stopPlayingRingtone;
- (void)resumePlayingRingtone;
- (void)playRingtone;
- (void)startRingtonePlaying;
- (void)play:(id)arg1;
- (void)shareMyRingtone:(id)arg1;
- (void)showUpdateAlert;
- (void)askPushNotificationsPermissions;
- (void)stopObserving;
- (void)startObserving;
- (void)downloadFiles;
- (void)fetchRingtones;
- (void)entitiesListChanged;
- (void)appDidEnterBackground:(id)arg1;
- (void)appWillEnterForeground:(id)arg1;
- (void)appDidBecomeActive:(id)arg1;
- (void)autorizationSkipped;
- (void)authorizationSucceeded;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
@property(readonly, nonatomic) AURingtoneEntityService *ringtoneService;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

