//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSNumber, NSString;

@interface Statistic : NSManagedObject
{
}

- (id)initWithEntity:(id)arg1 insertIntoManagedObjectContext:(id)arg2;
- (id)dictionary;

// Remaining properties
@property(nonatomic, copy) NSString *action; // @dynamic action;
@property(nonatomic, copy) NSString *category; // @dynamic category;
@property(nonatomic, copy) NSString *label; // @dynamic label;
@property(nonatomic, copy) NSString *target; // @dynamic target;
@property(nonatomic, retain) NSNumber *time; // @dynamic time;
@property(nonatomic, retain) NSNumber *value; // @dynamic value;

@end

