//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

#import "_TtP19AudikoRingtonesFree19StickerPackProtocol_-Protocol.h"

@class NSDate, NSNumber, NSOrderedSet, NSString;

@interface StickerPack : NSManagedObject <_TtP19AudikoRingtonesFree19StickerPackProtocol_>
{
}

+ (id)stickerPackFromDict:(id)arg1;
+ (id)packsFromDicts:(id)arg1;
- (id)initWithEntity:(id)arg1 insertIntoManagedObjectContext:(id)arg2;
- (void)updateFromDict:(id)arg1;
- (long long)packType;

// Remaining properties
@property(nonatomic, copy) NSString *artist; // @dynamic artist;
@property(nonatomic, copy) NSString *bannerUrl; // @dynamic bannerUrl;
@property(nonatomic, retain) NSNumber *disabled; // @dynamic disabled;
@property(nonatomic, retain) NSNumber *isNew; // @dynamic isNew;
@property(nonatomic, retain) NSNumber *order; // @dynamic order;
@property(nonatomic, copy) NSString *packDescription; // @dynamic packDescription;
@property(nonatomic, retain) NSNumber *packID; // @dynamic packID;
@property(nonatomic, copy) NSString *packName; // @dynamic packName;
@property(nonatomic, copy) NSString *packTitle; // @dynamic packTitle;
@property(nonatomic, retain) NSNumber *price; // @dynamic price;
@property(nonatomic, copy) NSString *pricePoint; // @dynamic pricePoint;
@property(nonatomic, copy) NSString *productID; // @dynamic productID;
@property(nonatomic, retain) NSOrderedSet *stickers; // @dynamic stickers;
@property(nonatomic, retain) NSDate *updatedAt; // @dynamic updatedAt;

@end

