//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TAGPBGeneratedMessage.h"

@class NSString;

@interface TAGPBUninterpretedOption_NamePart : TAGPBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasIsExtension; // @dynamic hasIsExtension;
@property(nonatomic) _Bool hasNamePart; // @dynamic hasNamePart;
@property(nonatomic) _Bool isExtension; // @dynamic isExtension;
@property(retain, nonatomic) NSString *namePart; // @dynamic namePart;

@end

