#!/bin/bash

echo "Removing leftover files from previous version."
# Try to move plist if exists from old folder if exists

if [ -f "/var/mobile/Library/Application Support/ToneHelper/ToneHelperData.plist" ]
then
	echo "$file found. Moving to new path."
	mv $file /var/mobile/Library/ToneHelper/
	rm -r "/var/mobile/Library/Application Support/ToneHelper/"
fi

echo "Fixing permissions of ToneHelper data files"
# make sure its owned by mobile:mobile
chown -R mobile:mobile /var/mobile/Library/ToneHelper
chmod -R 777 /var/mobile/Library/ToneHelper


exit 0
