//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AUConnection.h"

@class ARUserInfo, NSURLSessionTask;

@interface AUAuthService : AUConnection
{
    ARUserInfo *_userInfo;
    NSURLSessionTask *_authOperation;
    unsigned long long _authorizeAttemptsCount;
}

@property(nonatomic) unsigned long long authorizeAttemptsCount; // @synthesize authorizeAttemptsCount=_authorizeAttemptsCount;
@property(retain, nonatomic) NSURLSessionTask *authOperation; // @synthesize authOperation=_authOperation;
@property(readonly, nonatomic) ARUserInfo *userInfo; // @synthesize userInfo=_userInfo;
- (void).cxx_destruct;
- (void)authenticateWithURLString:(id)arg1 parameters:(id)arg2 requestHandler:(CDUnknownBlockType)arg3;
- (void)sendDeviceTokenToServer;
- (void)cancelAuthentification;
- (void)authenticateWithEmail:(id)arg1 password:(id)arg2 authType:(unsigned long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)authenticateWithToken:(id)arg1 type:(id)arg2 userId:(id)arg3 mail:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)updateCredentialIfExpired:(CDUnknownBlockType)arg1;
- (void)storeDeviceToken:(id)arg1;
- (void)resetPasswordForEmail:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)authorizeAtLaunch:(CDUnknownBlockType)arg1;
- (id)initWithBaseURL:(id)arg1;

@end

