//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AURingtonesTableViewController.h"

@class NSNumber;

@interface AUCollectionRingtonesTableViewController : AURingtonesTableViewController
{
    NSNumber *_collectionID;
}

@property(retain, nonatomic) NSNumber *collectionID; // @synthesize collectionID=_collectionID;
- (void).cxx_destruct;
- (void)loadData;
- (void)viewWillAppear:(_Bool)arg1;

@end

