//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface AUFileManagerService : NSObject
{
}

- (id)pathToTempFolder:(id)arg1;
- (void)clearTempFolder;
- (id)pathToGiffTempFolder;
- (id)pathToVideoTonesTempFolder;
- (_Bool)fileExistAtPath:(id)arg1;
- (_Bool)removeFileAtPath:(id)arg1;

@end

