//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AUNativeAdsCollectionViewController.h"

#import "AUEntityServiceObserver-Protocol.h"
#import "AUWallpaperCategoriesAdapterDelegate-Protocol.h"

@class AUWallpaperCategoriesCollectionViewAdapter, NSString, UIActivityIndicatorView;

@interface AUWallpapersCategoryCollectionViewController : AUNativeAdsCollectionViewController <AUEntityServiceObserver, AUWallpaperCategoriesAdapterDelegate>
{
    AUWallpaperCategoriesCollectionViewAdapter *_adapter;
    UIActivityIndicatorView *_spinner;
}

@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) AUWallpaperCategoriesCollectionViewAdapter *adapter; // @synthesize adapter=_adapter;
- (void).cxx_destruct;
- (void)entitiesListChanged;
- (void)categorySelected:(id)arg1;
- (void)setupMopub;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

