//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CLSAnswersPredefinedEvent.h"

@interface CLSAnswersContentViewEvent : CLSAnswersPredefinedEvent
{
}

- (id)initWithContentName:(id)arg1 contentType:(id)arg2 contentId:(id)arg3 customAttributes:(id)arg4;

@end

