//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FBANJSONSchemaParser, FBAdEnvironmentData, FBAdProviderResponse, NSMutableArray, NSOperationQueue;
@protocol FBAdProviderDelegate;

@interface FBAdProvider : NSObject
{
    _Bool _active;
    id <FBAdProviderDelegate> _delegate;
    FBANJSONSchemaParser *_adParser;
    NSOperationQueue *_parsingQueue;
    NSMutableArray *_requestQueue;
    FBAdEnvironmentData *_environmentData;
    FBAdProviderResponse *_adResponse;
    NSMutableArray *_adSourceRequestQueue;
    long long _adSourceQueries;
    long long _adSourceCompletedQueries;
}

@property(nonatomic) long long adSourceCompletedQueries; // @synthesize adSourceCompletedQueries=_adSourceCompletedQueries;
@property(nonatomic) long long adSourceQueries; // @synthesize adSourceQueries=_adSourceQueries;
@property(retain, nonatomic) NSMutableArray *adSourceRequestQueue; // @synthesize adSourceRequestQueue=_adSourceRequestQueue;
@property(retain, nonatomic) FBAdProviderResponse *adResponse; // @synthesize adResponse=_adResponse;
@property(retain, nonatomic) FBAdEnvironmentData *environmentData; // @synthesize environmentData=_environmentData;
@property(retain, nonatomic) NSMutableArray *requestQueue; // @synthesize requestQueue=_requestQueue;
@property(retain, nonatomic) NSOperationQueue *parsingQueue; // @synthesize parsingQueue=_parsingQueue;
@property(retain, nonatomic) FBANJSONSchemaParser *adParser; // @synthesize adParser=_adParser;
@property(nonatomic) _Bool active; // @synthesize active=_active;
@property(nonatomic) __weak id <FBAdProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)parseResponseFromData:(id)arg1 canReturnSources:(_Bool)arg2;
- (void)handleAdResponse:(id)arg1 data:(id)arg2 error:(id)arg3 canReturnSources:(_Bool)arg4 deliveryUrl:(id)arg5;
- (void)makeFirstAdRequestWithParameters:(id)arg1;
- (void)dispatchError:(id)arg1;
- (void)destroy;
- (void)cancel;
- (void)getAdWithEnvironmentData:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

