//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBAdView, NSError, UIViewController;

@protocol FBAdViewDelegate <NSObject>

@optional
- (UIViewController *)viewControllerForPresentingModalView;
- (void)adViewWillLogImpression:(FBAdView *)arg1;
- (void)adView:(FBAdView *)arg1 didFailWithError:(NSError *)arg2;
- (void)adViewDidLoad:(FBAdView *)arg1;
- (void)adViewDidFinishHandlingClick:(FBAdView *)arg1;
- (void)adViewDidClick:(FBAdView *)arg1;
@end

