//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBAdProviderDelegate-Protocol.h"
#import "FBAdViewabilityValidatorDelegate-Protocol.h"
#import "FBDisplayAdAdapterDelegate-Protocol.h"

@class FBAdCandidate, FBAdEnvironmentData, FBAdPlacementDefinition, FBAdProvider, FBAdViewabilityValidator, FBDisplayAdAdapter, FBTimer, NSArray, NSString;
@protocol FBDisplayAdControllerDelegate;

@interface FBDisplayAdController : NSObject <FBDisplayAdAdapterDelegate, FBAdProviderDelegate, FBAdViewabilityValidatorDelegate>
{
    _Bool _flexibleAdSize;
    _Bool _initialized;
    _Bool _loaded;
    _Bool _started;
    _Bool _adapterHadImpression;
    _Bool _controllerHadImpression;
    id <FBDisplayAdControllerDelegate> _delegate;
    FBAdProvider *_adProvider;
    FBAdEnvironmentData *_environment;
    FBDisplayAdAdapter *_currentAdapter;
    long long _currentAdMinViewabilityPercentage;
    FBAdViewabilityValidator *_currentViewabilityValidator;
    FBAdPlacementDefinition *_currentPlacementDefinition;
    FBAdCandidate *_currentAdCandidate;
    FBDisplayAdAdapter *_nextAdapter;
    FBTimer *_nextAdapterTimeoutTimer;
    NSString *_nextAdapterName;
    long long _adapterInitTimeoutInterval;
    NSArray *_nextAdsData;
    long long _nextAdsDataCurrentPos;
    long long _nextAdMinViewabilityPercentage;
    long long _placementType;
    NSString *_placementID;
    long long _refreshInterval;
    FBTimer *_refreshTimer;
    long long _retryCount;
    struct FBAdSize _adSizeType;
    struct CGSize _actualAdSize;
}

@property(nonatomic) long long retryCount; // @synthesize retryCount=_retryCount;
@property(retain, nonatomic) FBTimer *refreshTimer; // @synthesize refreshTimer=_refreshTimer;
@property(nonatomic) long long refreshInterval; // @synthesize refreshInterval=_refreshInterval;
@property(copy, nonatomic) NSString *placementID; // @synthesize placementID=_placementID;
@property(nonatomic) long long placementType; // @synthesize placementType=_placementType;
@property(nonatomic) _Bool controllerHadImpression; // @synthesize controllerHadImpression=_controllerHadImpression;
@property(nonatomic) _Bool adapterHadImpression; // @synthesize adapterHadImpression=_adapterHadImpression;
@property(nonatomic) _Bool started; // @synthesize started=_started;
@property(nonatomic) _Bool loaded; // @synthesize loaded=_loaded;
@property(nonatomic) _Bool initialized; // @synthesize initialized=_initialized;
@property(nonatomic, getter=isFlexibleAdSize) _Bool flexibleAdSize; // @synthesize flexibleAdSize=_flexibleAdSize;
@property(nonatomic) struct CGSize actualAdSize; // @synthesize actualAdSize=_actualAdSize;
@property(nonatomic) struct FBAdSize adSizeType; // @synthesize adSizeType=_adSizeType;
@property(nonatomic) long long nextAdMinViewabilityPercentage; // @synthesize nextAdMinViewabilityPercentage=_nextAdMinViewabilityPercentage;
@property(nonatomic) long long nextAdsDataCurrentPos; // @synthesize nextAdsDataCurrentPos=_nextAdsDataCurrentPos;
@property(retain, nonatomic) NSArray *nextAdsData; // @synthesize nextAdsData=_nextAdsData;
@property(nonatomic) long long adapterInitTimeoutInterval; // @synthesize adapterInitTimeoutInterval=_adapterInitTimeoutInterval;
@property(retain, nonatomic) NSString *nextAdapterName; // @synthesize nextAdapterName=_nextAdapterName;
@property(retain, nonatomic) FBTimer *nextAdapterTimeoutTimer; // @synthesize nextAdapterTimeoutTimer=_nextAdapterTimeoutTimer;
@property(retain, nonatomic) FBDisplayAdAdapter *nextAdapter; // @synthesize nextAdapter=_nextAdapter;
@property(retain, nonatomic) FBAdCandidate *currentAdCandidate; // @synthesize currentAdCandidate=_currentAdCandidate;
@property(retain, nonatomic) FBAdPlacementDefinition *currentPlacementDefinition; // @synthesize currentPlacementDefinition=_currentPlacementDefinition;
@property(retain, nonatomic) FBAdViewabilityValidator *currentViewabilityValidator; // @synthesize currentViewabilityValidator=_currentViewabilityValidator;
@property(nonatomic) long long currentAdMinViewabilityPercentage; // @synthesize currentAdMinViewabilityPercentage=_currentAdMinViewabilityPercentage;
@property(retain, nonatomic) FBDisplayAdAdapter *currentAdapter; // @synthesize currentAdapter=_currentAdapter;
@property(retain, nonatomic) FBAdEnvironmentData *environment; // @synthesize environment=_environment;
@property(retain, nonatomic) FBAdProvider *adProvider; // @synthesize adProvider=_adProvider;
@property(nonatomic) __weak id <FBDisplayAdControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)viewDidAppearOnScreen;
- (_Bool)tryNextAdFromList;
- (void)onAdRequestSuccess:(id)arg1;
- (void)onAdRequestError:(id)arg1;
- (void)invalidateCurrentAd;
- (void)invalidateInProgressAd;
- (void)setInitialAdViewSize:(struct FBAdSize)arg1;
- (void)loadAd;
- (void)initialLoadAd;
- (void)stopObservingNotifications;
- (void)onApplicationForegrounded;
- (void)onApplicationBackgrounded;
- (void)startObservingNotifications;
- (void)scheduleTimeout;
- (void)invalidateTimeoutTimer;
- (void)updateRefreshInterval:(long long)arg1;
- (void)scheduleRefreshIn:(long long)arg1;
- (void)scheduleRefresh;
- (void)invalidateRefreshTimer;
- (void)adapter:(id)arg1 didFailWithError:(id)arg2;
- (void)adapterDidLoad:(id)arg1;
- (void)disableViewabilityValidator;
- (void)ensureViewabilityValidator;
- (void)adapterWillLogImpression:(id)arg1;
- (void)adapterDidUnload:(id)arg1;
- (void)adapterWillUnload:(id)arg1;
- (void)adapterDidFinishHandlingClick:(id)arg1;
- (void)adapterDidClick:(id)arg1 url:(id)arg2 playerHandles:(_Bool)arg3;
- (void)notifyOnAdUserClose;
- (void)notifyOnAdClickThruWithURL:(id)arg1 playerHandles:(_Bool)arg2;
- (void)notifyOnAdError:(id)arg1;
- (void)notifyOnAdStopped;
- (void)notifyOnAdImpression;
- (void)notifyOnAdViewPresented;
- (void)notifyOnAdLoaded;
- (void)logImpressionFrom:(long long)arg1;
@property(readonly, nonatomic) long long minViewabilityPercentage;
- (void)disableAutoRefresh;
- (void)retry;
- (void)refresh;
- (_Bool)startAdFromRootViewController:(id)arg1;
- (void)startAd;
- (void)checkInitialization;
- (void)dealloc;
- (void)initAdWithPlacementId:(id)arg1 placementType:(long long)arg2 withAdSize:(struct FBAdSize)arg3 withAdType:(long long)arg4 adProvider:(id)arg5;
- (void)initAdWithPlacementId:(id)arg1 placementType:(long long)arg2 withAdSize:(struct FBAdSize)arg3 adProvider:(id)arg4;
- (void)initAdWithPlacementId:(id)arg1 placementType:(long long)arg2 withAdSize:(struct FBAdSize)arg3;
- (void)initAdWithPlacementId:(id)arg1 placementType:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

