//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FBSDKMessengerContext, NSString, NSURL;

@interface FBSDKMessengerShareOptions : NSObject
{
    NSString *_metadata;
    NSURL *_sourceURL;
    FBSDKMessengerContext *_contextOverride;
}

@property(retain, nonatomic) FBSDKMessengerContext *contextOverride; // @synthesize contextOverride=_contextOverride;
@property(copy, nonatomic) NSURL *sourceURL; // @synthesize sourceURL=_sourceURL;
@property(copy, nonatomic) NSString *metadata; // @synthesize metadata=_metadata;
- (void).cxx_destruct;

@end

