//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ParseUtil : NSObject
{
}

+ (void)addAppVersion:(id)arg1;
+ (void)addEmail:(id)arg1;
+ (void)addCountry:(id)arg1;
+ (void)handlePush:(id)arg1;
+ (void)addChannelWithName:(id)arg1;
+ (void)setDeviceTokenFromData:(id)arg1;
+ (void)setDeviceToken:(id)arg1;
+ (id)currentDeviceToken;
+ (void)addParseWithLaunchOptions:(id)arg1;

@end

