//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIBarButtonItem.h>

@interface _TtC9Ringtones14SaveButtonItem : UIBarButtonItem
{
    // Error parsing type: , name: activityIndicator
    // Error parsing type: , name: imageView
    // Error parsing type: , name: enabledColor
    // Error parsing type: , name: disabledColor
    // Error parsing type: , name: state
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

