//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC9Ringtones11AudioPlayer : NSObject
{
    // Error parsing type: , name: currentPosition
    // Error parsing type: , name: audioStreamDescription
    // Error parsing type: , name: audioQueueTapRef
    // Error parsing type: , name: queueIsPlaying
    // Error parsing type: , name: outputQueue
    // Error parsing type: , name: started
    // Error parsing type: , name: stopping
    // Error parsing type: , name: playerQueue
    // Error parsing type: , name: queueSemaphore
    // Error parsing type: , name: audioDataReader
    // Error parsing type: , name: state
    // Error parsing type: , name: delegate
}

+ (void)setSharedPlayer:(id)arg1;
+ (id)sharedPlayer;
- (CDUnknownBlockType).cxx_destruct;
- (void)stop:(_Bool)arg1;
- (id)init;

@end

