//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC9Ringtones21MainTabbedCoordinator.h"

@interface _TtC9Ringtones20RingtonesCoordinator : _TtC9Ringtones21MainTabbedCoordinator
{
    // Error parsing type: , name: ringtoneConfig
    // Error parsing type: , name: presentingModal
    // Error parsing type: , name: deepLinkAction
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithTabBarController:(id)arg1;

@end

