//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC9Ringtones23SearchHistoryDataSource.h"

#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@interface _TtC9Ringtones23SearchHistoryDataSource (Ringtones3) <UICollectionViewDelegateFlowLayout>
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
@end

