//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC9Ringtones24SavedRingtonesDataSource : SwiftObject
{
    // Error parsing type: , name: onItemsLoaded
    // Error parsing type: , name: dataUpdated
    // Error parsing type: , name: initialItems
    // Error parsing type: , name: insertedData
    // Error parsing type: , name: savedRingtones
    // Error parsing type: , name: ringtoneFacade
}

@end

