//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC9Ringtones34InteractivePopNavigationController.h"

#import "UINavigationControllerDelegate-Protocol.h"

@interface _TtC9Ringtones34InteractivePopNavigationController (Ringtones1) <UINavigationControllerDelegate>
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;
@end

