//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface _TtC9Ringtones24FeedbackCellGradientView : UIView
{
    // Error parsing type: , name: startColor
    // Error parsing type: , name: endColor
}

+ (Class)layerClass;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(nonatomic, retain) UIColor *endColor; // @synthesize endColor;
@property(nonatomic, retain) UIColor *startColor; // @synthesize startColor;

@end

