//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC9Ringtones10ImageCache : SwiftObject
{
    // Error parsing type: , name: preferredMemoryCapacity
    // Error parsing type: , name: memoryCapacity
    // Error parsing type: , name: images
    // Error parsing type: , name: actualMemoryUsage
    // Error parsing type: , name: dispatchQueue
}

- (void)clearMemory;

@end

