//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FBAdSettings : NSObject
{
}

+ (void)setTestAdType:(long long)arg1;
+ (long long)testAdType;
+ (void)setMediaViewRenderingMethod:(long long)arg1;
+ (long long)mediaViewRenderingMethod;
+ (void)resetSessionID;
+ (id)sessionID;
+ (void)setLogLevel:(long long)arg1;
+ (long long)getLogLevel;
+ (id)getBaseURL;
+ (id)getBaseURLWithDefault:(id)arg1 withFormat:(id)arg2;
+ (id)getWebviewBaseURL;
+ (id)getDeliveryEndpoint;
+ (void)setUrlPrefix:(id)arg1;
+ (id)urlPrefix;
+ (id)getMediationService;
+ (void)setMediationService:(id)arg1;
+ (_Bool)isChildDirected;
+ (_Bool)isTestMode;
+ (void)setIsChildDirected:(_Bool)arg1;
+ (void)clearTestDevice:(id)arg1;
+ (void)clearTestDevices;
+ (void)addTestDevices:(id)arg1;
+ (void)addTestDevice:(id)arg1;
+ (void)persistTestDevices;
+ (id)testDevices;
+ (id)testDeviceHash;

@end

