//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBAdVideoView;

@protocol FBAdVideoViewDelegate <NSObject>
- (_Bool)isBeingDismissed;
- (_Bool)isBeingPresented;
- (void)videoViewDidChangeVolume:(FBAdVideoView *)arg1;
- (void)videoView:(FBAdVideoView *)arg1 didEnd:(CDStruct_1b6d18a9)arg2;
- (void)videoView:(FBAdVideoView *)arg1 didStopSeek:(CDStruct_1b6d18a9)arg2;
- (void)videoView:(FBAdVideoView *)arg1 didStartSeek:(CDStruct_1b6d18a9)arg2;
- (void)videoView:(FBAdVideoView *)arg1 didProgress:(CDStruct_1b6d18a9)arg2;
- (void)videoView:(FBAdVideoView *)arg1 didResume:(CDStruct_1b6d18a9)arg2;
- (void)videoView:(FBAdVideoView *)arg1 didPause:(CDStruct_1b6d18a9)arg2;
- (void)videoViewTapped:(FBAdVideoView *)arg1;
- (void)videoViewDidLoad:(FBAdVideoView *)arg1;
@end

