//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface FBInterstitialAdInternal : UIViewController
{
}

- (_Bool)showAdFromRootViewController:(id)arg1;
- (void)loadAd;
- (_Bool)showAdFromRootViewController:(id)arg1 animated:(_Bool)arg2;
- (void)loadAdFromMarkup:(id)arg1 activationCommand:(id)arg2 orientation:(long long)arg3;
- (id)initWithPlacementID:(id)arg1 adData:(id)arg2 minViewability:(int)arg3;
- (_Bool)isAdValid;

@end

