//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBAdViewabilityValidatorDelegate-Protocol.h"
#import "FBDisplayAdControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class FBAdImage, FBAdPlacementDefinition, FBAdProvider, FBAdViewabilityValidator, FBDisplayAdController, FBNativeAdDataModel, FBNativeAdViewAttributes, NSArray, NSDate, NSDictionary, NSHashTable, NSNumber, NSString, NSURL, UIView, UIViewController;
@protocol FBNativeAdDelegate;

@interface FBNativeAd : NSObject <FBDisplayAdControllerDelegate, FBAdViewabilityValidatorDelegate, UIGestureRecognizerDelegate>
{
    _Bool _hasCalledLoadAd;
    _Bool _isHScroll;
    _Bool _usedByMediaView;
    _Bool _viewabilityValidatorDisabled;
    _Bool _bypassValidation;
    NSString *_placementID;
    long long _mediaCachePolicy;
    id <FBNativeAdDelegate> _delegate;
    FBDisplayAdController *_adController;
    FBAdProvider *_adProvider;
    NSDictionary *_mediaViewConfiguration;
    FBAdViewabilityValidator *_viewabilityValidator;
    NSHashTable *_gestureRecognizers;
    FBAdPlacementDefinition *_placementDefinition;
    UIViewController *_viewController;
    NSDate *_loadAdStartTime;
    FBNativeAdDataModel *_dataModel;
    FBAdImage *_adChoicesIcon;
    NSURL *_adChoicesLinkURL;
    NSString *_adChoicesText;
    FBNativeAdViewAttributes *_adViewAttributes;
    UIView *_nativeAdView;
    NSHashTable *_clickableViews;
    double _firstImpressionTime;
    NSString *_lastTouchData;
    CDUnknownBlockType _onImpression;
    CDUnknownBlockType _onClick;
}

+ (id)fakeNativeAd;
+ (void)unregisterOutstandingRequest:(id)arg1;
+ (void)registerOutstandingRequest:(id)arg1;
+ (id)requests;
+ (id)viewToNativeAdMap;
@property(copy, nonatomic) CDUnknownBlockType onClick; // @synthesize onClick=_onClick;
@property(copy, nonatomic) CDUnknownBlockType onImpression; // @synthesize onImpression=_onImpression;
@property(copy, nonatomic) NSString *lastTouchData; // @synthesize lastTouchData=_lastTouchData;
@property(nonatomic) double firstImpressionTime; // @synthesize firstImpressionTime=_firstImpressionTime;
@property(nonatomic, getter=shouldBypassValidation) _Bool bypassValidation; // @synthesize bypassValidation=_bypassValidation;
@property(nonatomic) _Bool viewabilityValidatorDisabled; // @synthesize viewabilityValidatorDisabled=_viewabilityValidatorDisabled;
@property(retain, nonatomic) NSHashTable *clickableViews; // @synthesize clickableViews=_clickableViews;
@property(nonatomic) __weak UIView *nativeAdView; // @synthesize nativeAdView=_nativeAdView;
@property(retain, nonatomic) FBNativeAdViewAttributes *adViewAttributes; // @synthesize adViewAttributes=_adViewAttributes;
@property(copy, nonatomic) NSString *adChoicesText; // @synthesize adChoicesText=_adChoicesText;
@property(copy, nonatomic) NSURL *adChoicesLinkURL; // @synthesize adChoicesLinkURL=_adChoicesLinkURL;
@property(retain, nonatomic) FBAdImage *adChoicesIcon; // @synthesize adChoicesIcon=_adChoicesIcon;
@property(retain, nonatomic) FBNativeAdDataModel *dataModel; // @synthesize dataModel=_dataModel;
@property(retain, nonatomic) NSDate *loadAdStartTime; // @synthesize loadAdStartTime=_loadAdStartTime;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) FBAdPlacementDefinition *placementDefinition; // @synthesize placementDefinition=_placementDefinition;
@property(retain, nonatomic) NSHashTable *gestureRecognizers; // @synthesize gestureRecognizers=_gestureRecognizers;
@property(retain, nonatomic) FBAdViewabilityValidator *viewabilityValidator; // @synthesize viewabilityValidator=_viewabilityValidator;
@property(copy, nonatomic) NSDictionary *mediaViewConfiguration; // @synthesize mediaViewConfiguration=_mediaViewConfiguration;
@property(nonatomic) _Bool usedByMediaView; // @synthesize usedByMediaView=_usedByMediaView;
@property(nonatomic) _Bool isHScroll; // @synthesize isHScroll=_isHScroll;
@property(nonatomic) _Bool hasCalledLoadAd; // @synthesize hasCalledLoadAd=_hasCalledLoadAd;
@property(retain, nonatomic) FBAdProvider *adProvider; // @synthesize adProvider=_adProvider;
@property(retain, nonatomic) FBDisplayAdController *adController; // @synthesize adController=_adController;
@property(nonatomic) __weak id <FBNativeAdDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long mediaCachePolicy; // @synthesize mediaCachePolicy=_mediaCachePolicy;
@property(copy, nonatomic) NSString *placementID; // @synthesize placementID=_placementID;
- (void).cxx_destruct;
- (_Bool)viewabilityValidator:(id)arg1 checkedWithStatus:(long long)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
@property(readonly, copy, nonatomic) NSString *body;
@property(readonly, nonatomic) FBAdImage *coverImage;
@property(readonly, nonatomic) FBAdImage *icon;
@property(readonly, copy, nonatomic) NSString *callToAction;
@property(readonly, copy, nonatomic) NSString *socialContext;
@property(readonly, copy, nonatomic) NSString *subtitle;
@property(readonly, copy, nonatomic) NSString *title;
@property(readonly, nonatomic) struct FBAdStarRating starRating;
- (id)generateTapLoggingWithLocation:(struct CGPoint)arg1 inRect:(struct CGRect)arg2;
- (void)handleTap:(id)arg1 withEvent:(id)arg2;
- (void)handleTap:(id)arg1;
- (void)detachTapGestureRecognizers;
- (id)generateViewSnapshotData;
- (id)generateViewSnapshot;
- (id)loggingDataForView:(id)arg1 withSubviews:(_Bool)arg2;
- (id)generateLoggingWithView:(id)arg1 withClickableViews:(id)arg2;
- (id)generateViewLogging;
- (id)generateViewPostData;
- (id)generateLoggingDataWithExtraData:(id)arg1;
- (id)generateLoggingData;
- (void)unregisterViewInternal;
- (void)unregisterView;
- (_Bool)isRegistered;
- (void)registerViewForInteraction:(id)arg1 withViewController:(id)arg2 withClickableViews:(id)arg3;
- (void)registerViewForInteraction:(id)arg1 withViewController:(id)arg2;
@property(readonly, copy, nonatomic, getter=getAdNetwork) NSString *adNetwork;
@property(readonly, nonatomic, getter=isAdValid) _Bool adValid;
- (void)disableViewabilityValidator;
- (void)displayAdController:(id)arg1 didFailWithError:(id)arg2;
- (void)displayAdControllerUserClosed:(id)arg1;
- (void)displayAdController:(id)arg1 clickThruWithURL:(id)arg2;
- (void)displayAdControllerImpression:(id)arg1;
- (void)displayAdControllerStopped:(id)arg1;
- (void)displayAdController:(id)arg1 presentedData:(id)arg2 onImpression:(CDUnknownBlockType)arg3 onClick:(CDUnknownBlockType)arg4;
- (void)displayAdControllerLoaded:(id)arg1;
- (void)populateFromDataModel:(id)arg1 placementDefinition:(id)arg2 onImpression:(CDUnknownBlockType)arg3 onClick:(CDUnknownBlockType)arg4;
- (void)loadAdInternal;
- (void)loadAd;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithPlacementID:(id)arg1 adProvider:(id)arg2;
- (id)initWithPlacementID:(id)arg1;
- (id)init;
@property(readonly, copy, nonatomic) NSNumber *autoPlayEnabled;
@property(readonly, copy, nonatomic) NSURL *videoURL;
@property(readonly, nonatomic, getter=isVideoSupported) _Bool videoSupported;
@property(readonly, copy, nonatomic) NSArray *multiProductAdContent;
@property(readonly, nonatomic, getter=isMultiProductSupported) _Bool multiProductSupported;
- (id)getExternalLoggingExtraDataWithSource:(id)arg1;
- (void)handleExternalClickWithViewController:(id)arg1 fromSource:(id)arg2;
- (void)logExternalImpressionFromSource:(id)arg1;
- (void)checkManualLoggingEligibility;
- (id)getManualLoggingExtraData;
- (void)handleClickWithViewController:(id)arg1;
- (void)logImpression;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

