//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBRewardedVideoAdVideoInternal, NSError;

@protocol FBRewardedVideoAdVideoInternalDelegate <NSObject>
- (void)rewardedVideoAdVideoWillClose:(FBRewardedVideoAdVideoInternal *)arg1;
- (void)rewardedVideoAdVideoWillLogImpression:(FBRewardedVideoAdVideoInternal *)arg1;
- (void)rewardedVideoAdVideoComplete:(FBRewardedVideoAdVideoInternal *)arg1;
- (void)rewardedVideoAdVideo:(FBRewardedVideoAdVideoInternal *)arg1 didFailWithError:(NSError *)arg2;
- (void)rewardedVideoAdVideoDidLoad:(FBRewardedVideoAdVideoInternal *)arg1;
@end

