//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSProxy.h>

@interface FIRAAppDelegateProxy : NSProxy
{
}

+ (void)notifyInterceptorsWithMethodSelector:(SEL)arg1 callback:(CDUnknownBlockType)arg2;
+ (_Bool)isAppDelegateProxyEnabled;
+ (CDUnknownFunctionPointerType)implementationOfMethodSelector:(SEL)arg1 fromClass:(Class)arg2;
+ (void)addInstanceMethodWithDestinationSelector:(SEL)arg1 withImplementationFromSourceSelector:(SEL)arg2 fromClass:(Class)arg3 toClass:(Class)arg4;
+ (void)addInstanceMethodWithSelector:(SEL)arg1 fromClass:(Class)arg2 toClass:(Class)arg3;
+ (void)createSubclassWithObject:(id)arg1;
+ (void)proxyOriginalDelegate:(id)arg1;
+ (void)fulfillRequiredMethodsForAppDelegateClass:(Class)arg1;
+ (void)load;
+ (id)interceptors;
+ (void)unregisterAppDelegateInterceptorWithID:(id)arg1;
+ (id)registerAppDelegateInterceptor:(id)arg1;
- (_Bool)defaultApplication:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (void)defaultApplication:(id)arg1 handleEventsForBackgroundURLSession:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)defaultApplication:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 handleEventsForBackgroundURLSession:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (id)fakeDescription;

@end

