//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol FIRNetworkLoggerDelegate, FIRReachabilityDelegate;

@interface FIRReachabilityChecker : NSObject
{
    int reachabilityStatus_;
    const struct FIRReachabilityApi *reachabilityApi_;
    struct __SCNetworkReachability *reachability_;
    NSString *host_;
    id <FIRReachabilityDelegate> reachabilityDelegate_;
    id <FIRNetworkLoggerDelegate> loggerDelegate_;
}

@property(nonatomic) __weak id <FIRNetworkLoggerDelegate> loggerDelegate; // @synthesize loggerDelegate=loggerDelegate_;
@property(nonatomic) __weak id <FIRReachabilityDelegate> reachabilityDelegate; // @synthesize reachabilityDelegate=reachabilityDelegate_;
@property(copy, nonatomic) NSString *host; // @synthesize host=host_;
@property(nonatomic) int reachabilityStatus; // @synthesize reachabilityStatus=reachabilityStatus_;
@property(nonatomic) struct __SCNetworkReachability *reachability; // @synthesize reachability=reachability_;
- (void).cxx_destruct;
- (void)reachabilityFlagsChanged:(unsigned int)arg1;
- (int)statusForFlags:(unsigned int)arg1;
- (void)stop;
- (_Bool)start;
- (void)dealloc;
- (id)initWithReachabilityDelegate:(id)arg1 loggerDelegate:(id)arg2 withHost:(id)arg3;
@property(readonly, nonatomic) _Bool isActive;
@property(nonatomic) const struct FIRReachabilityApi *reachabilityApi; // @synthesize reachabilityApi=reachabilityApi_;

@end

