//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDecimalNumber, NSString;

@interface GADAdReward : NSObject
{
    NSString *_type;
    NSDecimalNumber *_amount;
}

@property(readonly, copy, nonatomic) NSDecimalNumber *amount; // @synthesize amount=_amount;
@property(readonly, copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)initWithRewardType:(id)arg1 rewardAmount:(id)arg2;
- (id)initWithRewardDictionary:(id)arg1;
- (id)init;

@end

