//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol GADAdViewActiveViewMonitoring;

@interface GADAdViewActiveViewReporter : NSObject
{
    _Bool _reporting;
    id <GADAdViewActiveViewMonitoring> _observer;
}

@property(readonly, nonatomic) _Bool reporting; // @synthesize reporting=_reporting;
@property(nonatomic) __weak id <GADAdViewActiveViewMonitoring> observer; // @synthesize observer=_observer;
- (void).cxx_destruct;
- (void)dealloc;
- (void)stop;
- (void)start;

@end

