//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface GADAutoClickProtection : NSObject
{
    NSArray *_reportingURLStringTemplates;
    _Bool _enabled;
}

@property(readonly, nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
- (void).cxx_destruct;
- (void)reportSpamOpenActionWithNavigationURLString:(id)arg1;
- (void)reportSpamOpenActionWithAdDebugDialogString:(id)arg1 navigationURLString:(id)arg2;
- (id)initWithDictionary:(id)arg1;
- (id)initWithAutoClickProtectionEnabled:(_Bool)arg1;

@end

