//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GADAdMediationDelegate-Protocol.h"
#import "GADSlotAdEventDelegate-Protocol.h"
#import "GADSlotAdKeyDelegate-Protocol.h"
#import "GADSlotAdLoadDelegate-Protocol.h"
#import "GADSlotAdResponseDelegate-Protocol.h"
#import "GADSlotDelegate-Protocol.h"

@class GADAdConfiguration, GADAdExposureMonitor, GADAdView, GADBufferedClearcutLogger, GADClearcutLogger, GADSlot, GADVideoController, NSDictionary, NSObject, NSString, UIViewController;
@protocol GADAdSizeDelegate, GADBannerViewDelegate, GADInAppPurchaseDelegate, OS_dispatch_queue;

@interface GADBannerView : UIView <GADAdMediationDelegate, GADSlotAdEventDelegate, GADSlotAdLoadDelegate, GADSlotDelegate, GADSlotAdKeyDelegate, GADSlotAdResponseDelegate>
{
    _Bool _hasLoadedAd;
    _Bool _hasInitialized;
    _Bool _isMediated;
    NSDictionary *_viewHierarchy;
    NSObject<OS_dispatch_queue> *_lockQueue;
    _Bool _setAdSizeAndReloadWasCalled;
    GADClearcutLogger *_logger;
    GADBufferedClearcutLogger *_bufferedLogger;
    GADAdExposureMonitor *_adExposureMonitor;
    GADAdConfiguration *_adConfiguration;
    NSString *_adUnitID;
    NSDictionary *_bannerKey;
    _Bool _autoloadEnabled;
    UIViewController *_rootViewController;
    id <GADBannerViewDelegate> _delegate;
    id <GADInAppPurchaseDelegate> _inAppPurchaseDelegate;
    id <GADAdSizeDelegate> _adSizeDelegate;
    GADVideoController *_videoController;
    UIView *_rootAdView;
    GADSlot *_slot;
}

@property(retain, nonatomic) GADSlot *slot; // @synthesize slot=_slot;
@property(retain, nonatomic) UIView *rootAdView; // @synthesize rootAdView=_rootAdView;
@property(readonly, nonatomic) GADVideoController *videoController; // @synthesize videoController=_videoController;
@property(nonatomic, getter=isAutoloadEnabled) _Bool autoloadEnabled; // @synthesize autoloadEnabled=_autoloadEnabled;
@property(nonatomic) __weak id <GADAdSizeDelegate> adSizeDelegate; // @synthesize adSizeDelegate=_adSizeDelegate;
@property(nonatomic) __weak id <GADInAppPurchaseDelegate> inAppPurchaseDelegate; // @synthesize inAppPurchaseDelegate=_inAppPurchaseDelegate;
@property(nonatomic) __weak id <GADBannerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
- (void).cxx_destruct;
- (id)videoOptions;
- (void)processAdOptions;
- (void)resetVideoController;
- (id)mediationConnectorForConfiguration:(id)arg1 networkConfiguration:(id)arg2;
- (void)slot:(id)arg1 willProcessMediatedAdResponse:(id)arg2;
- (_Bool)slot:(id)arg1 shouldProcessAdResponse:(id)arg2 error:(id *)arg3;
- (void)didMoveToWindow;
- (void)loadRequest:(id)arg1;
- (id)viewHierarchyInformationForSlot:(id)arg1;
- (void)cacheViewHierarchyInformationForSlot:(id)arg1;
- (void)slotWillLeaveApplication:(id)arg1;
- (void)slotDidDismissScreen:(id)arg1;
- (void)slotWillDismissScreen:(id)arg1;
- (void)slotWillPresentScreen:(id)arg1;
- (_Bool)slot:(id)arg1 shouldChangeAudioSessionCategoryTo:(id)arg2;
- (void)slot:(id)arg1 didFailToLoadAdContentWithError:(id)arg2;
- (void)slotFinishedLoadingAdContent:(id)arg1;
- (_Bool)slot:(id)arg1 shouldLoadRequest:(id)arg2 error:(id *)arg3;
- (void)layoutSubviewsIfNeeded;
- (void)slot:(id)arg1 contentSizeDidChange:(struct CGSize)arg2;
- (id)swipeToViewControllerView;
- (struct CGRect)frameInInterface;
- (void)slot:(id)arg1 didReceiveAdView:(id)arg2;
- (_Bool)slotShouldReloadCurrentRequest:(id)arg1;
- (id)requestParametersForRequest:(id)arg1;
- (void)setAdOptions:(id)arg1;
- (void)setAlpha:(double)arg1;
@property(readonly, copy, nonatomic) NSString *adNetworkClassName;
@property(readonly, nonatomic) __weak UIView *mediatedAdView;
@property(readonly, nonatomic) _Bool hasAutoRefreshed;
@property(readonly, nonatomic) __weak GADAdView *adView;
@property(nonatomic) struct GADAdSize adSize;
- (void)setAdSizeFromExternalCGSize:(struct CGSize)arg1;
- (void)setMediated;
@property(copy, nonatomic) NSDictionary *bannerKey;
@property(copy, nonatomic) NSString *adUnitID;
- (void)commonLayoutSubviews;
- (void)layoutSubviews;
- (struct CGSize)intrinsicContentSize;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setAdSize:(struct GADAdSize)arg1 andReload:(_Bool)arg2;
- (void)dealloc;
- (id)initWithAdSize:(struct GADAdSize)arg1 origin:(struct CGPoint)arg2;
- (id)initWithAdSize:(struct GADAdSize)arg1;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 adSize:(struct GADAdSize)arg2;
- (void)commonInitWithAdSize:(struct GADAdSize)arg1;
- (void)rootObjectLoggerChanged;
- (void)bannerAdLoadFailedWithError:(id)arg1;
- (void)bannerAdLoadSucceeded;
- (void)bannerAdLoadStarted;
- (void)bannerCreatedSlot:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

