//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GADCustomEventRequest, NSString;
@protocol GADCustomEventBannerDelegate;

@protocol GADCustomEventBanner <NSObject>
@property(nonatomic) __weak id <GADCustomEventBannerDelegate> delegate;
- (void)requestBannerAd:(struct GADAdSize)arg1 parameter:(NSString *)arg2 label:(NSString *)arg3 request:(GADCustomEventRequest *)arg4;
@end

