//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GADGMSGHandler.h"

@protocol GADDelayLoadDelegate;

@interface GADDelayPageLoadGMSGHandler : GADGMSGHandler
{
    long long _delayCount;
    id <GADDelayLoadDelegate> _delegate;
}

+ (id)actionBlockDictionary;
- (void).cxx_destruct;
- (void)handleDelayLoadWithParameters:(id)arg1;
- (void)adView:(id)arg1 delayPageLoadWithArguments:(id)arg2;
- (id)initWithDelegate:(id)arg1;
- (id)init;

@end

