//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CMMotionManager;
@protocol OS_dispatch_queue;

@interface GADGLSphericalShader : NSObject
{
    unsigned int _glProgram;
    int _uniformColorConversionMatrix;
    int _uniformFOVx;
    int _uniformFOVy;
    int _uniformVMat;
    struct __CVOpenGLESTextureCache *_videoTextureCache;
    struct __CVBuffer *_lumaTexture;
    struct __CVBuffer *_chromaTexture;
    CMMotionManager *_motionManager;
    union _GLKMatrix4 _externalPitchRotation;
    union _GLKMatrix4 _externalRollRotation;
    double _externalRollMultiplier;
    double _externalPitchMultiplier;
    long long _lastApplicationOrientation;
    union _GLKMatrix4 _orientationOffsetRotationY;
    _Bool _firstRenderingOrientationHandled;
    NSObject<OS_dispatch_queue> *_lockQueue;
}

- (void).cxx_destruct;
@property long long lastApplicationOrientation;
- (void)updateApplicationOrientation;
- (union _GLKMatrix4)deviceRotationMatrix;
- (void)destroyOpenGLProgram;
- (struct __CVBuffer *)createTextureWithPixelBuffer:(struct __CVBuffer *)arg1 index:(int)arg2 format:(int)arg3 width:(int)arg4 height:(int)arg5;
- (_Bool)setUpOpenGL;
- (void)cleanupTextures;
- (void)displayPixelBuffer:(struct __CVBuffer *)arg1 inViewPortRect:(struct CGRect)arg2;
- (void)handleUserTouchMovedByVector:(struct CGVector)arg1;
- (void)stopMotionTracking;
- (void)startMotionTracking;
- (void)dealloc;
- (id)init;
- (id)initWithTouchPitchMultiplier:(double)arg1 touchRollMultiplier:(double)arg2;

@end

