//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GADInterstitialPoolRefilling-Protocol.h"

@class NSMutableSet, NSString;
@protocol OS_dispatch_queue;

@interface GADInterstitialPoolGroupRefillPolicy : NSObject <GADInterstitialPoolRefilling>
{
    NSMutableSet *_pools;
    NSObject<OS_dispatch_queue> *_lockQueue;
}

- (void).cxx_destruct;
- (void)addPool:(id)arg1;
- (void)fillPools;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

