//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FlurryAdBannerDelegate-Protocol.h"
#import "FlurryAdInterstitialDelegate-Protocol.h"
#import "FlurryAdNativeDelegate-Protocol.h"
#import "GADMAdNetworkAdapter-Protocol.h"

@class FlurryAdBanner, FlurryAdInterstitial, FlurryAdNative, FlurryMediatedNativeAd, GADNativeAdImageAdLoaderOptions, GADNativeAdViewAdOptions, NSString, UIView;
@protocol GADMAdNetworkConnector;

@interface GADMAdapterFlurryAppCircle : NSObject <FlurryAdBannerDelegate, FlurryAdInterstitialDelegate, FlurryAdNativeDelegate, GADMAdNetworkAdapter>
{
    _Bool _shouldDownloadNativeImages;
    _Bool _shouldLoadContentAds;
    _Bool _shouldLoadAppInstallAds;
    id <GADMAdNetworkConnector> _connector;
    GADNativeAdImageAdLoaderOptions *_nativeAdimageLoaderOptions;
    GADNativeAdViewAdOptions *_nativeAdViewOptions;
    FlurryAdBanner *_bannerAd;
    FlurryAdInterstitial *_interstitialAd;
    FlurryAdNative *_nativeAd;
    FlurryMediatedNativeAd *_flurryMediatedNativeAd;
    UIView *_bannerAdView;
}

+ (Class)networkExtrasClass;
+ (id)adapterVersion;
@property(nonatomic) _Bool shouldLoadAppInstallAds; // @synthesize shouldLoadAppInstallAds=_shouldLoadAppInstallAds;
@property(nonatomic) _Bool shouldLoadContentAds; // @synthesize shouldLoadContentAds=_shouldLoadContentAds;
@property(nonatomic) _Bool shouldDownloadNativeImages; // @synthesize shouldDownloadNativeImages=_shouldDownloadNativeImages;
@property(retain, nonatomic) UIView *bannerAdView; // @synthesize bannerAdView=_bannerAdView;
@property(retain, nonatomic) FlurryMediatedNativeAd *flurryMediatedNativeAd; // @synthesize flurryMediatedNativeAd=_flurryMediatedNativeAd;
@property(retain, nonatomic) FlurryAdNative *nativeAd; // @synthesize nativeAd=_nativeAd;
@property(retain, nonatomic) FlurryAdInterstitial *interstitialAd; // @synthesize interstitialAd=_interstitialAd;
@property(retain, nonatomic) FlurryAdBanner *bannerAd; // @synthesize bannerAd=_bannerAd;
@property(nonatomic) __weak GADNativeAdViewAdOptions *nativeAdViewOptions; // @synthesize nativeAdViewOptions=_nativeAdViewOptions;
@property(nonatomic) __weak GADNativeAdImageAdLoaderOptions *nativeAdimageLoaderOptions; // @synthesize nativeAdimageLoaderOptions=_nativeAdimageLoaderOptions;
@property(nonatomic) __weak id <GADMAdNetworkConnector> connector; // @synthesize connector=_connector;
- (void).cxx_destruct;
- (id)configureTargeting;
- (_Bool)isConnectorConfigured;
- (_Bool)isNativeAppInstallAd:(id)arg1;
- (void)adNativeWillPresent:(id)arg1;
- (void)adNativeWillLeaveApplication:(id)arg1;
- (void)adNativeWillDismiss:(id)arg1;
- (void)adNativeDidLogImpression:(id)arg1;
- (void)adNativeDidReceiveClick:(id)arg1;
- (void)adNativeDidDismiss:(id)arg1;
- (void)adNative:(id)arg1 adError:(int)arg2 errorDescription:(id)arg3;
- (void)adNativeDidFetchAd:(id)arg1;
- (void)adInterstitialWillPresent:(id)arg1;
- (void)adInterstitialWillLeaveApplication:(id)arg1;
- (void)adInterstitialWillDismiss:(id)arg1;
- (void)adInterstitialDidReceiveClick:(id)arg1;
- (void)adInterstitialDidDismiss:(id)arg1;
- (void)adInterstitial:(id)arg1 adError:(int)arg2 errorDescription:(id)arg3;
- (void)adInterstitialDidFetchAd:(id)arg1;
- (void)adBannerWillLeaveApplication:(id)arg1;
- (void)adBannerDidReceiveClick:(id)arg1;
- (void)adBanner:(id)arg1 adError:(int)arg2 errorDescription:(id)arg3;
- (void)adBannerDidFetchAd:(id)arg1;
- (_Bool)handlesUserImpressions;
- (_Bool)handlesUserClicks;
- (void)getNativeAdWithAdTypes:(id)arg1 options:(id)arg2;
- (void)presentInterstitialFromRootViewController:(id)arg1;
- (void)getInterstitial;
- (_Bool)isBannerAnimationOK:(long long)arg1;
- (void)getBannerWithSize:(struct GADAdSize)arg1;
- (void)stopBeingDelegate;
- (id)initWithGADMAdNetworkConnector:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

