//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UIView, UIViewController;
@protocol GADMediatedNativeAd;

@protocol GADMediatedNativeAdDelegate <NSObject>

@optional
- (void)mediatedNativeAd:(id <GADMediatedNativeAd>)arg1 didUntrackView:(UIView *)arg2;
- (void)mediatedNativeAd:(id <GADMediatedNativeAd>)arg1 didRecordClickOnAssetWithName:(NSString *)arg2 view:(UIView *)arg3 viewController:(UIViewController *)arg4;
- (void)mediatedNativeAdDidRecordImpression:(id <GADMediatedNativeAd>)arg1;
- (void)mediatedNativeAd:(id <GADMediatedNativeAd>)arg1 didRenderInView:(UIView *)arg2 viewController:(UIViewController *)arg3;
@end

