//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GADResourceCache, NSError;

@protocol GADResourceCacheDelegate <NSObject>

@optional
- (void)resourceCache:(GADResourceCache *)arg1 didFailCachingWithError:(NSError *)arg2;
- (void)resourceCacheDidSucceededCaching:(GADResourceCache *)arg1;
- (void)resourceCacheDidReceiveResponse:(GADResourceCache *)arg1;
- (void)resourceCacheDidStartCaching:(GADResourceCache *)arg1;
@end

