//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class GADLocation, NSArray, NSDate, NSDictionary, NSMutableDictionary, NSNumber, NSString;

@interface GADRequest : NSObject <NSCopying>
{
    NSMutableDictionary *_networkExtrasMap;
    _Bool _nativeExpressEnabled;
    NSArray *_testDevices;
    long long _gender;
    NSDate *_birthday;
    NSArray *_keywords;
    NSString *_contentURL;
    NSString *_requestAgent;
    GADLocation *_location;
    NSNumber *_childDirectedTreatment;
    NSDictionary *_customTargeting;
    NSDictionary *_privateMediationExtras;
    NSArray *_formatParameters;
    long long _responseType;
    NSDictionary *_adConfigurationParameters;
    NSString *_origin;
}

+ (id)sdkVersion;
+ (long long)requestTypeFromString:(id)arg1;
+ (void)initialize;
+ (id)request;
+ (id)requestWithMediationAdRequest:(id)arg1;
+ (id)extendedSDKVersionNumber;
+ (id)sdkVersionIdentifiers;
+ (id)sdkVersionMetadata;
@property(nonatomic, getter=isNativeExpressEnabled) _Bool nativeExpressEnabled; // @synthesize nativeExpressEnabled=_nativeExpressEnabled;
@property(copy, nonatomic) NSString *origin; // @synthesize origin=_origin;
@property(copy, nonatomic) NSDictionary *adConfigurationParameters; // @synthesize adConfigurationParameters=_adConfigurationParameters;
@property(nonatomic) long long responseType; // @synthesize responseType=_responseType;
@property(copy, nonatomic) NSArray *formatParameters; // @synthesize formatParameters=_formatParameters;
@property(copy, nonatomic) NSDictionary *privateMediationExtras; // @synthesize privateMediationExtras=_privateMediationExtras;
@property(copy, nonatomic) NSDictionary *customTargeting; // @synthesize customTargeting=_customTargeting;
@property(copy, nonatomic) NSNumber *childDirectedTreatment; // @synthesize childDirectedTreatment=_childDirectedTreatment;
@property(copy, nonatomic) GADLocation *location; // @synthesize location=_location;
@property(copy, nonatomic) NSString *requestAgent; // @synthesize requestAgent=_requestAgent;
@property(copy, nonatomic) NSString *contentURL; // @synthesize contentURL=_contentURL;
@property(copy, nonatomic) NSArray *keywords; // @synthesize keywords=_keywords;
@property(copy, nonatomic) NSDate *birthday; // @synthesize birthday=_birthday;
@property(nonatomic) long long gender; // @synthesize gender=_gender;
@property(copy, nonatomic) NSArray *testDevices; // @synthesize testDevices=_testDevices;
- (void).cxx_destruct;
- (void)setLocationWithDescription:(id)arg1;
- (void)setBirthdayWithMonth:(long long)arg1 day:(long long)arg2 year:(long long)arg3;
@property(readonly, nonatomic) _Bool cacheable;
- (id)parameters;
- (id)threadSafeParameters;
- (_Bool)isATestDevice;
- (void)tagForChildDirectedTreatment:(_Bool)arg1;
- (void)setLocationWithLatitude:(double)arg1 longitude:(double)arg2 accuracy:(double)arg3;
- (id)contentURLString;
- (id)birthdayString;
- (id)genderString;
- (id)networkExtrasAdditionalParameters;
- (void)removeAdNetworkExtrasFor:(Class)arg1;
- (id)adNetworkExtrasFor:(Class)arg1;
- (void)registerAdNetworkExtras:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithParameters:(id)arg1;
- (id)init;
- (void)configureNetworkExtrasWithMediationAdRequest:(id)arg1;
- (void)addAdapterListWithMediationAdRequest:(id)arg1;

@end

