//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GADVideoOptions;

@protocol GADVideoControlling <NSObject>
- (_Bool)customControlsEnabled;
- (double)aspectRatio;
- (_Bool)hasVideoContent;
- (void)setInitialStateWithVideoOptions:(GADVideoOptions *)arg1;
- (void)pause;
- (void)play;
- (void)setMute:(_Bool)arg1;
@end

