//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 30 2018 09:46:22).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GADAdLoaderOptions.h"

@interface GADVideoOptions : GADAdLoaderOptions
{
    _Bool _startMuted;
    _Bool _customControlsRequested;
}

@property(nonatomic) _Bool customControlsRequested; // @synthesize customControlsRequested=_customControlsRequested;
@property(nonatomic) _Bool startMuted; // @synthesize startMuted=_startMuted;
- (id)requestParameters;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

