@interface Ringtones.SelectedRingtoneViewController: UIViewController  
{
	__unknown__ closeButton;
	__unknown__ titleLabel;
	__unknown__ tagsIcon;
	__unknown__ tagsLabel;
	__unknown__ downloadButton;
	__unknown__ shareButton;
	__unknown__ infoButton;
	__unknown__ progressView;
	__unknown__ downloadProgressView;
	__unknown__ activityIndicator;
	__unknown__ playButton;
	__unknown__ shareButtonLeadingConstraint;
	__unknown__ tagsLabelRightConstraint;
	__unknown__ selectedCell;
	__unknown__ itemPosition;
	__unknown__ sectionName;
	__unknown__ item;
	__unknown__ onClose;
	__unknown__ rootNavigationController;
	__unknown__ isPlaying;
	__unknown__ displayLink;
	__unknown__ downloadProgressLayer;
	__unknown__ errorOverLay;
}

@property (non-atomic, __weak) UIButton * closeButton;
@property (non-atomic, __weak) UILabel * titleLabel;
@property (non-atomic, __weak) UIImageView * tagsIcon;
@property (non-atomic, __weak) UILabel * tagsLabel;
@property (non-atomic, __weak) UIButton * downloadButton;
@property (non-atomic, __weak) UIButton * shareButton;
@property (non-atomic, __weak) UIButton * infoButton;
@property (non-atomic, __weak) _TtCRingtonesProgressBarView * progressView;
@property (non-atomic, __weak) _TtCRingtonesProgressBarView * downloadProgressView;
@property (non-atomic, __weak) UIActivityIndicatorView * activityIndicator;
@property (non-atomic, __weak) UIButton * playButton;
@property (non-atomic, __weak) NSLayoutConstraint * shareButtonLeadingConstraint;
@property (non-atomic, __weak) NSLayoutConstraint * tagsLabelRightConstraint;
@property (non-atomic) long long itemPosition;
@property (non-atomic, copy) NSString * sectionName;
@end
 +(id)create:(id)arg1;
 -(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2;
 -(void)errorOccured;
 -(void)closeTapped;
 -(id)tagsIcon;
 -(void)setTagsIcon:(id)arg1;
 -(id)downloadProgressView;
 -(void)setDownloadProgressView:(id)arg1;
 -(id)shareButtonLeadingConstraint;
 -(void)setShareButtonLeadingConstraint:(id)arg1;
 -(id)tagsLabelRightConstraint;
 -(void)setTagsLabelRightConstraint:(id)arg1;
 -(long long)itemPosition;
 -(void)setItemPosition:(long long)arg1;
 -(void)saveTapped;
 -(void)itemInfoTapped:(id)arg1;
 -(void)playTapped:(id)arg1;
 -(void)shareTapped;
 -(void)openRingtoneGuideTapped;
 -(void)updateProgress;
 -(id (^block)(...)).cxx_destruct;
 -(void)hide;
 -(void)show;
 -(id)initWithCoder:(id)arg1;
 -(id)titleLabel;
 -(id)initWithNibName:(id)arg1 bundle:(id)arg2;
 -(void)viewDidLoad;
 -(void)viewWillDisappear:(BOOL)arg1;
 -(void)close;
 -(id)activityIndicator;
 -(void)setActivityIndicator:(id)arg1;
 -(id)infoButton;
 -(void)setInfoButton:(id)arg1;
 -(void)setTitleLabel:(id)arg1;
 -(id)sectionName;
 -(void)setSectionName:(id)arg1;
 -(id)progressView;
 -(void)setProgressView:(id)arg1;
 -(void)setShareButton:(id)arg1;
 -(id)shareButton;
 -(id)playButton;
 -(void)setCloseButton:(id)arg1;
 -(id)closeButton;
 -(void)setPlayButton:(id)arg1;
 -(id)downloadButton;
 -(id)tagsLabel;
 -(void)setDownloadButton:(id)arg1;
 -(void)setTagsLabel:(id)arg1;